### PR TITLE
Promote stats-d emitter to a core extension

### PR DESCRIPTION
**Pull request by suneet-s**
### Description

Move the stats-d emitter to a core extension. 

AFAICT we are using the latest version of the java client https://github.com/DataDog/java-dogstatsd-client/releases/tag/v4.0.0

I have tried running this extension in a cluster and haven't noticed any issues. I did notice that not all metrics are reported in the default configuration. I've added 2 more metrics to be reported by default `coordinator/global/time` and `coordinator/time` as these are helpful in knowing how long different coordinator duties are taking.

I had considered a system to automatically detect when a new metric was reported so that we don't forget to update the config of this emitter when a new metric is added, however, I could not think of a reliable way to do this, so I decided to leave it out of the change that promotes this extension to a core extension.

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by maytasm — APPROVED** [review]

**Review by zachjsh — COMMENTED** [review]
LGTM 🚢

**Review by zachjsh — APPROVED** [review]
LGTM 🚢

**Comment by clintropolis** [comment]
>I had considered a system to automatically detect when a new metric was reported so that we don't forget to update the config of this emitter when a new metric is added, however, I could not think of a reliable way to do this, so I decided to leave it out of the change that promotes this extension to a core extension.

related #11958

**Review by clintropolis — APPROVED** [review]

**Review by clintropolis — CHANGES_REQUESTED** [review]
oh a couple more things need fixing, 
https://github.com/apache/druid/blob/master/website/sidebars.json#L282

and also please add an entry to redirects file https://github.com/apache/druid/blob/master/website/redirects.json

**Comment by suneet-s** [comment]
> oh a couple more things need fixing, https://github.com/apache/druid/blob/master/website/sidebars.json#L282 https://github.com/apache/druid/blob/master/website/.spelling#L721
> 
> and also please add an entry to redirects file https://github.com/apache/druid/blob/master/website/redirects.json

How did you find these links? Is there a test already for stuff like this?

**Comment by clintropolis** [comment]
>How did you find these links? Is there a test already for stuff like this?
Heh good question, something like a spidey sense I guess after I pressed approve if there were any sneaky things to consider. 

>Is there a test already for stuff like this?
Sidebars isn't really testable because its controlling which things should be shown/hidden on the docs page nav sidebar, so is subjective. Spelling exceptions are not checked that the page they are referring to exists (though i'm unsure why we don't have just a giant exception list instead of that + per page exceptions...). Redirects could possibly be checked if we detect a diff that moves a doc page, but is currently not.

**Comment by suneet-s** [comment]
glad your spidey senses kicked in 😅  I'll push up another patch with those fixes as soon as I get this license check job to pass locally

**Comment by FrankChen021** [comment]
Should the group id of this extension be changed from `org.apache.druid.extensions.contrib` to `org.apache.druid.extensions` ?

**Pull request closed without merging**
