### PR TITLE
[Backport] cleanup temp files for nested column serializer

### PR DESCRIPTION
**Pull request by clintropolis**
Backport of #15236 to 28.0.0.

### CODE REVIEW

**Comment by LakshSingla** [comment]
Can you please PTAL at the failing test?

**Comment by clintropolis** [comment]
> Can you please PTAL at the failing test?

Strange, seems completely unrelated to changes in this PR since is big decimal extension, but .. i can add a fix for it :shrug:

**Comment by LakshSingla** [comment]
Seems weird that it fails on this branch, but the original CI is green. Did you have a merge conflict while creating the backport?

**Comment by LakshSingla** [comment]
The test started failing recently, I suspect it's perhaps due to the null handling stuff that was recently changed but somehow slipped through CI. I see the same failure in `master` as well.  Nevertheless, it seems unrelated to the PR so going ahead with the merge.

**Review by LakshSingla — APPROVED** [review]

**Pull request merged**
