### PR TITLE
Free Druid source code from Guava by shading

### LINKED ISSUE #6942: Shade Guava manually
It's suggested to create a module called "guava" in Druid that copies the Guava source tree (without tests) and prohibit using the real Guava in Druid source code via Checkstyle.

Shading Guava automatically using a plugin is not possible because Druid's dependencies depend on older Guava versions that are binary-incompatible with the freshest Guava. Repackaging all such dependencies doesn't seem to be a feasible task.

One could say that copying source code of a library is bad because we won't receive updates and bug fixes that happen in the upstream, but we aren't receiving them currently anyway, using the ancient 16.0.1 version!

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #6942

### Description

This might look like a large PR but most changes are mechanical i.e. updates to import statements and guava dependency in various pom files.

Here is the meaty part...

1.  A new module "shaded-guava" is introduced that produces classes in "org.apache.druid.com.google.common" package by shading real guava. See `shaded-guava/pom.xml` . 
2.  pom.xml in all modules are made to depend upon shaded guava jar above instead of real guava, that change looks like
```
-      <groupId>com.google.guava</groupId>
+      <groupId>org.apache.druid.com.google.guava</groupId>
```
3. In all Java files, `import com.google.common.X` is replaced by `import org.apache.druid.com.google.guava.X`
4.  "Organize Imports" is done to all Java files to correct import ordering or checkstyles fails
5. Some imports in `cloudfiles-extensions` and `sql` modules are reverted to use `import com.google.common.X` because their dependencies `jclouds-core` and `calcite` respectively mandate using real `import com.google.common.X` in various methods exposed by those libraries. But this is minimal.
6. some imports that used `org.apache.curator.shaded.com.google.common.X` , i.e. shaded version of guava used by curator, continue to use same. that is independent.

(this approach was briefly described in https://github.com/apache/druid/issues/6942#issuecomment-791029487 )

End Result is that Druid source code is free from real guava and can use any version of guava inside `shaded-guava` module, few exceptions in (5) as described above.
we still ship guava-0.16.1.jar like before, so no external integrations should see any impact. User should be able to switch this with their favorite version of guava jar at runtime and Druid source code be fine because it uses druid-shaded-guava-0.x.y.jar 

Existing Unit, Integration Tests and Travis builds should cover all of the changes except for Hadoop Integration that I could not verify due to not having quick access to such setup. However, given the way this patch works and that we continue to ship existing guava jar, Hadoop Integration should see no change.

https://github.com/apache/druid/issues/10965 should also be done after this PR is accepted.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by himanshug** [comment]
Ah, this PR is very prone to merge conflicts due to the sweeping changes made. However, this PR can be reviewed in the presence of conflicts [with mechanical changes described in PR description]. I will fix all the conflicts when this PR is accepted and ready to be merged.

**Comment by mghosh4** [comment]
This looks good to me. @himanshug when are we planning to commit this?

**Comment by himanshug** [comment]
@mghosh4 needs to get review/approval before it can be merged.

**Comment by egor-ryashin** [comment]
Looks good, @himadrisingh  I wonder if `extensions-core/hive-extensions/pom.xml` was added by mistake?

**Comment by egor-ryashin** [comment]
Looks like `ambari-metrics-emitter` will fail without guava 16:

```
mvn dependency:tree
...
[INFO] +- org.apache.ambari:ambari-metrics-common:jar:2.7.0.0.0:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.2.2:compile
[INFO] |  +- com.google.guava:guava:jar:16.0.1:compile
```

**Comment by himanshug** [comment]
> Looks good, .. I wonder if extensions-core/hive-extensions/pom.xml was added by mistake?

yes

**Comment by egor-ryashin** [comment]
We need to merge the ticket, it will solve a bunch of problems and people waiting for it.

**Comment by himanshug** [comment]
@egor-ryashin Thanks. Unfortunately I will not be able to spend much time on it in the near future. Please feel free to take the commits here , create a new PR with conflicts resolved and any other files that were added later.

**Pull request closed without merging**
