### PR TITLE
netty 4.1.107

### PR DESCRIPTION
**Pull request by sullis**
### Description

upgrade to latest Netty (4.1.107)

https://netty.io/news/2024/02/13/4-1-107-Final.html

This PR has:

- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by cryptoe** [comment]
Can you please update the licenses.yaml file.

**Comment by cryptoe** [comment]
LGTM post that.

**Comment by sullis** [comment]
> Can you please update the licenses.yaml file.

Done.

**Comment by sullis** [comment]
PTAL @cryptoe

**Review by abhishekagarwal87 — APPROVED** [review]

**Review by asdf2014 — APPROVED** [review]

**Pull request merged**
