### PR TITLE
Web console: make supervisor reset really scary in the UI

### PR DESCRIPTION
**Pull request by vogievetsky**
Do a better job of conveying just how drastic a supervisor reset is to the user.

This PR does two things:

- Renames "Reset" to "Hard reset" to make it sound scarier and look less like "Restart"
- Makes the user tick a few boxes to ensure they know what they are getting themselves into

image

image

### CODE REVIEW

**Comment by vogievetsky** [comment]
@gianm I really wanted there to be 3 checkboxes because that feels right.
You think we should avoid a 'really intense' checkbox?

**Comment by vogievetsky** [comment]
FWIW I dialed down the intensity from my initial plan. Initially I thought you would enter your name and SSN and then we do a hard credit score pull with Transunion. This will allow us yo both verify who you are and ensure that you are a responsible person (credit score must be at least 500 to reset a supervisor).

**Comment by vogievetsky** [comment]
Ok here:

image

Although I still think 3 warnings would look ascetically better.

**Comment by sthetland** [comment]
I took a quick look at doc impact. The only existing doc I could find where this concept is touched upon is https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html#resetting-supervisors (and equivalent section in the Kinesis page). 

That section can throttle up the fear factor a bit, but it would be good to put the explanation in docs that are set in the context of UI doc (rather than this operation endpoint doc linked). This would be a larger effort though, I as don't see an existing logical spot for that doc. Something for me to work on. 

Meanwhile, taking a stab at how to reword the existing section to induce more fear, for one thing, by moving possible ill effects up :

```
The `POST /druid/indexer/v1/supervisor/<supervisorId>/reset` operation clears stored 
offsets, causing the supervisor to start reading offsets from either the earliest or latest 
offsets in Kafka (depending on the value of useEarliestOffset). After clearing stored 
offsets, the supervisor kills and recreates any active tasks, so that tasks begin reading 
from valid offsets. 

Use care when using this operation! Resetting the supervisor may cause Kafka messages 
to be skipped or read twice, resulting in missing or duplicate data. 

The reason for using this operation is to recover from a state in which the supervisor 
ceases operating due to missing offsets. The indexing service keeps track of the latest 
persisted Kafka offsets in order to provide exactly-once ingestion guarantees across 
tasks. Subsequent tasks must start reading from where the previous task completed in 
order for the generated segments to be accepted. If the messages at the expected 
starting offsets are no longer available in Kafka (typically because the message retention 
period has elapsed or the topic was removed and re-created) the supervisor will refuse 
to start and in flight tasks will fail.

This operation enables you to recover from this condition. Note that the supervisor 
must be running for this endpoint to be available.
```

(Change applies to https://github.com/apache/druid/blob/master/docs/development/extensions-core/kafka-ingestion.md)

Let me know if my rewrite is accurate (and addresses the goal). If so, I’ll file a doc ticket/PR (or add it to this one?)

**Comment by vogievetsky** [comment]
That rewrite looks much better to me than the existing thing. Does it make sense to include `The reason for using this operation is to recover from a state in which the supervisor 
ceases operating due to missing offsets.` in the UI text also?

**Comment by sthetland** [comment]
> ... Does it make sense to include `The reason for using this operation is to recover from a state in which the supervisor ceases operating due to missing offsets.` in the UI text also?

Yes, I think it should. 

However, at a glance, I'm not sure where that text would go in the UI (if I'm looking at the right place, which is in the Druid console at the Ingestion tab - Supervisors pane - [wrench menu]). Should that operations menu have tool-tip style/pop-up help for its items? Anyway, yes, and if there's not a good place to put it, we should chat about adding.

**Comment by vogievetsky** [comment]
I was thinking of adding it in the dialog text like so:

image

(added it)

**Pull request merged**
