### PR TITLE
fix 'is not null' is invalid for array-type in druid-sql

### LINKED ISSUE #10525: Incorrect results (including nulls) when querying string column with col <> '' and col is not null
### Affected Version
0.18.0 and 0.20.0

### Description
For druid 0.18.0 and config useDefaultValueForNull to false, querying a table with condition on string column (lets say col) with condition like col <> '' and col is not null returns rows with that column null. Both of these conditions behave correctly if passed separately but when together, nulls are not filtered at all.
- Cluster size
Local docker setup
- Configurations in use 
useDefaultValueForNull is False
- Steps to reproduce the problem
1. Setup local druid 0.18.0 using docker setup
2. Load example data viz. wikipedia
3. Query: select * from wikipedia where cityName is not null and cityName <> '' limit 100
- The error message or stack traces encountered.
In the results you can see rows with cityName null as well
- Any debugging that you have already done
I tested it with version 0.18.0 and 0.20.0 and both have these issue

### PR DESCRIPTION
**Pull request by chenyuzhi459**
Fixes #10525 

### Description
Fix the bug : incorrect results (including nulls) when querying string-array column(let's say it's `col`) with col <> '' and col is not null 

Reason: When we use `is not null`  filter in SQL, Calcite will treat it  as `truefilter` through call stack as beflow:
`DruidPlanner.plan(final String sql) -> PlannerImpl.rel(SqlNode sql) ->SqlToRelConverter.convertQuery(SqlNode query, boolean needsValidation, boolean top) ->SqlToRelConverter.convertQueryRecursive(SqlNode query, boolean top, RelDataType targetRowType)->SqlToRelConverter.convertSelect(SqlSelect select, boolean top) -> SqlToRelConverter.convertSelectImpl(SqlToRelConverter.Blackboard bb, SqlSelect select) -> SqlToRelConverter.convertWhere(SqlToRelConverter.Blackboard bb, SqlNode where) -> RexCall.isAlwaysTrue()-> AbstractSqlType.isNullable()`

The last method `AbstractSqlType.isNullable()` will return false in our arrayColumnType. Because in the method `Calcites.createSqlArrayTypeWithNullability()`, we only specify `nullable` praram for elementType in arrayColumnType,
however, `typeFactory.createArrayType()` will invoke ` new ArraySqlType(elementType, false)` to return  a new RelDataType.
Thus, we will got  incorrect results (including nulls) when use `is not null`

Solution: support specify  `nullable` praram for  arrayColumnType

<hr>

This PR has:
- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `org.apache.druid.sql.calcite.planner.Calcites`

### CODE REVIEW

**Review by clintropolis — COMMENTED** [review]
:+1: thanks for the fix, this was my bad I think 😅 

Any chance you could add a test for this case? https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java is the catch-all bucket where we typically add functional query tests, and https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java is where you can find the data that these tests operate on, if it helps.

**Comment by chenyuzhi459** [comment]
> 👍 thanks for the fix, this was my bad I think 😅
> 
> Any chance you could add a test for this case? https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java is the catch-all bucket where we typically add functional query tests, and https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java is where you can find the data that these tests operate on, if it helps.

ok, i will add a test on https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java

**Comment by chenyuzhi459** [comment]
>  thanks for the fix, this was my bad I think 
> 
> Any chance you could add a test for this case? https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java is the catch-all bucket where we typically add functional query tests, and https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java is where you can find the data that these tests operate on, if it helps.

Hey, i had try to add a test in https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java.
However, I can not  simulate a filter of `string_array` column,because we treat `string_array` column as `string` column in the `org.apache.druid.sql.calcite.schema.DruidSchema.analysisToRowSignature()`. For example, `dim3` column in table 'foo' is a multivalue column, and in the schema ,it convert to a string column simply.

**Comment by clintropolis** [comment]
>Hey, i had try to add a test in https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java.
However, I can not simulate a filter of string_array column,because we treat string_array column as string column in the org.apache.druid.sql.calcite.schema.DruidSchema.analysisToRowSignature(). For example, dim3 column in table 'foo' is a multivalue column, and in the schema ,it convert to a string column simply.

Hmm, yeah, true array types aren't quite fully supported throughout the query engine yet. We've got some functions to interact with multi-value string dimensions as if they were arrays, as well as array constants, but the result row signatures are still for the most part non-array types because it's not quite there yet (no grouping on the rows as complete arrays for example). You might be able to use an [array constant on a scan query to get the right row signature](https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java#L15055), but I'm not certain about that because in the native druid query, array types will still currently end up as STRING virtual columns I believe.

**Comment by chenyuzhi459** [comment]
> > Hey, i had try to add a test in https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java.
> > However, I can not simulate a filter of string_array column,because we treat string_array column as string column in the org.apache.druid.sql.calcite.schema.DruidSchema.analysisToRowSignature(). For example, dim3 column in table 'foo' is a multivalue column, and in the schema ,it convert to a string column simply.
> 
> Hmm, yeah, true array types aren't quite fully supported throughout the query engine yet. We've got some functions to interact with multi-value string dimensions as if they were arrays, as well as array constants, but the result row signatures are still for the most part non-array types because it's not quite there yet (no grouping on the rows as complete arrays for example). You might be able to use an [array constant on a scan query to get the right row signature](https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java#L15055), but I'm not certain about that because in the native druid query, array types will still currently end up as STRING virtual columns I believe.

Thanks for your tips, I have try to run `testSelectConstantArrayExpressionFromTable()` in `CalciteQueryTest.java`, however i found in the rowsignature, all column is treated as asingle-string column。And I found if i want to change the rowsignature of multi-string value, it will have a huge change on the source code. In this  situation， it's hard to add a test for my code in `createSqlArrayTypeWithNullability(typeFactory,elementTypeName,nullable)`.

**Comment by clintropolis** [comment]
>And I found if i want to change the rowsignature of multi-string value, it will have a huge change on the source code.

Ah yeah, don't do that 😅 

Hmm, I guess i'm having trouble determining how this bug is hit if we can't replicate it in the tests. I guess this area of the code has seem a fair bit of refactor over the last few releases, so maybe it used to be possible? That said, it seems like it should be a harmless change. I'll have a closer look and see if I can think of a way to trigger it.

**Comment by chenyuzhi459** [comment]
> > And I found if i want to change the rowsignature of multi-string value, it will have a huge change on the source code.
> 
> Ah yeah, don't do that 
> 
> Hmm, I guess i'm having trouble determining how this bug is hit if we can't replicate it in the tests. I guess this area of the code has seem a fair bit of refactor over the last few releases, so maybe it used to be possible? That said, it seems like it should be a harmless change. I'll have a closer look and see if I can think of a way to trigger it.

I have checked the latest code in master branch, and it's still return `dataType' directly in methond `Calcites.createSqlArrayTypeWithNullability`, thus it's still a potential problem there i think. And it'll be my pleasure if could provide more help for your check and trigger work.

**Comment by clintropolis** [comment]
>I have checked the latest code in master branch, and it's still return dataType' directly in methond Calcites.createSqlArrayTypeWithNullability`, thus it's still a potential problem there i think. And it'll be my pleasure if could provide more help for your check and trigger work.

Oops, forgot to look into this, sorry! I will try to have a look this weekend.

**Pull request closed without merging**
