### PR TITLE
DruidSegmentReader: Close segments properly.

### PR DESCRIPTION
**Pull request by gianm**
Two changes:

1) Call QueryableIndex.close to ensure that the memory is unmapped.
2) Use FileUtils.deleteDirectory instead of File.delete, because segments are
   directories, and so File.delete won't work on them.

### CODE REVIEW

**Review by jihoonson — COMMENTED** [review]
Nice catch :+1: Is it very hard to add unit tests? It seems possible to add some with a real but small segment file and a custom `IndexIO` that returns a custom `QueryableIndex` in `loadIndex()` that tracks of whether queryableIndex itself is closed.

**Comment by gianm** [comment]
> Nice catch 👍 Is it very hard to add unit tests? It seems possible to add some with a real but small segment file and a custom `IndexIO` that returns a custom `QueryableIndex` in `loadIndex()` that tracks of whether queryableIndex itself is closed.

I think it would be doable, I'll have a look. Before doing that, I was hoping to use CI here to see if this change has any negative effect on pre-existing tests.

**Comment by gianm** [comment]
When I run the tests locally, they crash due to HLL collectors referencing mmapped memory from a QueryableIndex that has been closed. I think we'll want to do one of the following:

- Change the contract of `intermediateRowIterator` to say that you must fully dispose of all objects before closing the iterator, and make sure all callers adhere to it.
- Implement a way to clone complex objects that may reference mmapped memory, and have DruidSegmentReader use that method, so the objects will keep working properly after the segment they came from is unmapped.
- Implement some form of refcounting for objects that reference mmapped memory.

To me the first and third ones seem like a boondoggle, because these objects can go on a pretty wild journey after the iterator closes. So the second (cloning the objects) seems cleanest. But it will have a performance hit that the other two would not. If the performance hit is acceptable, though, then that one seems best.

**Comment by gianm** [comment]
I won't have time to finish this, and at any rate, I'm more focused on MSQ these days, which doesn't have this problem. So, I'm converting this PR into an issue: #14486.

**Pull request closed without merging**
