### PR TITLE
Add a internal Aggregator to fix overestimate thetaSketch,quantilesDoublesSketch in  ingestion task

### LINKED ISSUE #6743: IncrementalIndex generally overestimates theta sketch size
Theta sketches have a very large max size by default, relative to typical row sizes (about 250KB with "size" set to the default of 16384). The ingestion-time row size estimator (getMaxBytesPerRowForAggregators in OnheapIncrementalIndex) uses this figure to estimate row sizes when theta sketches are used at ingestion time, leading to way more spills than is reasonable. It would be better to use an estimate based more on actual current size. I'm not sure how to get this, though.

@leerho - or anyone else - do you have any ideas or suggestions?

### PR DESCRIPTION
**Pull request by liuxiaohui1221**
Fixes #6743 .

 When the data source has one or more thetasketch,quantilesDoublesSketch,ingestion task(when maxBytesInMemory not -1) will generate a lot of small files and  will trigger off heap OOM when merge this spill files.

### Description
 Add a internal Aggregator to fix overestimate `thetaSketch`,`quantilesDoublesSketch`.   This PR add a new internal countAdjustmentAggregator, it is used to aggregate count and judge complex metric(for now  `thetaSketch`,`quantilesDoublesSketch`) whether reached expansion capacity threshold, and append bytes to bytesInMemory when reached.
This is a better way than #10241 on aggregation performance. The following are the aggregation test results:

  ```
Benchmark                                     (adjustFlag)  (maxBytesInMemory)  (rollup)  (rollupOpportunity)  (rowsPerSegment)  (schema)  Mode  Cnt      Score      Error  Units
ComplexMetricAdjustStrategyBenchmark.addRows          true         20000000000      true                  low             75000   complex  avgt   10  75030.753 ±  485.785  us/op
ComplexMetricAdjustStrategyBenchmark.addRows          true         20000000000      true             moderate             75000   complex  avgt   10  74210.326 ±  404.810  us/op
ComplexMetricAdjustStrategyBenchmark.addRows          true         20000000000      true                 high             75000   complex  avgt   10  74502.573 ±  230.314  us/op
ComplexMetricAdjustStrategyBenchmark.addRows         false         20000000000      true                  low             75000   complex  avgt   10  73830.057 ±  758.054  us/op
ComplexMetricAdjustStrategyBenchmark.addRows         false         20000000000      true             moderate             75000   complex  avgt   10  72092.055 ±  210.018  us/op
ComplexMetricAdjustStrategyBenchmark.addRows         false         20000000000      true                 high             75000   complex  avgt   10  72549.061 ± 1107.324  us/op

  ```

<hr>

This PR has:
- 

> 

- [x] been self-reviewed.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `MaxIntermediateSizeAdjustStrategy`
 * `ThetaSketchSizeAdjustStrategy`
 * `DoublesSketchSizeAdjustStrategy`
 * `InternalCountAdjustmentAggregator`
 * `OnheapIncrementalIndex`
 * `AggregatorFactory`
......

### CODE REVIEW

**Review by liuxiaohui1221 — COMMENTED** [review]
reviewed my code

**Comment by liuxiaohui1221** [comment]
Consuming time will increase the effect by about 15% in our test druid cluster.

**Comment by liuxiaohui1221** [comment]
I can't find reason for thisTravis-ci: [https://travis-ci.org/github/apache/druid/jobs/742105278](url)  [https://travis-ci.org/github/apache/druid/jobs/742105297](url)

**Comment by gianm** [comment]
I've been trying to solve this same problem recently and came across this PR! I'll take a look soon @liuxiaohui1221.

**Comment by liuxiaohui1221** [comment]
Ok,no problem,Thank you @gianm .

**Pull request closed without merging**
