### PR TITLE
Fix Druid Console cannot open submit supervisor dialog

### LINKED ISSUE #16589: Druid Console cannot open submit supervisor dialog
### Affected Version

29.01

### Description

When user click on Load Data -> Streaming -> Other -> Submit Supervisor, the dialog doesn't open and user is directed to the home page. 
On the other hand, Submit Task seems to work fine.

This issue was not seen in 27.0

Druid crash

### PR DESCRIPTION
**Pull request by AlbericByte**
Fixes #16589.

### Description

Fix the web console issue, cannot open submit supervisor dialog
When user click on Load Data -> Streaming -> Other -> Submit Supervisor, the dialog doesn't open and user is directed to the home page.
On the other hand, Submit Task seems to work fine. 
After modification, i have verified as following screenshot.
image

#### Release note
Fix Druid Console cannot open submit supervisor dialog

<hr>

##### Key changed/added classes in this PR
 * `console-application.tsx`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by AlbericByte** [comment]
@abhishekagarwal87 if you have free time, could you help to review this.

**Comment by FrankChen021** [comment]
introduced by #14395 ?

**Comment by AlbericByte** [comment]
@vogievetsky could you help to have a look?

**Comment by AlbericByte** [comment]
@vogievetsky welcome for any comment, i will update as soon as possible.

**Comment by AlbericByte** [comment]
hi @vogievetsky and @FrankChen021 is there anyone available to review the code changes, i think this take minor effect, and i have verified on my local environment.

**Comment by FrankChen021** [comment]
> hi @vogievetsky and @FrankChen021 is there anyone available to review the code changes, i think this take minor effect, and i have verified on my local environment.


I'm not familiar with this part, even though you have verfied that the patch works fine and I believe your change is correct, it's better that @vogievetsky can take a look to see if there's anything left behind.

**Review by vogievetsky — APPROVED** [review]
Sorry just seeing this. Thank you!

**Comment by AlbericByte** [comment]
> Sorry just seeing this. Thank you!

Thanks, i am glad i can contribute the front end code.

**Pull request merged**
