### PR TITLE
#14033 Updated case statement for ISO Year

### PR DESCRIPTION
**Pull request by saurabh111222**
Fixes #14036.

### Description

In Druid Console, enter the following SQL query and execute:

select EXTRACT(ISOYEAR FROM TIMESTAMP '2023-01-01')
Result: 2023

Expected result: 2022

Explanation: The ISO week of the date 2023-01-01 is the 52nd week of the year 2022, which should be returned by EXTRACT(ISOYEAR ...).

#### Release note
Fixed:  EXTRACT(ISOYEAR ...) now returns ISO year instead of only year. An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days.

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
can you add some PR description about the change?

**Comment by abhishekagarwal87** [comment]
@saurabh111222 - there are build failures on this PR that need looking into.

**Comment by abhishekagarwal87** [comment]
The PR description was helpful. Thank you for adding that. Please also update the docs to add this specific nuance using the example.

**Comment by saurabh111222** [comment]
> The PR description was helpful. Thank you for adding that. Please also update the docs to add this specific nuance using the example.

Thank you for helping me. As I am new to open source, your comments are really helping me in correcting the mistakes I am doing. Again I have made some changes as the previous commit was showing some build error.

**Comment by abhishekagarwal87** [comment]
@saurabh111222 - can you update the docs and add some tests?

**Pull request closed without merging**
