### PR TITLE
Enable Supervisor to Halt New Task Creation on Record Parsing Exceptions

### PR DESCRIPTION
**Pull request by YongGang**
### Description

This PR introduces functionality to prevent unnecessary task creation and associated costs when record parsing exceptions exceed the `maxAllowedParseExceptions` threshold. Currently, when this threshold is reached, the streaming ingestion task fails, and subsequent tasks continue to fail. This cycle persists until the Supervisor specification is updated to handle the problematic data or until the `maxAllowedParseExceptions` setting is increased.

With the changes introduced in this PR, if the `maxAllowedParseExceptions` limit is violated, the Supervisor will now halt the creation of new tasks. This prevents the initiation of tasks that are likely to fail due to the same parsing issues, thereby reducing unnecessary resource consumption and cost implications.

#### Release note

<hr>

##### Key changed/added classes in this PR

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by kfaraz** [comment]
Thanks for the improvement, @YongGang . It makes sense to not create new tasks if they are going to inevitably fail.

Even though this PR is still in draft, I have some suggestions/queries that you could try to incorporate early in the design:
- If the supervisor is not going to launch tasks, would it make sense to just move the supervisor to an `idle state` rather than introduce a new state?
- Rather than introduce a new config, why not reuse the existing `idleConfig` (https://druid.apache.org/docs/latest/ingestion/kafka-ingestion/#idle-configuration). That was also introduced keeping in mind cost concerns and unnecessary task launches. We could just add a new field to `idleConfig` which dictates the supervisor to become idle if `maxAllowedParseExceptions` is violated.
- It should be easy for the user to figure out __why__ the supervisor was moved to the idle state.
- Based on the PR description, this seems fairly tied in to the `maxAllowedParseExceptions` but the code changes don't seem to be using `maxAllowedParseExceptions` anywhere. Is there any other scenario where we would want to make the supervisor idle?
- What if `maxAllowedParseExceptions` keeps getting violated for some partitions and not for others. The task launched for the former partitions would always fail but should we become idle in this case or just not launch tasks to read from the bad partitions?
- I am not sure if the "no progress" check is really going to be effective or if it is even desirable. There could be other reasons behind not making progress and not all of them would qualify for making the supervisor idle.
- The `StateManager.markRunFinished()` now accepts a `Boolean` which is almost always passed as `null` except in one or two places. Please consider adding a separate method instead.

**Comment by YongGang** [comment]
Thanks for your early review @kfaraz !

> - If the supervisor is not going to launch tasks, would it make sense to just move the supervisor to an idle state rather than introduce a new state?
> 
> - Rather than introduce a new config, why not reuse the existing idleConfig (https://druid.apache.org/docs/latest/ingestion/kafka-ingestion/#idle-configuration). That was also introduced keeping in mind cost concerns and unnecessary task launches. We could just add a new field to idleConfig which dictates the supervisor to become idle if maxAllowedParseExceptions is violated.

The primary distinction between the existing idle state and the newly introduced `UNHEALTHY_TASKS_STOP_CREATING_NEW` state is that the former represents a healthy condition, indicating that there are no further records to process. In contrast, `UNHEALTHY_TASKS_STOP_CREATING_NEW` is an unhealthy state. It can be seen as an extension of the existing `UNHEALTHY_TASKS` state, signifying not only that all tasks have failed or are unhealthy but also that no new tasks will be created due to the errors. This state requires intervention by a user or operator to restore it to a healthy condition.

> - I am not sure if the "no progress" check is really going to be effective or if it is even desirable. There could be other reasons behind not making progress and not all of them would qualify for making the supervisor idle.

The Supervisor will transition to the new `UNHEALTHY_TASKS_STOP_CREATING_NEW` state only if three conditions are met: "no progress" AND all failed task are due to parsing exceptions AND the count of failed task exceed `TaskUnhealthinessThreshold`. Under these circumstances, we can attribute the parsing exceptions as the root cause of the Supervisor's lack of progress.

> - What if maxAllowedParseExceptions keeps getting violated for some partitions and not for others. The task launched for the former partitions would always fail but should we become idle in this case or just not launch tasks to read from the bad partitions?

In this case that means Supervisor is making progress, we won't stop Supervisor from launching new tasks. Because transitioning to the `UNHEALTHY_TASKS_STOP_CREATING_NEW` state results in a halt to new task initiation, we approach this transition with great caution to ensure it is absolutely necessary.

**Comment by suneet-s** [comment]
> The Supervisor will transition to the new UNHEALTHY_TASKS_STOP_CREATING_NEW state only if three conditions are met: "no progress" AND all failed task are due to parsing exceptions AND the count of failed task exceed TaskUnhealthinessThreshold. Under these circumstances, we can attribute the parsing exceptions as the root cause of the Supervisor's lack of progress.

Why limit this functionality just to stuck supervisors because of parse exceptions? If a supervisor is failing continuously (because of OOMs or something else) and the offsets to read from are not moving forward, it seems like stopping the supervisor and notifying the operator would be a good thing to do.

**Comment by YongGang** [comment]
> Why limit this functionality just to stuck supervisors because of parse exceptions? If a supervisor is failing continuously (because of OOMs or something else) and the offsets to read from are not moving forward, it seems like stopping the supervisor and notifying the operator would be a good thing to do.

In the case of task OOM errors occurring in the MiddleManager, the issue might stem from other processes running on the same host, which temporarily consume excessive memory. When these processes terminate—say, within 10 minutes—the memory pressure might alleviate, allowing tasks to resume normal operation. Therefore, halting task creation in response to transient or uncertain issues like OOM may not always be appropriate, as the situation might resolve itself without needing operator intervention.
In contrast, parse exceptions directly impact the Supervisor's ability to process data correctly and are not self-resolving. These issues unequivocally require operator intervention to adjust parsing logic or data format expectations. In such cases, stopping the Supervisor and notifying the operator ensures that no further tasks fail due to the same unaddressed issue, which is a necessary measure.
This approach balances responsiveness to critical, actionable issues with avoidance of unnecessary interruptions in cases where conditions may soon return to normal.

**Pull request closed without merging**
