### PR TITLE
[Backport] S3: Improvements to prefix listing (including fix for an infinite loop)

### PR DESCRIPTION
**Pull request by gianm**
Backport of #9098 to 0.17.0.

### CODE REVIEW

**Comment by jihoonson** [comment]
The CI failure looks legit:

```
[ERROR] Failures: 

[ERROR] org.apache.druid.query.aggregation.distinctcount.DistinctCountGroupByQueryTest.testGroupByWithDistinctCountAgg(org.apache.druid.query.aggregation.distinctcount.DistinctCountGroupByQueryTest)

[ERROR]   Run 1: DistinctCountGroupByQueryTest.testGroupByWithDistinctCountAgg:156 distinct-count: Expected expectedResultsIter to be exhausted, next element was ResultRow{row=[iphone, 2, 2]}

[ERROR]   Run 2: DistinctCountGroupByQueryTest.testGroupByWithDistinctCountAgg:156 distinct-count: Expected expectedResultsIter to be exhausted, next element was ResultRow{row=[iphone, 2, 2]}

[ERROR]   Run 3: DistinctCountGroupByQueryTest.testGroupByWithDistinctCountAgg:156 distinct-count: Expected expectedResultsIter to be exhausted, next element was ResultRow{row=[iphone, 2, 2]}

[ERROR]   Run 4: DistinctCountGroupByQueryTest.testGroupByWithDistinctCountAgg:156 distinct-count: Expected expectedResultsIter to be exhausted, next element was ResultRow{row=[iphone, 2, 2]}

[INFO] 

[INFO] 

[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by gianm** [comment]
Is the branch broken? It seems strange that S3 changes would cause that test to fail.

**Comment by gianm** [comment]
Actually, master is broken… I see the same failure there. It looks like a Y2020 bug.

**Comment by gianm** [comment]
https://github.com/apache/druid/pull/9120

**Comment by gianm** [comment]
I've backported #9120 to 0.17.0, merged that branch here, and re-pushed.

**Pull request merged**
