### PR TITLE
allow retention rules to be imported from other data sources

### PR DESCRIPTION
**Pull request by kroeders**
Discussion of the general problem of Increase reusability of retention rule configurations is here [Issue #10237 ](https://github.com/apache/druid/issues/10237)
This pull request implements a new rule type that imports rules from any other rule set, including rules from other data sources. 

sizecheck

### Description

This branch adds a new ImportRule type that specifies an imported rule set. Whenever rules are used, they are expanded to include the default rules for the cluster. This changes the getRulesWithDefault to also expand any import rules found at the time they are retrieved. This is functionally equivalent to the original list as the rules are replaced before evaluation. Rules are also used in CoordinatorRuleManager in the router, where getRulesWithDefault was implemented again. Here, that implementation is left at one place, in SQLRuleManager and a new method is added to RulesResource to allow CoordinatorRuleManager to retrieve the expanded list of rules without knowing how it was generated. 

In the implementation, the function of getRulesWithDefault has diverged a little bit from the name, maybe a name like getExpandedRules would be better. Also, the implementation for ImportRule is specifically in SQLMetadataRuleManager maybe it should be interface methods or in a utility class for use by other implementations in the future. 

<hr>

This PR has:
- [X] been self-reviewed.
- [X] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [X] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [X] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `SQLMetadataRuleManager`
 * `ImportRule`
 * `CoordinatorRuleManager`
 * `RulesResource`

### CODE REVIEW

**Comment by kroeders** [comment]
hi @clintropolis regarding the area, there is a web console component here, but we're suggesting a whole new rule type to support imports, so it goes beyond that

**Comment by nishantmonu51** [comment]
@kroeders : Thanks for the PR. 
The new rule simplifies rule management for clusters having many datasources, however, I believe the new concept of implicitRule can be confusing for many and opens up possibilities of unexpected behaviours.

1. This introduces dependency on the datasources which is not implied, e.g. If you add an import rule from Datasource A to Datasource B, it might be confusing for the rule change on A to affect B. 
2. If someone drops the datasource A, the effect is not clear, from the current proposal it seems it will continue to apply the same rules to other datasources, this will lead to a case there will not be any way to change the dependent rules easily from the console. 

Instead of defining an import rule, How does adding support for **RuleGroups** seem to you ?
The thought being _RuleGroups are named and simply defines a list of Ordered Rules can be applied to multiple datasources_. 
Implementation wise it would be similar and the rules will be  expanded at runtime.

**Comment by kroeders** [comment]
hi @nishantmonu51 thanks for taking a look!

 I think we're pretty much on the same page and some of these concerns are addressable at the UI layer. The current implementation for rules is basically already rule groups / rulesets, even the default rules are using a faux data source called __default and an array for the payload. It would be easy to add an "edit rules" option and restrict importable rules to exclude actual data sources. 

Is using RuleGroups effectively just introducing a one-to-many relationship between data sources and rules? From a modeling perspective, I definitely agree that is a good idea. This gives reusability, but it doesn't allow sharing as well as fine tuning.  The original use case that I ran into was having multiple defaults in a cluster, where the goal was to allow that kind of fine tuning on top of different sets of shared rules. This is where an includes/import rule came from - instead of just importing one ruleset at the end of the rules for a data source, generalize that and allow other rulesets to be imported anywhere in the execution of rules for a dataset. The nice thing about adding a new rule is that there is no change required to the schema in the database to support this. 

I thought about having some convention, similar to the default rules, that said any ruleset starting with "__" is a special ruleset that can be included in other rules and having a way to launch the editor to manage those.  I was thinking allowing or excluding importing rules from an existing datasource, rather than a special ruleset, would just be a UI level decision. It would be straightforward to add a notice in the UI to avoid confusion (e.g. Caution these rules are imported in datasource X,Y,Z etc) 

I was thinking, maybe I should start an issue talking about the general idea of increased reusability in retention rules and then reference this as one of the possible solutions?

**Comment by kroeders** [comment]
hi @nishantmonu51 I created this issue https://github.com/apache/druid/issues/10237 to discuss the problem in general, so that the problem is separated from this particular solution. I'm happy to go with any approach that works!

**Comment by kroeders** [comment]
pending design issues and conflicts need to be resolved, so I created a related issue to discuss alternative approaches and can reopen this after fixing conflicts if this solution is selected

**Pull request closed without merging**
