### PR TITLE
Use native git for git-commit-id-plugin to speed up build

### PR DESCRIPTION
**Pull request by 2bethere**
Currently, git-commit-id-plugin takes a lot of time during the build
image

git-commit-id has support for 'native git', this is a config option. After this change:
image

To use this, added a configuration option in pom file to turn on native git.

### CODE REVIEW

**Review by clintropolis — APPROVED** [review]
🚀

**Comment by suneet-s** [comment]
@2bethere how did you generate those pie charts? And what do the measurements mean?

**Comment by 2bethere** [comment]
I used https://github.com/intuit/maven-build-scanner

Original blog:
https://medium.com/@alex_collins/10x-faster-maven-builds-at-intuit-5b7bb60c65e6


The # on the pie chart is cumulative ms during the build.

**Review by suneet-s — APPROVED** [review]
+1 after CI - I restarted the last flaky test

**Pull request merged**
