### PR TITLE
add tier config in helm

### LINKED ISSUE #12249: add tier in helm chart
Currently, there is no tier setting for the historical node in the helm chart, do you have any plans to add a tier?

If you don't have a plan, I'll try adding it using range as shown below.

historical node statefulset.yaml
``` yaml
{{- range $key, $value := .Values.historical.tiers }}

historical statefulset helm chart

{{- end }}
```

values.yaml
```yaml
  tiers:
    default:
      replicaCount: 1
      env:
        druid_server_tier: xxxx
    cold:
      replicaCount: 1
      env:
        druid_server_tier: xxxx
```

### PR DESCRIPTION
**Pull request by jaegwonseo**
Fixes #12249 add tier config in helm

#### add tier config in helm chart

This PR has:
- [x] been self-reviewed.

#### deploy in k8s cluster 
tier : cold, default
스크린샷 2022-02-10 오후 6 08 13

#### checked in router ui
스크린샷 2022-02-10 오후 6 09 21

### CODE REVIEW

**Comment by jaegwonseo** [comment]
In the range scope, other variables could not be used, so i replaced them with local variables.

**Comment by jihoonson** [comment]
Hi @jaegwonseo, thank you for your contribution. I haven't reviewed your change yet, but just want to let other reviewers know that the CI failure is a known flaky test (#12171) and unrelated to this PR. I think we can ignore it.

**Comment by isandeep41** [comment]
@jaegwonseo 
changes looks great.

here are few things need to be fixed
1. [Helm chart test][1a] fails due to invalid Yaml document 
```sh
ct lint --charts helm/druid --print-config --validate-maintainers=false

==> Linting helm/druid
[ERROR] templates/historical/statefulset.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
```
2. a [new line][2a] must be added at the end of `statefulset.yaml`

[1a]: https://github.com/apache/druid/pull/12162 "enable github workflow to automate helm chart test #12162"
[2a]: https://unix.stackexchange.com/questions/18743 "What's the point in adding a new line to the end of a file?"

**Comment by jaegwonseo** [comment]
@isandeep41 
i fix lint issue, plz check it

**Pull request closed without merging**
