### PR TITLE
Update `groupId` for delta-lake and iceberg extensions

### PR DESCRIPTION
**Pull request by abhishekrb19**
This PR:
- Updates the `groupId` for both delta-lake and iceberg extensions to `org.apache.druid.extensions.contrib`; all the other contrib extensions already have this group id
- Includes both delta-lake and iceberg extensions in `extensions.md`
- Updates the codeblocks in the `extensions.md` for syntax highlighting and IDE support

This PR has:

- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
Builds are failing. Change LGTM otherwise. I think it will be helpful to also change the docs for delta and iceberg extension with instructions on how to fetch the extension. I have seen people trip over that. What do you think?

**Review by a2l007 — APPROVED** [review]
+1 after CI, thank you for fixing this!

**Comment by abhishekrb19** [comment]
> I think it will be helpful to also change the docs for delta and iceberg extension with instructions on how to fetch the extension. I have seen people trip over that. What do you think?

Good idea. I included a small section in the delta lake and iceberg docs.

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekrb19** [comment]
Merging the PR as the IT failure is unrelated:
```
[standard-its / (Compile=openjdk8, Run=openjdk8, Cluster Build On K8s) ITNestedQueryPushDownTest integration test](https://github.com/apache/druid/actions/runs/7820090484/job/21337518879?pr=15843#logs)
```

**Pull request merged**
