### PR TITLE
Set TieredStopAtLevel=1 on JDK 21.

### PR DESCRIPTION
**Pull request by gianm**
Attempting to work around #17429.

### CODE REVIEW

**Comment by gianm** [comment]
There's some error in `DecoupledPlanningCalciteNestedDataQueryTest.testReturningAndSumPathDouble` ending in this chain. The root exception is `VirtualMachineError: Out of space in CodeCache for method handle intrinsic`:

```
Caused by: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandle.linkToSpecial(Object,Object,Object,Object,Object,Object,Object,int,Object,MemberName)void/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
	at java.base/java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:261)
	... 112 more
Caused by: java.lang.NoSuchMethodError: 'void java.lang.invoke.MethodHandle.linkToSpecial(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, java.lang.Object, java.lang.invoke.MemberName)'
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
	... 113 more
Caused by: java.lang.VirtualMachineError: Out of space in CodeCache for method handle intrinsic
	... 116 more
```

After that, there's a ton of StupidPool errors due to leaks being detected. There must be some cleanup code somewhere that catches `Exception` rather than `Throwable`, so this `Error` causes a leak. The `VirtualMachineError` is the real problem though.

**Comment by gianm** [comment]
I've attempted to work around the above problem by setting `-XX:ReservedCodeCacheSize=512m`

**Review by kgyrtkirk — APPROVED** [review]
I've tried the same steps I was able to repro the issue earlier and it didn't happened
some tests were 2/3 times slower...but that's kinda expected
overall: instead of 3:55 it took 11:36 to run the same set of tests
+1

**Comment by gianm** [comment]
Now a quidem test is failing with:

```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 884
```

Maybe JDK 21 is too buggy 😛

**Comment by gianm** [comment]
Closing, this doesn't seem like the right path.

**Pull request closed without merging**
