### PR TITLE
Cleanup logic from handoff API

### PR DESCRIPTION
**Pull request by georgew5656**
Some followup fixes from: https://github.com/apache/druid/pull/16310#pullrequestreview-2056935898

### Description
Making a few nit fixes from the PR in https://github.com/apache/druid/pull/16310#pullrequestreview-2056935898 for the handoff API

##### Key changed/added classes in this PR
 * `Supervisor`
 * `SeekableStreamSupervisor`

This PR has:

- [X] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by kfaraz — APPROVED** [review]
Thanks for the changes, @georgew5656 .

**Comment by georgew5656** [comment]
the cds-task-schema-publish-disabled test appears to be hanging and is not cancelling for some reason. i'm pretty sure this is unrelated so i'm going to merge

**Comment by gianm** [comment]
> the cds-task-schema-publish-disabled test appears to be hanging and is not cancelling for some reason. i'm pretty sure this is unrelated so i'm going to merge

I've seen this happen on various PRs after master has been merged into the PR branches. It didn't happen on #16250, the PR that was merged to master immediately before this one. That suggests that possibly this patch did something to make the `cds-task-schema-publish-disabled` group take longer to run? It used to complete in ~1.5hrs, now it's running for 6h and then getting canceled.

**Comment by gianm** [comment]
Looking through the patch, though, I don't see anything that seems like it would have that effect…

**Comment by gianm** [comment]
Nevermind, #16250 didn't run the ITs since it was a console only change. I don't think this patch is the one to blame.

**Pull request merged**
