### PR TITLE
Refactoring org.apache.druid.segment.loading

### LINKED ISSUE #15164: Refactoring the Duplicated/Redundant Mock Objects in test of org.apache.druid.segment.loading;
Hi Druid developers, 

I noticed that the dependency `DataSegment` was repeatedly mocked a total of 12 times in three different test suites.

There are a total of two mock behaviors of mocking `DataSegment`.

The code for the first behavior is as follows:
```java
DataSegment segment = mock(DataSegment.class);
when(segment.getLoadSpec()).thenReturn(ImmutableMap.of("type", "sane"));
```
It has been repeated 8 times with completely identical logic in the 3 test classes:

- In class [OmniDataSegmentMoverTest.java](https://github.com/apache/druid/blob/master/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentMoverTest.java), there were 3 identical duplicate creations in 3 test cases.
- In class [OmniDataSegmentArchiverTest.java](https://github.com/apache/druid/blob/master/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentArchiverTest.java), there were 3 identical duplicate creations in 3 test cases.
- In class [OmniDataSegmentKillerTest.java](https://github.com/apache/druid/blob/master/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java), there were 2 identical duplicate creations in 2 test cases.

Example code for another behavior is as follows:
```java
DataSegment segment = mock(DataSegment.class);
when(segment.getLoadSpec()).thenReturn(ImmutableMap.of("type", "sane"));
when(segment.isTombstone()).thenReturn(false);//one more stub method over the first behavior.
```

Compared to the first behavior. It stubs an extra `isTombstone()` method. It has been repeated 4 times with completely identical logic in 2 test cases of [OmniDataSegmentKillerTest.java](https://github.com/apache/druid/blob/master/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java).

We can create a [CreateMockDataSegment](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/CreateMockDataSegment.java) class to eliminate duplicates.
The code snippet of `CreateMockTungstenAnswer`:
```java
public class CreateMockDataSegment {
    //Attribute is for reuse mock creation.
    private DataSegment segment;
    //Implement the first behavior of mock creation.
    CreateMockDataSegment(String key, String value) {
        segment = mock(DataSegment.class);
        when(segment.getLoadSpec()).thenReturn(ImmutableMap.of(key, value));
    }
    //Implement the second behavior of mock creation.
    CreateMockDataSegment(String key, String value, boolean isTombstone) {
        segment=new CreateMockDataSegment(key, value).getSegment();//Reuse the first creation behavior.
        when(segment.isTombstone()).thenReturn(isTombstone);
    }  
    public DataSegment getSegment() {return segment;}
}
```

When we need to reuse the first mock creation.Just call this class with two parameters to complete the mock creation. It is as follows:
```java
final DataSegment segment = new CreateMockDataSegment("type", "sane").getSegment();
```
Similarly, when we need to reuse the second mock creation behavior. Just call this class with three parameters to complete the mock creation. It is as follows:
```java
final DataSegment segment = new CreateMockDataSegment("type", "sane", false).getSegment();
```

To be more intuitive, the following shows the comparison of how a test case looks before and after the refactoring, with the code snippet of `testKillMultipleSegmentsWithType()` in test suit `OmniDataSegmentKillerTest.java` as an example:

Code [before refactoring](https://github.com/apache/druid/blob/master/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java#L142C1-L165C4):

```java
@Test
public void testKillMultipleSegmentsWithType() throws SegmentLoadingException{
    // The code before this comment is the same
    final DataSegment segment1 = Mockito.mock(DataSegment.class);
    final DataSegment segment2 = Mockito.mock(DataSegment.class);
    final DataSegment segment3 = Mockito.mock(DataSegment.class);

    Mockito.when(segment1.isTombstone()).thenReturn(false);
    Mockito.when(segment1.getLoadSpec()).thenReturn(ImmutableMap.of("type", "sane"));

    Mockito.when(segment2.isTombstone()).thenReturn(false);
    Mockito.when(segment2.getLoadSpec()).thenReturn(ImmutableMap.of("type", "sane"));

    Mockito.when(segment3.isTombstone()).thenReturn(false);
    Mockito.when(segment3.getLoadSpec()).thenReturn(ImmutableMap.of("type", "sane_2"));    
    //The rest of the sentence is exactly the same before and after the refactoring.
}
```
Code [after refactoring](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java#L138C1-L154C4):
```java
@Test
public void testKillMultipleSegmentsWithType() throws SegmentLoadingException{
    // The code before this comment is the same
    final DataSegment segment1 = new CreateMockDataSegment("type", "sane", false).getSegment();
    final DataSegment segment2 = new CreateMockDataSegment("type", "sane", false).getSegment();
    final DataSegment segment3 = new CreateMockDataSegment("type", "sane_2", false).getSegment();
    //The rest of the sentence is exactly the same before and after the refactoring.
}
```
We've applied a similar refactoring approach to three test suites, [OmniDataSegmentMoverTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentMoverTest.java), [OmniDataSegmentArchiverTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentArchiverTest.java) and [OmniDataSegmentKillerTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java). As a result, we can reduce 16 lines of code.

**With refactoring, if the `DataSegment` mock creation needs to be modified in the future, the developer only needs to modify one time in `CreateMockDataSegment` instead of 12 places of duplicate mock creation in 3 test classes.**

#### Benefits of the Proposed Refactoring:
- **Modularity:** The code is now more modular with a specific class for creating mock objects.
- **Readability:** Test cases are more readable, focusing on specific test logic rather than the setup code.
- **Maintainability:** Easier maintenance due to the reduction of redundancy and a cleaner, more structured codebase.
- **Scalability:** Facilitates the addition of new test cases and makes modifications to existing ones more efficient.

 I'd love to hear your thoughts on this proposal! Do you agree with any of these changes, or do you have other insights or preferences?

### PR DESCRIPTION
**Pull request by gzhao9**
### Description

This PR addresses Issue #15164 of the `DataSegment` dependency being repeatedly mocked across three different test suites. It introduces a `CreateMockDataSegment` class to eliminate this redundancy, enhancing the maintainability and extensibility of the code.

And also Implemented a similar refactoring approach as described in issue #15164. Introduced a helper method `CreateMockTaskActionToolbox` to reuse the creation of `TaskActionToolbox` mocks. This reduces code redundancy and improves test readability.

#### Introduced the `CreateMockDataSegment` Class

A new class named [CreateMockDataSegment](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/CreateMockDataSegment.java) has been created to centralize the mocking of `DataSegment`, reducing code duplication and improving maintainability.

#### Optimized Test Suite Code

This refactoring approach has been applied to three test suites: [OmniDataSegmentMoverTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentMoverTest.java), [OmniDataSegmentArchiverTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentArchiverTest.java), and [OmniDataSegmentKillerTest.java](https://github.com/gzhao9/druid/blob/Refactoring-org.apache.druid.segment.loading/server/src/test/java/org/apache/druid/segment/loading/OmniDataSegmentKillerTest.java).
<hr>

##### Key changed/added classes in this PR
 * `CreateMockTaskActionToolbox` method in `UpdateStatusActionTest.java`

<hr>

This PR has:

- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] included a release note in the PR description.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [] been tested in a test Druid cluster.

Please note, the above is a sample filled out using the information from your provided issue. You may need to adjust it according to the actual content of your PR.

### CODE REVIEW

**Comment by gzhao9** [comment]
@cryptoe Thank you very much for your reply in Issue. I have merged both PRs, #15187 and #15217 into this current PR.

**Comment by cryptoe** [comment]
@gzhao9 Please take a look into the conflicts.

**Comment by gzhao9** [comment]
> @gzhao9 Please take a look into the conflicts.

Thanks for the reminder, I've resolved the conflict.

**Review by kfaraz — CHANGES_REQUESTED** [review]
Thanks for trying to improve the tests, @gzhao9 !

`DataSegment` is a simple POJO Druid class which should not be mocked. Any test doing this should instead be updated to use concrete `DataSegment` objects. You can either use a `DataSegment.Builder` or the `CreateDataSegment` utility to easily create `DataSegment` objects in test.

Also, this is a change that doesn't affect Druid users in any way, so it doesn't need a release note.

**Comment by gzhao9** [comment]
> Thanks for trying to improve the tests, @gzhao9 !
> 
> `DataSegment` is a simple POJO Druid class which should not be mocked. Any test doing this should instead be updated to use concrete `DataSegment` objects. You can either use a `DataSegment.Builder` or the `CreateDataSegment` utility to easily create `DataSegment` objects in test.
> 
> Also, this is a change that doesn't affect Druid users in any way, so it doesn't need a release note.

Hi, sorry for the delayed response. I have removed the changes regarding the `DataSegment` section. Because this PR is mainly trying to reduce mock cloning in tests.

In the meantime, I submitted another PR that also tries to reduce mock cloning in tests. See the detail in #15980 If you are interested please take a look as well. @kfaraz @cryptoe

**Comment by kfaraz** [comment]
My feedback on this PR is the same as #15980 . I don't feel that these changes are necessary as they don't add any value except reducing a couple of lines and compromise the readability of the tests.

**Pull request closed without merging**
