### PR TITLE
Add context dimension to DefaultQueryMetrics

### LINKED ISSUE #10577: Query Context should be included as a dimension in Query metrics by default
### Description

Druid Metrics for queries should include the context dimension by default. It is added for many of them, but one notable omission is `query/cpu/time`. I think this metric is very useful to gain information about each metric. At my org we extract context information and add them as native dims to a metrics datasource in druid and it is very useful.

### Motivation

Please provide the following for the desired feature or change:
- It is super useful to be able to correlate query metrics with the context. Being able to know if caching is explicitly configured, or vectorization. or in the case of some people, if custom query context information is included too. It just makes sense to me to have this dimension by default for query metrics.

### PR DESCRIPTION
**Pull request by capistrant**
Fixes #10577 .

### Release Notes

`context` is now a default dimension emitted for all query metrics. `context` is a `json` formatted string containing the query context that is tied to the query that the emitted metric refers to. This will alter some of the metrics that are emitted by Druid (adding a dimension that was not previously there). Clients should plan to handle this new `context` dimension in their metrics pipeline. Since the dimension is a `json` formatted string, it is common for clients to parse the dimension and either flatten it or extract the bits they want and discard the full `json` formatted string blob.

### Description

Makes the context dimension a default dimension for DruidQueryMetrics. This will allow clients to gain more informations about the queries producing the metrics.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `DefaultQueryMetrics`

### CODE REVIEW

**Review by nishantmonu51 — APPROVED** [review]
👍 LGTM, 
NIT: since we moved it to default now, 
Can we now remove the context addition in DruidMetrics.makeRequestMetrics ?

**Review by jihoonson — APPROVED** [review]
This PR LGTM, but should be called out in the release notes because it can impact on the user metrics store. Also please address https://github.com/apache/druid/pull/10578#pullrequestreview-532612135.

**Comment by capistrant** [comment]
@nishantmonu51 @jihoonson thank you for the review. I addressed the redundant call to `context()` in latest commit and added a release notes blurb in the PR description.

**Comment by capistrant** [comment]
Hmm, I appear to be having an inspection problem after my `00efa42` commit. `QueryMetrics#context` is getting flagged with `Method is never used as a member of this interface, but only as a member of the implementation class(es). The project will stay compilable if the method is removed from the interface.` ... However, I do not see the difference between this method or any of the other override methods that don't have an inspection error. I'll keep digging, if anyone has some tips, let me know.

**Review by jihoonson — APPROVED** [review]
@capistrant thanks! :+1:

**Comment by jihoonson** [comment]
@capistrant thanks for the detailed PR description :+1:

**Pull request merged**
