### PR TITLE
MSQ extension: Fix over-capacity write in ScanQueryFrameProcessor.

### PR DESCRIPTION
**Pull request by gianm**
Frame processors are meant to write only one output frame per cycle. The ScanQueryFrameProcessor would write two when reading from a channel if the input frame cursor cycled and then the output frame filled up while reading from the next frame.

This patch fixes the bug, and adds a test. It also makes some adjustments to the processor code in order to make it easier to test.

### CODE REVIEW

**Comment by gianm** [comment]
This part is the fix: https://github.com/apache/druid/pull/13036/files#diff-9b472caafa614f6c7b93fc27e09e8192b1bd6b665857ed0e5946f73035ac633cL206-R207

The rest is refactoring to make it possible to write the test.

**Review by cryptoe — APPROVED** [review]
LGTM. 
It would be cool to understand how you debugged this also.

**Review by vogievetsky — APPROVED** [review]
I saw Gian write the fix :-)

**Comment by gianm** [comment]
> It would be cool to understand how you debugged this also.

I ran into an error "Channel has no capacity" from BlockingQueueFrameChannel in a test cluster. The stack trace indicated it was a frame write from ScanQueryFrameProcessor `populateFrameWriterAndFlushIfNeeded`. Knowing that this error means that a processor wrote two frames in a single cycle, I read through the code and thought about ways that this might happen. I found this one, and wrote a test case & fix for it.

**Pull request merged**
