### PR TITLE
Add interval time check

### LINKED ISSUE #16945: Check interval range to avoid cases where year is inappropriately entered
### Description

In Apache Druid, we need to support a new feature that can check the interval range to avoid cases where the year is inappropriately entered.

Specifically, when dealing with time data, there are instances where incorrect years are entered due to typos or other reasons. For example, entering the year as 20240 instead of 2024. These incorrect years can lead to significant deviations in data processing and analysis results, affecting the accuracy and reliability of the data.

To avoid such situations, we plan to add an interval range check feature in Apache Druid. This feature will allow users to set a reasonable range for years, such as from the year 2000 to 2100. During data input and processing, the system will automatically check whether the year falls within this range. If a year outside this range is detected, the system will issue a warning or error message, prompting the user to make corrections.

The implementation of this new feature will include the following steps:

1. **Define a reasonable year range**: Users can set a reasonable year range through configuration files or the interface.
2. **Data input check**: During the data input phase, the system will check whether the year of each data entry falls within the set range.
3. **Data processing check**: During the data processing phase, the system will also perform year checks to ensure that all processing data years are within the reasonable range.
4. **Error handling and notification**: If a year outside the range is detected, the system will log the error and issue a warning or error message to the user.

By introducing this interval range check feature, we can effectively avoid data issues caused by incorrect year entries, enhancing the accuracy and reliability of data processing. This will provide users with higher quality data analysis services, ensuring that their decisions are based on accurate and error-free data.

### PR DESCRIPTION
**Pull request by GWphua**
Fixes #16945

#### Add interval check functionality
- System will throw IAE if check is enabled, and the user-defined rules are violated.
- Default: Time check functionality set to false. (Do not want systems to break all of a sudden if they actually want years like "20240").
- Can enable functionality, and set start and end time with JSON input: `safeInput` (boolean), `safeStart` (string), `safeEnd` (string) respectively.
- Documented changes in `ingestion-spec.md`.
- Update `equals` and `hashcode` function, adhering to rule that objects that are equal must have the same hashcode.

#### Unit test changes
- Renamed test class allows easy navigation between to and from implementation classes with (Cmd Shift T) in IntelliJ.
- Added unit tests for new functionalities.

#### Release note

<hr>

Add functionality to check your ingestion intervals, giving early reporting to erroneous time intervals during ingestion.

<hr>

This PR has:

- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by GWphua** [comment]
Bump @kfaraz 😄

**Review by kfaraz — CHANGES_REQUESTED** [review]
Thanks for the changes, @GWphua !
I don't think touching `GranularitySpec` for this requirement is the correct approach.

Also, I am not sure if the change is even needed. We already support validation of intervals:
- Streaming supervisors have `lateMessageRejectionPeriod` and `earlyMessageRejectionPeriod`.
   Docs: https://druid.apache.org/docs/latest/ingestion/supervisor#io-configuration
- MSQ queries can declare a range of `__time` in the WHERE clause
- Batch specs can define filters on the `__time` column.
   Docs: https://druid.apache.org/docs/latest/querying/filters/#filtering-on-the-timestamp-column

Do you want to raise an alert when an out-of-range record is encountered or just filter out such records?

**Comment by GWphua** [comment]
Thanks for the review @kfaraz,

From the raised issue, it seems that there are cases where year of data is incorrectly labelled. I chose to make the system throw an error when facing an out-of-range data to notify the user.

Noted on the support of validation. If such capabilities are already supported in Druid, I can offer to close this PR 😄

**Comment by GWphua** [comment]
Reopen pull request based on the explanation in the relevant Issue.

**Comment by kfaraz** [comment]
> Assuming we create the tasks today (12 Sep 2024). Based on my understanding, if payloads are misconfigured with 20240, they will be initialized with the following:

2024-06-11/20240-06-12 // 9200G
2024-06-12/20240-06-13 // 9100G
...
2024-09-11/20240-09-12 // 100G

@GWphua , I am not sure if this is actually the case in the current code. Could you please share the logs of the ingestion that you tried where you encountered this?

**Pull request closed without merging**
