### PR TITLE
Adding the missing sqlQueryContext api

### LINKED ISSUE #10367: Add missing sqlQueryContext API
### Description

This is a minor change. DefaultRequestLogEvent is missing an api to query the sqlQueryContext

### Motivation

Exposing this api is useful for audit logging purposes. For each sql query, Druid runs an equivalent native query. The query context datastructure maintains the mapping between sqlQueryId (which represents the sql query) to queryId (which represents the native query).

### PR DESCRIPTION
**Pull request by mghosh4**
Fixes #10367.

### Description

Adding the missing sqlQueryContext api

<hr>

This PR has:
- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @mghosh4, the code change looks good to me, but I think it would be nice to have some test for this class. Would you mind adding one which verifies JSON-serialization? We don't currently have any tests for `DefaultRequestLogEvent`, so you may want to add one.

**Comment by jihoonson** [comment]
BTW, I tagged "Release Notes" and "Design Review" since this PR modifies a Public API.

**Comment by mghosh4** [comment]
> Hi @mghosh4, the code change looks good to me, but I think it would be nice to have some test for this class. Would you mind adding one which verifies JSON-serialization? We don't currently have any tests for `DefaultRequestLogEvent`, so you may want to add one.

Added the test

**Review by jihoonson — APPROVED** [review]
@mghosh4 thank you for adding a test! LGTM

**Review by clintropolis — APPROVED** [review]

**Pull request merged**
