### PR TITLE
W deser always

### PR DESCRIPTION
**Pull request by kgyrtkirk**
Fixes #XXXX.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by somu-imply — COMMENTED** [review]
Can you please add some description around what this PR is solving ?

**Comment by kgyrtkirk** [comment]
I just wanted to see if any tests fail if a conditional is altered in relation with [this comment](https://github.com/apache/druid/pull/15465#discussion_r1424142987)

sorry @somu-imply  for the noise; I wanted to open a PR against my own repo to just get a glimpse if any tests are failing.

**Comment by kgyrtkirk** [comment]
let me just close this

**Comment by somu-imply** [comment]
No problem! Thanks for clarifying. In such a case what I do is to put a [Do not Merge] as the PR title.

**Pull request closed without merging**
