### PR TITLE
Fix infinite iteration in http sync monitoring

### PR DESCRIPTION
**Pull request by AmatyaAvadhanula**
Fixes infinite iteration during sync monitoring when httpRemote task runner is used.

### Description

An iterator was used over a ConcurrentHashMap and items were being added and removed during the iteration. This led to an infinite loop of worker sync causing the Overlord to become unresponsive
This patch iterates over a copy instead.

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by clintropolis — APPROVED** [review]
sneaky :+1:

**Comment by AmatyaAvadhanula** [comment]
@clintropolis Thank you for the review. Could you please look at a similar fix made in HttpServerInventoryView?

**Comment by abhishekagarwal87** [comment]
LGTM. but there are no tests for this? can we add those?

**Comment by AmatyaAvadhanula** [comment]
@abhishekagarwal87 I've added tests.
Merging since the failures are due to code coverage

**Review by kfaraz — APPROVED** [review]

**Pull request merged**
