### PR TITLE
ui: fixes missing columns during Transform step

### PR DESCRIPTION
**Pull request by egor-ryashin**
### Description

Fixes missing columns with float type data during the Transform step in Druid UI.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by vogievetsky** [comment]
The changes you are suggesting looks good: use `double` instead of `float` and fix a typo in a function name but how does that address "fixes missing columns during Transform step"? what missing columns?

**Comment by clintropolis** [comment]
>The changes you are suggesting looks good: use double instead of float and fix a typo in a function name but how does that address "fixes missing columns during Transform step"? what missing columns?

I think the change is to match the case statement here: https://github.com/apache/druid/blob/02c1beb6ab43896744c02ff38bae124c6551f404/web-console/src/utils/druid-type.ts#L71

which calls the changed method, but 'float' matches nothing so would be lost. Technically there are both float and a double sum aggs, but I'm not sure how you would distinguish between which to use so using 'double' is probably better.

**Comment by vogievetsky** [comment]
Or right! Thanks for the clarity @clintropolis ! @egor-ryashin could you please add a

```
      case 'float':
          return { name: `sum_${h}`, type: 'floatSum', fieldName: h };
```

to the `switch` that Clint linked?

**Comment by clintropolis** [comment]
>Or right! Thanks for the clarity @clintropolis ! @egor-ryashin could you please add a ...

Since this PR fixes a bug I'm going to go ahead and merge it, this change can be done in a follow-up.

**Pull request merged**
