### PR TITLE
Stop altering the query timeout in ScanQueryEngine

### PR DESCRIPTION
**Pull request by machine424**
Fixes https://github.com/apache/druid/issues/12197.

### Description

See https://github.com/apache/druid/issues/12197#issuecomment-1025143613 for details.

I'll squash the commits later, it's just to let you check that the current code fails on the added test.

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by kfaraz** [comment]
Thanks for the changes, @machine424 .
Not sure why this was put here in the first place.
But please note that even the original code was not altering the timeout (because the `timeoutAt` is a final field). It was only altering the timeout value inside the `ResponseContext` object.

+1 after CI passes.

**Comment by kfaraz** [comment]
Since the `timeoutAt` is not being altered, I don't think this will fix #12197

**Comment by machine424** [comment]
Hi @kfaraz, 

Thanks for your response.

I maybe misspoke, but we retrieve the timeout from the response context here:

https://github.com/apache/druid/blob/3f709db173d779db1466e57a1564a5f557b4b0cf/processing/src/main/java/org/apache/druid/query/scan/ScanQueryEngine.java#L75

we check it here:

https://github.com/apache/druid/blob/3f709db173d779db1466e57a1564a5f557b4b0cf/processing/src/main/java/org/apache/druid/query/scan/ScanQueryEngine.java#L174-L176

And we alter it (in the response context) here:

https://github.com/apache/druid/blob/3f709db173d779db1466e57a1564a5f557b4b0cf/processing/src/main/java/org/apache/druid/query/scan/ScanQueryEngine.java#L188-L192

(Of course the compiler wouldn't have appreciated altering an immutable field ^^)

And I did test the changes, as I said in https://github.com/apache/druid/issues/12197#issuecomment-1025143613:

> ...After commenting out Lines 190 to 194, the query's timeout (As I understand it) seems to be respected. Of course it's always possible to exceed it (while in rowsToList for example if the batchSize is big) but this is another subject which is discussed in https://github.com/apache/druid/issues/1415.

**Comment by kfaraz** [comment]
Thanks for the clarification, @machine424 .
Sorry, but I am still confused how this would fix #12197 .

If it does indeed fix the root cause as you verified, please add a unit test which asserts the same, i.e. a query which times out correctly after the changes.

**Comment by machine424** [comment]
I thin this prevents shortening the timeout in `responseContext` and thus timing out early.

I've added a check in a unit test to make sure we don't alter the timeout. I could add more tests later, when I have time.

But now I need someone to confirm I'm on the right track, maybe we could ask review from someone who is familiar with this part of the code.

**Comment by machine424** [comment]
@jihoonson maybe?

**Review by gianm — COMMENTED** [review]
The change looks good to me. I'm not sure why the current code is doing what it's doing. It would make sense if it was adjusting a timeout duration, but there's no reason to adjust a timeout-at instant.

Please remove this no-longer-accurate comment at `ResponseContext#TIMEOUT_AT`:

```
     * Continuously updated by {@link org.apache.druid.query.scan.ScanQueryEngine}
     * by reducing its value on the time of every scan iteration.
```

With that change 👍 on the patch.

**Comment by machine424** [comment]
Thanks @gianm for your review, done. I also squashed.

Yep, maybe the original logic has changed but not everywhere in the code (didn't dig in the history too much).

There is another timeout `QUERY_FAIL_TIME` that is redefined from the same timeout query attribute I think.
https://github.com/apache/druid/blob/0fd4f1e3863f8f33bec69fc77dcb1ea118a42ed4/server/src/main/java/org/apache/druid/server/SetAndVerifyContextQueryRunner.java#L69-L73
I'll see if we can just use `ResponseContext.Key.TIMEOUT_AT`.


I know you're all busy and that 3 months is not that much (I've a MR that has been hanging for 15 months on another repo :)) but how could we give these fix PR more exposure? (I've tried slack and the mailing list in vain, but I think you saw my last message on slack),

**Comment by gianm** [comment]
> Thanks @gianm for your review, done. I also squashed.

Thanks!

> I'll see if we can just use ResponseContext.Key.TIMEOUT_AT.

We wouldn't use it there, since TIMEOUT_AT is a Scan query thing. 

> I know you're all busy and that 3 months is not that much (I've a MR that has been hanging for 15 months on another repo :)) but how could we give these fix PR more exposure? (I've tried slack and the mailing list in vain, but I think you saw my last message on slack),

Excellent question. It's up to the community collectively to review and merge patches in a timely manner. Of course only committers can merge patches, but anyone can review, and that does help. In fact reviewing the work of others is one way to earn the merit needed to become a committer.

I don't recognize your github handle, but if you're not already a committer & you're interested in getting more involved then keep at it and become part of the solution 😀

**Comment by machine424** [comment]
> We wouldn't use it there, since TIMEOUT_AT is a Scan query thing.

I meant we define two timeouts in the code from same `timeout` query attribute. Maybe there is some refactoring to be done.

> Excellent question. It's up to the community collectively to review and merge patches in a timely manner. Of course only committers can merge patches, but anyone can review, and that does help. In fact reviewing the work of others is one way to earn the merit needed to become a committer.

>I don't recognize your github handle, but if you're not already a committer & you're interested in getting more involved then keep at it and become part of the solution 😀

Thanks, I don't have much time  for now for reviewing, but I'll not skimp on patches if needed.

**Pull request merged**
