### PR TITLE
remove ListenableFutures and revert to using the Guava implementation

### PR DESCRIPTION
**Pull request by xvrl**
This change removes ListenableFutures.transformAsync in favor of the
existing Guava Futures.transform implementation. Our own implementation
had a bug which did not fail the future if the applied function threw an
exception, resulting in the future never completing.

An attempt was made to fix this bug, however when running againts Guava's own
tests, our version failed another half dozen tests, so it was decided to not
continue down that path and scrap our own implementation.

Explanation for how was this bug manifested itself:

An exception thrown in BaseAppenderatorDriver.publishInBackground when
invoked via transformAsync in StreamAppenderatorDriver.publish will
cause the resulting future to never complete.

This explains why when encountering #9845
the task will never complete, forever waiting for the publishFuture to
register the handoff. As a result, the corresponding "Error while
publishing segments ..." message only gets logged once the index task
times out and is forcefully shutdown when the future is force-cancelled
by the executor.

### CODE REVIEW

**Comment by xvrl** [comment]
CI is failing this for lack of code coverage for the affected line :/

**Comment by clintropolis** [comment]
>CI is failing this for lack of code coverage for the affected line :/

Yeah, was just looking at that. I don't think the solution is to copy the tests from guava, but I don't really know what else to do other than disable this check which I'm not entirely sure how to do or if is the right solution either.

While knowing coverage is useful for the reviewer, I am not really a fan of it being a requirement for a PR to pass CI after seeing it in practice for a few days, since it just enforces raw numbers blindly.

**Comment by xvrl** [comment]
ok, unless people feel strongly about adding a test for this, I'm going to merge this then.

**Comment by gianm** [comment]
> ok, unless people feel strongly about adding a test for this, I'm going to merge this then.

IMO it'd be good to copy the tests too from Guava (if they would cover this), because if we decide to change this later, it'd be good to have the tests. Also, it'd help us validate future JDK upgrades etc.

**Comment by jihoonson** [comment]
Hmm, I'm confused. The javadoc says ["This is NOT copied from guava"](https://github.com/apache/druid/blob/master/core/src/main/java/org/apache/druid/java/util/common/concurrent/ListenableFutures.java#L37). 

No matter whether it was copied or not, I think it would be nice to have some test but only for the change made in this PR. I approved this PR before since there is no test for this method now and so we may be able to add necessary tests at once later. But I agree it would be nice if the test can be in this PR.

**Comment by jihoonson** [comment]
Let me make clear my stance here. I don't have a strong opinion here and am fine with either adding some tests in this PR or doing it as a follow-up. If it's the follow-up, it would be nice to add all missing tests for this method in it.

**Comment by xvrl** [comment]
@jihoonson @gianm I looked into porting the applicable Guava tests to validate our implementation, and it turns out we're failing over half of the dozen tests.
I was able to fix a few more issues to get it down to 3 failing tests, but the work involved to fix the remaining ones might be more involved.
At this point I am inclined to say we should probably revert back to using the Guava implementation, rather than trying our luck with the home-grown one.

**Comment by jihoonson** [comment]
@xvrl that sounds good to me.

**Comment by xvrl** [comment]
I've updated this PR to revert back to Guava's Futures.transform. The new title/description reflect the code. If anyone is curious about my previous attempt to run Guava's tests, you can find the code here https://github.com/apache/druid/compare/master...xvrl:listenable-futures-tests?expand=1

**Pull request merged**
