### PR TITLE
Add support for REGEXP_REPLACE

### PR DESCRIPTION
**Pull request by suneet-s**
### Description

This function is similar to `regexp_replace` functions offered by other databases like
postgres and oracle.

This function unlocks a few use-cases

* Name rearrangement

If a column stores the name as first last, but you would prefer the report
to be displayed as last, first

`SELECT REGEXP_REPLACE('John Doe','(.*) (.*)','$2, $1');`

* String removal

If you'd prefer to replace a string that matches a pattern - for example
email addresses that might be in a text column, you can replace the pattern
with generic text so that queries don't accidentally leak data.

`SELECT DISTINCT REGEXP_REPLACE(diffUrl, 'diff=\d*', 'diff=****'`) from wikipedia`

This PR has:
- [ ] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by suneet-s** [comment]
Marked as WIP since it has insufficient tests

**Comment by suneet-s** [comment]
not stale... new PR coming this month 🤞

**Comment by suneet-s** [comment]
one more time please stalebot 🙏

**Comment by gianm** [comment]
> one more time please stalebot 🙏

two more times? 🙂

**Comment by hosswald** [comment]
Just want to say that I'm really looking forward to this being eventually merged and thank @suneet-s for implementing it.

**Pull request closed without merging**
