### PR TITLE
Upgrade parquet-mr version

### PR DESCRIPTION
**Pull request by a2l007**
Upgrades parquet-mr dependency version to 1.13.0. The release notes for the version can be found [here](https://github.com/apache/parquet-mr/blob/master/CHANGES.md).

This PR has:

- [x] been self-reviewed.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
@a2l007 - can you look into CI failures. LGTM once those are addressed.

**Comment by abhishekagarwal87** [comment]
Hmm. will this upgrade break Hadoop 2? If so, we cannot make the change till we get rid of Hadoop 2 entirely.

**Comment by a2l007** [comment]
@abhishekagarwal87 I have a discussion with the parquet folks going on here: https://issues.apache.org/jira/browse/PARQUET-2276
They've unintentionally broke compatibility with hadoop 2.8 with their latest version and it seems from their responses the lowest hadoop version they will support is 2.9. I'll need to test out the latest parquet dependency with hadoop 2.9 and evaluate if it is worth making this temporary move to hadoop 2.9 for Druid before our long term migration over to 3.x.
Another option for us would be to stay put at parquet version 1.12.0. One drawback of this would be that we wouldn't be able to take full advantage of [Parquet Modular Encryption](https://github.com/apache/parquet-format/blob/master/Encryption.md), but I don't know if other druid users care about that feature at the moment.

**Comment by abhishekagarwal87** [comment]
@a2l007 - thanks for sharing the context. one way to make this work is to have different parquet-mr version for different hadoop profiles. So parquet-mr can be 1.13.0 on Hadoop 3 and 1.12.0 on Hadoop 2. We have pom profiles for different hadoop versions.

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by a2l007** [comment]
@abhishekagarwal87 Thanks for the review!

**Pull request merged**
