### PR TITLE
Auth v2 Model

### LINKED ISSUE #9380: Fine grained config and state resources
### Motivation

This proposal is to introduce fine grained config and state resources for better access controls. For example, for a user we may want to allow them the permission to view the status of a node but do not want to allow by default access to all other state resources like load queue, list of servers or list of tasks for a worker etc. Another example, we may want to give permissions to a user to just query the datasources but not read/change any state or config of the cluster, however even for showing the datasource list on console, a read on config is required to fetch compaction status for the datasource.

### Proposed changes

The current design has the same resource name for all `STATE` and `CONFIG` resources which are _state_ and _config_ respectively. To achieve the desired results, different resource names will need to be set for these resources. For example, for `druid/coordinator/v1/config/compaction` the resource name can be _COMPACTION_ and resource type is _CONFIG_ so a `GET` on this endpoint will be a `READ on COMPACTION CONFIG` instead of `READ on CONFIG CONFIG`. Similarly appropriate names will be chosen for resources. The design always had this provision for future improvement, see [here](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/server/http/security/ConfigResourceFilter.java#L38) and  [here](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/server/http/security/StateResourceFilter.java).

- `StateResourceFilter` and `ConfigResourceFilter` will be changed to introspect the requested url and set the resource name accordingly before performing authorization. 
- Endpoints that do authorization in the method itself will be changed to set the resource names appropriately before authorizing.

### Rationale

Having fine grained access controls. 

### Operational impact

If the security extension uses _state_ and _config_ as resource name for `STATE` and `CONFIG` resource types for auth checks then they would need to change the implementation to allow any name as valid and just check the resource type to preserve the old behaviour.

### Backwards Compatibility 
Its backward compatible as long as exact resource name match is not done for `CONFIG` and `STATE` resource types in the security extension.

### PR DESCRIPTION
**Pull request by pjain1**
Fixes #9380.

### Description
This PR changes the auth model to support user personas like admin, viewer etc. in an easy manner. Details about new Resource types, names and the endpoints that they protect can be found on [auth-model.md](https://github.com/apache/druid/blob/3489957683a54590c823fc66aa9ac682ead852a5/docs/design/auth-model.md#auth-v2-model) page.

All the changes are backwards compatible and support rolling update, details can be found on [auth-model.md](https://github.com/apache/druid/blob/3489957683a54590c823fc66aa9ac682ead852a5/docs/design/auth-model.md#auth-v2-model) page.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `*Resource` classes
 * `*ResourceFilter*` classes
* `Authorizer` class

### CODE REVIEW

**Comment by pjain1** [comment]
Checks are green @jon-wei  can you have a look, thanks !

**Comment by jon-wei** [comment]
@pjain1 Thanks! I'll take a look this week

**Comment by pjain1** [comment]
@jon-wei can you please take a look

**Review by a2l007 — COMMENTED** [review]
Thanks for the PR! This is super useful and I'm looking forward to integrating this with our internal security extensions as well. 
It would be interesting to look at how certain fine grained security setups would work with the web console.

**Pull request closed without merging**
