### PR TITLE
Web console: update dev dependencies

### PR DESCRIPTION
**Pull request by jgoz**
### Description

This PR updates web-console dependency versions that are relatively safe and straightforward to upgrade. Some highlights:

- TypeScript 4.2
- Webpack 5
- Jest 26
- Prettier 2 (via awesome-code-style)

With the upgraded packages, `npm install` will now succeed on Node 14 without needing node-gyp.

And a couple of configuration changes:
- Enable sourcemaps in development mode for nicer debugging in the browser
- Set TypeScript `module` format to `esnext` to allow webpack to tree-shake

And finally, I removed some packages that were not being used.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by vogievetsky** [comment]
Thank you for the dependency updates, what a breath of fresh air!

The CI failure in the e2e tests looks legit:

image

**Comment by vogievetsky** [comment]
also with all the dependency updates please make sure to run the script `script/licenses` from the `web-console` directory. It should update the root license listing with the new versions of the modules per Apache requirements.

**Comment by jgoz** [comment]
@vogievetsky Thank you, I updated the licenses. It looks like `tslib >= 1.11.2` is now licensed under 0BSD, which does not require inclusion of the copyright header. (Druid formerly used 1.10, which was Apache 2.0 licensed).

And I think the e2e test failure is due to Travis using a really old version of Node for that one step since it doesn't run through mvn. I'm not a Travis expert, but I attempted to ask it for Node 10 to match the rest of the pipeline. We'll see if he listens.

**Comment by vogievetsky** [comment]
image

Nice!

**Review by vogievetsky — APPROVED** [review]
LGTM 👍

**Comment by vogievetsky** [comment]
image

...

image

Nice first contrib. good start, keep it up!

**Pull request merged**
