### PR TITLE
remove search auto strategy, estimateSelectivity of BitmapColumnIndex

### PR DESCRIPTION
**Pull request by clintropolis**
### Description
Removes the 'auto' strategy from the native search query to simplify `BitmapColumnIndex` to remove the `estimateSelectivity` method. The 'auto' strategy is not on by default, and in some cases can be rather expensive since for logical filters like AND/OR we fetch all of the indexes, compute the cardinality of each of them, and then throw them away, sometimes to turn around and do the same thing again to actually use the indexes.

The replacement for this will be smarter usage of indexes for all query types, as a follow-up I plan to bring the enhancements of #13977 to classic string typed columns, and I've got some additional improvements coming in the future.

[Related dev mailing list thread](https://lists.apache.org/thread/8lbgbo2977c88xxp714znmkg3w2lbkdj)

(This release note is currently a lie, but a follow-up PR will make it more true.)

#### Release note
The 'auto' strategy has been removed from the [search query](https://druid.apache.org/docs/latest/querying/searchquery). Specifying 'auto' will now be equivalent to specifying 'useIndexes'. Improvements to how and when indexes are computed in general have allowed 'useIndexes' to benefit and be more adaptive when it uses indexes for filter processing, skipping computing expensive indexes when possible.

<hr>

This PR has:

- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] a release note entry in the PR description.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by gianm — APPROVED** [review]
I'm ok with removing this. As far as I know, it's a rarely used feature, and removing it allows us to also remove `estimateSelectivity` and replace it with something better.

**Comment by gianm** [comment]
Merging, given there was already a dev list thread about this.

**Comment by LakshSingla** [comment]
@clintropolis Can you please update this change in the https://github.com/apache/druid/blob/master/docs/release-info/release-notes.md, in a follow-up PR as well?

**Comment by clintropolis** [comment]
>@clintropolis Can you please update this change in the https://github.com/apache/druid/blob/master/docs/release-info/release-notes.md, in a follow-up PR as well?

Why would I do that? I haven't seen any discussion that is part of the process unless I missed something...

**Pull request merged**
