### PR TITLE
remove use log of log4j v1

### LINKED ISSUE #12425: Security: remove use log of log4j v1
### Description

log4j v1 is end of life and full of security issues

Can you upgrade log4j v2.17.x or reload4j?

* indexing-hadoop/pom.xml
* extensions-core/hdfs-storage/pom.xml

### Motivation

Please provide the following for the desired feature or change:
- A detailed description of the intended use case, if applicable
- Rationale for why the desired feature/change would be beneficial

### PR DESCRIPTION
**Pull request by AlbericByte**
Fixes #12425.
### Description
log4j v1 is end of life and full of security issues
indexing-hadoop/pom.xml
extensions-core/hdfs-storage/pom.xml

remove log4j v1 dependences

#### Release note
remove log4j v1 dependences

<hr>

##### Key changed/added classes in this PR
 * `pom.xml`

<hr>

This PR has:

- [x] been self-reviewed.
- [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by AlbericByte** [comment]
@FrankChen021 thanks for help for reviewing when you have time.

There is one integration test failed(integration-index-tests-indexer (kafka-index)), which is not related to the modification from the log
```
ERROR: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "error reading server preface: read unix @->/run/docker.sock: use of closed network connection"
Error:  Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:1000)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:947)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:471)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
```

**Comment by cryptoe** [comment]
@AlbericByte Can you please test a druid build with HDFS storage and see if this patch does not break logging.

**Comment by AlbericByte** [comment]
@cryptoe  Thanks for your time and suggestion.
I have tested using following command, and it can build successfully
Does it meet your suggestion. if not, could you help provide more detail.
```
mvn clean install \
     -Pintegration-tests,skip-static-checks,skip-tests \
     -Ddocker.run.skip=true \
     -Ddocker.build.hadoop=true
```

**Comment by abhishekagarwal87** [comment]
I think @cryptoe meant to ask if the change is manually verified with HDFS as deep storage.

**Comment by AlbericByte** [comment]
@abhishekagarwal87 and @cryptoe 
Sorry for late, this is my first time to setup druid-hdfs-storage, i have launch a HADOOP docker environment, and test it work as expected, for example: the index log can be write to the HDFS as following:
```
druid_indexer_logs_type=hdfs
druid_indexer_logs_directory=hdfs://namenode:8020/drui/indexing-logs
```
Screenshot 2024-03-14 at 1 55 49 PM

**Review by abhishekagarwal87 — APPROVED** [review]

**Pull request merged**
