### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by samarthjain**
Fix CI broken after https://github.com/apache/druid/commit/36193955b6d8a03fe247157dddebea0365c7e501

### CODE REVIEW

**Review by clintropolis — APPROVED** [review]

**Comment by clintropolis** [comment]
i think we can merge after the forbidden api check passes

**Comment by samarthjain** [comment]
Not sure why the build is still complaining about `String.format`. I am going to retry the build.

**Review by jihoonson — APPROVED** [review]

**Comment by samarthjain** [comment]
I am not sure why the LGTM build is still failing. Should I go ahead and merge this PR, @clintropolis, @jihoonson ? The build is failing right at the line that this PR is fixing.

**Comment by samarthjain** [comment]
i am going to go ahead and merge this PR.

**Comment by jihoonson** [comment]
@samarthjain thanks for merging this PR. I think that LGTM has a step that runs a build against master before applying your change. LGTM seems to have failed in that step, which can't be passed without your change. It makes sense to me to ignore it this time. The forbidden API checks passed after this change is merged in https://app.travis-ci.com/github/apache/druid/builds/247394888.

**Pull request merged**
