### PR TITLE
Use intermediate-persist IndexSpec during multiphase merge.

### PR DESCRIPTION
**Pull request by gianm**
The main change is the addition of an intermediate-persist IndexSpec
to the main "merge" method in IndexMerger. There are also a few minor
adjustments to the IndexMerger interface to encourage more harmonious
usage of its methods in the future.

### CODE REVIEW

**Comment by gianm** [comment]
This patch is getting nailed for test coverage in UnifiedIndexerAppenderatorsManager's LimitedPoolIndexMerger. In looking into this I've noticed that the class does need more tests, but also that a lot of IndexMerger interface methods are currently unused. Rather than add tests for all these unused methods, I'm looking into removing them.

**Comment by gianm** [comment]
I pushed a change that removes the unused-in-production IndexMerger methods "append" and "convert", and adds additional unit tests to UnifiedIndexerAppenderatorsManager. Hopefully this will satisfy the coverage checker.

**Comment by gianm** [comment]
The "analyze hadoop 3 dependencies" step keeps failing with this error:

```
[ERROR] error reading /home/travis/.m2/repository/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar; error in opening zip file
[ERROR] error reading /home/travis/.m2/repository/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar; cannot read zip file
```

I'm not sure why that would be; maybe it's a caching thing on the Travis side? Restarting the test doesn't help. Is there a "super-restart"?

**Comment by gianm** [comment]
> I'm not sure why that would be; maybe it's a caching thing on the Travis side? Restarting the test doesn't help. Is there a "super-restart"?

I deleted all the Travis caches, maybe that'll do it.

**Comment by gianm** [comment]
> I deleted all the Travis caches, maybe that'll do it.

Looks like that helped!

**Review by clintropolis — APPROVED** [review]
:+1:

**Pull request merged**
