### PR TITLE
Add useNativeQueryExplain in sql query context documentation

### LINKED ISSUE #12924: Add useNativeQueryExplain to SQL Query context docs
The [configuration docs](https://druid.apache.org/docs/latest/configuration/index.html#sql) mention that `druid.sql.planner.useNativeQueryExplain` can be overridden per query by the context key `useNativeQueryExplain` .

`useNativeQueryExplain` should be added to [SQL query context](https://druid.apache.org/docs/latest/querying/sql-query-context.html) docs.

### PR DESCRIPTION
**Pull request by Mihaylov93**
Fixes #12924.

### Description

Added the missing sql query context flag to the documentation.

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
Thank you for your contribution @Mihaylov93

**Comment by clintropolis** [comment]
this got merged without running through travis and it appears to be failing spellcheck in [other PRs](https://app.travis-ci.com/github/apache/druid/jobs/580521295#L758):

```
    ../docs/querying/sql-query-context.md
       45 | in plan generated by Calcite.|druid.sql.planner.useNativeQueryExplain on the Broker (default: False 
```

**Comment by Mihaylov93** [comment]
https://github.com/apache/druid/pull/12936 There is this PR too

**Comment by clintropolis** [comment]
I've opened #12940 to fix travis

**Comment by abhishekagarwal87** [comment]
ah. The fact that PR becomes green, without travis running, is really annoying. thanks for fixing it, @clintropolis.

**Pull request merged**
