### PR TITLE
Thread-safety for ResponseContext.REGISTERED_KEYS

### LINKED ISSUE #9106: Unbalanced synchronization of ResponseContext.REGISTERED_KEYS
To make it really thread-safe:
 1. `keyOf()` and `getAllRegisteredKeys()` should be made synchronized;
 2. `getAllRegisteredKeys()` should return a defensive copy: `new TreeMap<>(REGISTERED_KEYS).values()`

Relevant concurrency checklist items: https://github.com/code-review-checklists/java-concurrency#unsafe-concurrent-point-read, https://github.com/code-review-checklists/java-concurrency#unsafe-concurrent-iteration

### PR DESCRIPTION
**Pull request by alex-plekhanov**
Fixes #9106

### Description

This PR fixes potential concurrency problems of ResponseContext.REGISTERED_KEYS.
TreeMap was replaced with ConcurrentSkipList to make ResponseContext.REGISTERED_KEYS thread-safe.

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.

<hr>

##### Key changed/added classes in this PR
 * `ResponseContext`

### CODE REVIEW

**Comment by alex-plekhanov** [comment]
Up

**Comment by alex-plekhanov** [comment]
up

**Review by gianm — APPROVED** [review]
Looks good to me. I suppose another solution would be to make `registerKey` private, but perhaps it would be called in an extension.

**Comment by gianm** [comment]
Thanks @alex-plekhanov!

**Pull request merged**
