### PR TITLE
Added prometheus-emitter docs which was missing

### PR DESCRIPTION
**Pull request by jp707049**
### Description
Currently in the latest druid docs, we cannot find the documentation related to prometheus emitter (https://druid.apache.org/docs/latest/development/extensions.html#community-extensions).

Update the main `extension.md` to add `prometheus-emitter` docs.

This PR has:
- [ x ] been self-reviewed

### CODE REVIEW

**Comment by jp707049** [comment]
@suneet-s Can you rerun the travis check? Or it's okay to merge this since it's a doc change.

**Comment by suneet-s** [comment]
@jp707049 The docs failure appears to be legit - it is complaining about a broken link

```
[WARN] unresolved links in file 'development/extensions.md' > [ '../development/extensions-contrib/prometheus.md' ]
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
Could not find '../development/extensions-contrib/prometheus.md' linked from './build/ApacheDruid/docs/development/extensions.html'
There are 1 issues
```

You can run the tests locally if you want to try it out by reading `.travis.yml` and looking at the `docs` job

**Comment by jp707049** [comment]
@suneet-s , 
I actually fixed that in above commit `Rename prometheus.md to prometheus-emitter.md` 
I renamed the file from `prometheus.md` to `prometheus-emitter.md`. Here is the link  to the commit 
https://github.com/jp707049/druid/commit/71990ed47f61506ad91e9faa620a8a97845ab5e4

**Comment by jp707049** [comment]
@suneet-s It's now showing spell check error but I looked it up and spelling is correct for prometheus.

**Comment by clintropolis** [comment]
>@suneet-s It's now showing spell check error but I looked it up and spelling is correct for prometheus.

The spelling custom words file is pointing to the old path, https://github.com/apache/druid/blob/master/website/.spelling#L611. It either needs fixed to point to the new path, or the entries from this path moved to the top part of the file which is stuff that applies to all files. (Not really sure why we have both global entries and path specific entries...)

**Comment by jp707049** [comment]
I will create a new PR with filename `prometheus.md`

**Pull request closed without merging**
