### PR TITLE
Change the default format from OBJECT to OBJECTLINES

### PR DESCRIPTION
**Pull request by adarshsanjeev**
Change the default results format for the SqlStatementResource from OBJECT to OBJECTLINES for better formatting.

New format:
Screenshot 2023-07-31 at 12 10 53 PM

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by LakshSingla** [comment]
CI failures look legit

**Comment by adarshsanjeev** [comment]
Updated the tests. This is temporary and will be reworked while adding support for other formats in the other PR. This is mostly for the 27 release.

**Comment by LakshSingla** [comment]
There are still some test failures, can you please address them

**Review by vogievetsky — APPROVED** [review]
As the biggest champion of OBJECTLINES, thank you!

**Pull request merged**
