### PR TITLE
Fix compiler error on kafka-emitter

### PR DESCRIPTION
**Pull request by didip**
### Description

Fix compiler error on IDE:
```
The project was not built since its build path is incomplete. Cannot find the class file for org.slf4j.Logger. Fix the build path then try building this project
```

<hr>

##### Key changed/added classes in this PR
 * `KafkaEmitter.java`

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
Kafka emitter does not directly use API in slf4j. Which IDE are you using? Intellij? If it is, usually 'Reload All Maven Projects' button on the Maven panel solves compliation problem on IDE.

**Comment by didip** [comment]
@FrankChen021 I am seeing this error on VSCode.

**Comment by dampcake** [comment]
I have worked around this by using the solution posted at the end of https://github.com/redhat-developer/vscode-java/issues/2569 but maybe we should add the directive to the pom?

**Comment by FrankChen021** [comment]
@dampcake Thanks for the link. Seems it's a problem at the vs code side. 

I'm wondering if this problem is only on Kafka emitter extension?

**Comment by didip** [comment]
Yes, it is indeed only on kafka-emitter extension.

**Comment by didip** [comment]
Without adding that dependency, this is marked as broken:
```java
public class KafkaEmitter implements Emitter
{
  private static Logger log = new Logger(KafkaEmitter.class);
  ...
}
```
with the following message:
```
The type org.slf4j.Logger cannot be resolved. It is indirectly referenced from required .class files
```

**Comment by dampcake** [comment]
It should affect any IDE that uses m2e; VSCode and Eclipse, possibly others. Would also extend to stuff based on those like GitHub Codespaces.

**Comment by FrankChen021** [comment]
But if we look at other extensions, such as graphite emitter, it has the same code,

```java
public class GraphiteEmitter implements Emitter
{
  private static Logger log = new Logger(GraphiteEmitter.class);
```

And this extension does not explictly include slf4j dependency. Why does it have similar compliation error? This is weired.

**Comment by FrankChen021** [comment]
image

From the dependency-analyzer, these two extensions differ from each other on the slf4j-api dependency.

I think the problem might be due to `kafka-client` module which declares the scope of slf4j-api as `runtime`.

**Review by FrankChen021 — APPROVED** [review]

**Pull request merged**
