### PR TITLE
[Bug]Kinesis-data-format IT can not work

### PR DESCRIPTION
**Pull request by zhangyue19921010**
### Description

The IT for Kinesis-data-format can't work because:
1. Didn't launch schema registry service.
2. Didn't parse supervisor.json correctly.

This PR solved this bug and tested on local env.

<hr>
屏幕快照 2021-03-18 下午3 02 46

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by suneet-s** [comment]
@zhangyue19921010 I removed the bug label, since that's typically used for bugs in Druid code, as opposed to an issue with the tests. `Area - Testing` seems like a good label for this PR

**Comment by zhangyue19921010** [comment]
> @zhangyue19921010 I removed the bug label, since that's typically used for bugs in Druid code, as opposed to an issue with the tests. `Area - Testing` seems like a good label for this PR

Got it. Thanks for your reminding. By the way could you please take a look at this IT fix at your convince :)

**Review by clintropolis — APPROVED** [review]
:+1:

**Review by suneet-s — APPROVED** [review]
👍

**Pull request merged**
