### PR TITLE
Add authentication call before cleaning up intermediate files in hadoop ingestions

### PR DESCRIPTION
**Pull request by capistrant**
### Description

Druid Version: 0.22.0
Hadoop Version: 3.3.0

#### Fixed issue observed in hadoop ingestion intermediate file cleanup

I observed my hadoop tasks running against my kerberized hadoop cluster having authentication failures when trying to cleanup intermediate files during hadoop ingestion after upgrading to 0.22.X (from 0.20.X). This is a similar issue to what I had seen in the past when the job went into a graceful shutdown of a hadoop ingestion job (https://github.com/apache/druid/pull/9785). I'm suspicious that moving the file deletes into their own static JobHelper method introduced this experience I am seeing (https://github.com/apache/druid/pull/11194). The call to authenticate is idempotent. If the authentication is already done, no action will be taken. ~I added a debug log to help people trouble shooting potential issues in the future.~

<hr>

##### Key changed/added classes in this PR
 * `JobHelper`

<hr>

This PR has:
- [X] been self-reviewed.
- [X] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by capistrant** [comment]
@zachjsh could you take a peak at this when you have a chance? I'm not positive but am thinking it is related to a change you made in the past

**Comment by capistrant** [comment]
don't close

**Review by a2l007 — APPROVED** [review]
Fix looks reasonable, Thanks for your patience!

**Comment by capistrant** [comment]
Thanks @a2l007!

**Pull request merged**
