### PR TITLE
Add helm chart for Apache Druid

### PR DESCRIPTION
**Pull request by asdf2014**
### Description

This patch added a helm chart for Apache Druid.

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

cc @maver1ck @AWaterColorPen

### CODE REVIEW

**Comment by FrankChen021** [comment]
Do we need a tutorial like the tutorial of docker ( docs/tutorials/docker.md ) ?

**Comment by asdf2014** [comment]
Hi, @FrankChen021 . Thanks for your comment. I also considered whether to publish the doc, for example, put the `helm/README.md` file in the `docs/tutorials` directory. However, although this Helm Chart can deploy on the K8S cluster directly, there are still a few things that need to be completed before the document is published on the official website. For example: upgrade the Druid image version, support HDFS cluster deployment, release the Release version of Druid's Helm Chart by configuring Github Action, and etc. But these things are difficult to complete in a short period of time, so we should finish them in these follow-up PRs.

**Review by QiuMM — APPROVED** [review]
Nice work, lgtm.

**Comment by jihoonson** [comment]
Hey @asdf2014, have you sorted out the potential license issue before you merge this PR? I don't see it anywhere. As Julian suggested in https://lists.apache.org/thread.html/ra93200245a27fb77ff0a1cfc17d21b7efbbb263ae422d6d2cc5ade11%40%3Cdev.druid.apache.org%3E, we may need to go through a process similar to the IP clearance for podling projects.

**Comment by asdf2014** [comment]
Hi, @jihoonson. I didn't notice it, let me take a look. Thank you very much for reminding.

**Comment by clintropolis** [comment]
>Hey @asdf2014, have you sorted out the potential license issue before you merge this PR? I don't see it anywhere. As Julian suggested in https://lists.apache.org/thread.html/ra93200245a27fb77ff0a1cfc17d21b7efbbb263ae422d6d2cc5ade11%40%3Cdev.druid.apache.org%3E, we may need to go through a process similar to the IP clearance for podling projects.

I think we should consider reverting this until we get this resolved, after reading through https://incubator.apache.org/ip-clearance/, and looking at https://incubator.apache.org/ip-clearance/tika-tika-helm.html which appears to be a similar helm chart donation for another project, where I see linking to a voting thread, etc.

**Comment by clintropolis** [comment]
unrelated nitpick, i think putting this stuff in `distribution/helm/`, which is also where the Docker stuff lives, makes more sense to me than top level `helm/`

**Comment by clintropolis** [comment]
btw, in general I think it makes sense to maintain it here, so +1 on the idea (even though I know very little about helm)

**Comment by asdf2014** [comment]
Hi, @clintropolis . Thanks for your comments and support. As far as I know, the license of `helm/charts` is
Apache License 2.0. Maintaining Apache Druid’s own Helm Chart in the Apache Druid repo should not have copyright issues. I heard about the process just mentioned by @jihoonson for the first time, so I’ll look at it. In addition, Apache Superset has actually done this, and we can get more details through the link [https://github.com/apache/superset/tree/master/helm/superset](https://github.com/apache/superset/tree/master/helm/superset).

**Comment by xvrl** [comment]
@asdf2014 my understanding is that we still need to highlight were the code came from, just like we do for other Apache License 2.0 code we include or borrow.

Also, has this chart been tested? Does it still work?

**Comment by jihoonson** [comment]
I haven't closely checked the IP clearance or other ASF processes to adopt codes from outside the project after graduation. But my 2 cents is we probably need a PMC vote for adopting.

**Comment by asdf2014** [comment]
Hi, @xvrl. Thanks for your comment. I agree with you, the follow-up related documents will be improved. I also mentioned before that this Druid Helm Chart is completely usable, and it has been tested several times last week.

**Comment by asdf2014** [comment]
Hi, @jihoonson. Thank you for your comments. It was previously maintained by @maver1ck @AWaterColorPen and I. Currently, https://github.com/helm/charts/tree/master/incubator/druid cannot be maintained. So, we want maintain it here, just like other Apache projects did, such as [Apache Superset](https://github.com/apache/superset/tree/master/helm/superset). Indeed, I agree with your proposal. Let's raise up a PMC vote. If it really fails to pass the vote, we can revert this PR ASAP. Could you please help initiate the vote?

**Comment by jihoonson** [comment]
@asdf2014 I'm not saying we should not accept this. I'm saying this doesn't seem the right process. Have you read the [ASF IP clearance doc](https://incubator.apache.org/ip-clearance/)? The IP clearance is not just about the license. All codes in the ASF projects are owned by the ASF and the IP clearance process is required to make this part clear. The IP clearance doc explicitly says

> This is for projects and PMCs that have already been created and are receiving a code donation into an existing codebase. Any code that was developed outside of the ASF SVN repository and our public mailing lists must be processed like this, even if the external developer is already an ASF committer. 

I think we should revert this PR and go through the IP clearance process because this was developed outside of ASF. Please go back to the dev thread for this issue and add more details there (not here) for people like me who don't know much about the helm chart such as

- What is the current status of the project? 
  - Does it reflect the most recent release of Druid?
  - How is it being tested?
- Why is it best to host the helm chart in the druid repo? What alternatives have you considered?
- After migration, what is your plan for automatic testing?

I don't think this is an exhaustive list. Please add details as much as possible.

**Comment by asdf2014** [comment]
@jihoonson I see. And I agree with your suggestion. Let us follow the process of IP clearance to eliminate potential problems. I will do my best to provide answers to these questions. I have discussed it with other maintainers, and there are many improvements to it that cannot be contributed to the open source community. So, let's unify the maintenance of Druid's Helm Chart as soon as possible. Thanks a lot for your patience.

**Pull request merged**
