### PR TITLE
Metrics for shenandoah

### LINKED ISSUE #6424: Support new Java GC algorithms (Shenandoah and ZGC) in JvmMonitor
In this code:
https://github.com/apache/incubator-druid/blob/431d3d8497f9079857c3baa7ae7ab4cb44a22355/java-util/src/main/java/org/apache/druid/java/util/metrics/JvmMonitor.java#L253-L271

### PR DESCRIPTION
**Pull request by didip**
Based on this source code: 

https://github.com/openjdk/jdk/blob/554caf33a01ac9ca2e3e9170557e8348750f3971/src/hotspot/share/gc/shenandoah/shenandoahMonitoringSupport.cpp#L65

Partially fixes #6424 by generating metrics for Shenandoah. Too bad ZGC does not have similar MonitoringSupport.cpp file.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by xvrl** [comment]
@didip can you confirm which JVM versions this works with? Have you only tested on Java 11 or does this also work on Java 15?

**Comment by gianm** [comment]
> @didip can you confirm which JVM versions this works with? Have you only tested on Java 11 or does this also work on Java 15?

I just checked and it looks like the names "Shenandoah partial" and "Shenandoah full" are used on both Java 11 and Java 15.

**Review by clintropolis — APPROVED** [review]

**Comment by didip** [comment]
@gianm yes, correct. Sorry for the late response, I am still on paternity leave.

**Comment by gianm** [comment]
> @gianm yes, correct. Sorry for the late response, I am still on paternity leave.

No problem; and, congratulations 🙂

The only legit failure for this patch is test coverage. I'm planning on adding additional tests for JvmMonitor in #12469, so I'll merge this patch now and do all the new tests over there.

**Pull request merged**
