### PR TITLE
【isuue 10547】doc wrong description of configuration

### PR DESCRIPTION
**Pull request by QingdongZeng3**
Fixes wrong description of configuration .

### Description

Due to the code , druid.coordinator.kill.pendingSegments.on time depend on druid.coordinator.period.indexingPeriod（default PT30M）,not druid.coordinator.period（default PT60S）。

https://github.com/apache/druid/blob/master/services/src/main/java/org/apache/druid/cli/CliCoordinator.java#L217
https://github.com/apache/druid/blob/master/services/src/main/java/org/apache/druid/cli/CliCoordinator.java#L239

#### Added a forbidden-apis entry ...

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

### CODE REVIEW

**Comment by QingdongZeng3** [comment]
@gianm Hi Gian，could you help to review my code？Thanks！

**Comment by FrankChen021** [comment]
I think this change in doc reflects the behavior of current implementation. @jihoonson what do you think ?

**Comment by QingdongZeng3** [comment]
> I think this change in doc reflects the behavior of current implementation. @jihoonson what do you think ?

Yes , you can search this log in  coordinator.log  ,it will happened per 30 min

https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/server/coordinator/KillStalePendingSegments.java#L78

**Comment by QingdongZeng3** [comment]
@jihoonson  Hi Jihoon, could you help to review my code？Thanks！

**Review by jihoonson — APPROVED** [review]
I think you are right. @QingdongZeng3 thanks for the fix!

**Comment by QingdongZeng3** [comment]
> I think you are right. @QingdongZeng3 thanks for the fix!

Thanks for your review and merging！

**Pull request merged**
