### PR TITLE
Simplify ServiceMetricEvent.Builder

### PR DESCRIPTION
**Pull request by kfaraz**
### Description

Building a `ServiceMetricEvent` using a `ServiceMetricEvent.Builder` is a little confusing right now because we need to chain two `build()` calls to get the final `ServiceMetricEvent`. This is because the `ServiceMetricEvent.Builder` is a builder of a builder.

#### Existing
```java
ServiceMetricEvent event
  = ServiceMetricEvent.builder()
                      .setDimension("dataSource", "wiki")
                      .setDimension("tier", "cold")
                      .build("segment/unavailable/count", 100)
                      .build(serviceDimensions)
```

#### Proposed
```java
ServiceMetricEvent event
  = ServiceMetricEvent.builder()
                      .setDimension("dataSource", "wiki")
                      .setDimension("tier", "cold")
                      .setMetric("segment/unavailable/count", 100)
                      .build(serviceDimensions)
```

### Changes
- Make `ServiceMetricEvent.Builder` extend `ServiceEventBuilder<ServiceMetricEvent>` and thus convert it to a plain builder rather than a builder of builder.
- Add methods `setCreatedTime` , `setMetricAndValue` to the builder

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by LakshSingla** [comment]
WDYT of renaming the method that adds the metric as `.setMetric("segment/unavailable/count", 100)` instead of `.setMetricAndValue("segment/unavailable/count", 100)` due to following reasons:
1. The other methods in the builder don't specify `andValue` at the end, i.e. they are named as `setDimension` instead of `setDimensionAndValue, and `setMetric` seems more consistent.
2. It is kinda implicit that the second arg would be a value, and `setMetric` seems cleaner.

**Comment by kfaraz** [comment]
Yeah, I had originally used `setMetric`, but later changed to this. I can revert to using `setMetric` if it seems more consistent with the rest of the methods.

**Review by LakshSingla — APPROVED** [review]
LGTM 🚀 though there are some test failures.

**Comment by kfaraz** [comment]
Thanks for the review, @LakshSingla !

**Pull request merged**
