### PR TITLE
Refactor Test Code to Reduce Mock Duplication For Issue #15979

### LINKED ISSUE #15979: Refactoring the Duplicated/Redundant Mock Objects in `Test Case` of org.apache.druid.query.groupby.epinephelinae.column
### Description
Hello Druid Developers,
I have identified a recurring pattern of code duplication across several test classes in the Apache Druid project. Specifically, the process of mocking `ColumnValueSelector` objects is repeated in multiple test cases, leading to unnecessary code bloat and complexity.

### Mock clone in Test Classes

- `ArrayDoubleGroupByColumnSelectorStrategyTest`
- `ArrayLongGroupByColumnSelectorStrategyTest`
- `ArrayStringGroupByColumnSelectorStrategyTest`

### Example of Code Duplication

Currently, our test classes contain repeated blocks of code for mocking `ColumnValueSelector` objects and repeated  9 times, as shown below:

```java
ColumnValueSelector columnValueSelector = Mockito.mock(ColumnValueSelector.class);
Mockito.when(columnValueSelector.getObject()).thenReturn(ImmutableList.of(1.0, 2.0));
```

### Proposed Solution

Introduce a new utility class, `CreateMockColumnValueSelector`, which centralizes the creation of mocked `ColumnValueSelector` objects. This class will provide a static method to return a mocked `ColumnValueSelector` with predefined behavior, reducing the duplication and improving code maintainability.

### Suggested Implementation

Below is a proposed implementation snippet for the `CreateMockColumnValueSelector` utility class:

```java
public class CreateMockColumnValueSelector {
    public static <T> ColumnValueSelector get(Object returnValue) {
        ColumnValueSelector columnValueSelector = Mockito.mock(ColumnValueSelector.class);
        Mockito.when(columnValueSelector.getObject()).thenReturn(returnValue);
        return columnValueSelector;
    }
}
```
We only need to call get() to reduce repetition

```java
ColumnValueSelector columnValueSelector = CreateMockColumnValueSelector.get(new Object[]{"f", "a"});
```
By doing this, code repetition can be reduced. Make the test code clearer
I'd love to hear your thoughts on this proposal! Do you agree with any of these changes, or do you have other insights or preferences?

### PR DESCRIPTION
**Pull request by gzhao9**
#### Description
Fixes #15979

This PR addresses the issue #15979 of duplicated mock creation code across multiple test classes within the Apache Druid project. By introducing the `CreateMockColumnValueSelector.java` utility class, I aim to centralize the creation of mocked `ColumnValueSelector` objects, thereby enhancing code reusability and simplifying maintenance.

In the course of testing, particularly within the `ArrayDoubleGroupByColumnSelectorStrategyTest`, `ArrayLongGroupByColumnSelectorStrategyTest`, and `ArrayStringGroupByColumnSelectorStrategyTest` classes, I identified a pattern of duplicate code concerning mock object creation. This redundancy not only bloats the test code but also introduces unnecessary complexity.

#### Solution

The newly introduced `CreateMockColumnValueSelector` class provides a streamlined approach to generating mocked `ColumnValueSelector` instances, equipped with predefined behaviors. This approach significantly reduces the boilerplate code in our test suite and improves the readability and maintainability of our tests.

#### Key changed/added classes in this PR

- `CreateMockColumnValueSelector`
- Modified:
  - `ArrayDoubleGroupByColumnSelectorStrategyTest`
  - `ArrayLongGroupByColumnSelectorStrategyTest`
  - `ArrayStringGroupByColumnSelectorStrategyTest`

By doing this, code repetition can be reduced. Make the test code clearer
I'd love to hear your thoughts on this proposal! Do you agree with any of these changes, or do you have other insights or preferences?

### CODE REVIEW

**Review by cryptoe — CHANGES_REQUESTED** [review]
Thanks for taking out the time. I donot see value in this refactor. This adds another layer which is used in a single testClass.

**Comment by gzhao9** [comment]
> Thanks for taking out the time. I donot see value in this refactor. This adds another layer which is used in a single testClass.


Thank you for your feedback. I've removed `CreateMockColumnValueSelector` and added its creat mock function directly into the test classes as suggested. Could you please share your preferences for preparing mock object data in tests? Or any suggestions you wish to change?

**Comment by gzhao9** [comment]
> > Thanks for taking out the time. I donot see value in this refactor. This adds another layer which is used in a single testClass.
> 
> Thank you for your feedback. I've removed `CreateMockColumnValueSelector` and added its creat mock function directly into the test classes as suggested. Could you please share your preferences for preparing mock object data in tests? Or any suggestions you wish to change?

I'd like to clarify. When I first submitted my PR, the class was used by 3 test classes, not a single test class. So I'm a little confused about `This adds another layer which is used in a single testClass.`.

If you mean to avoid creating a new class. my modification is to create a method in each test class. In the test case, the method is called to minimize the duplicate creation of mock objects.

**Review by kfaraz — CHANGES_REQUESTED** [review]
@gzhao9 , thanks for creating this PR. But I agree with @cryptoe , these changes are not adding any value to the tests. We are reducing only one line in each test method and that only ends up compromising the readability of the test.

We could try to create a simple implementation of `BaseObjectColumnValueSelector` and use that instead of creating the mocks, but I don't really see any necessity for doing that either.

@gzhao9 , if you interested in improving the unit tests, maybe you could try looking at some of the slow running tests to improve their performance.

**Pull request closed without merging**
