### PR TITLE
Prioritize query stats in RequestLogLine.getNativeQueryLine

### PR DESCRIPTION
**Pull request by Zeyu-Chen-SFDC**
### Description
This change switches the order of query vs stats in `getNativeQueryLine` to keep it consistent with `getSqlQueryLine`.

It happens on non-trivial occasions when a long list of `intervals.segments` in the query object exceeds the max cut-off of whichever logging system is deployed by the user and makes the stats unavailable for subsequent log searches. In those situations, we prefer to have the more important stats logged first and sacrifice the list of intervals.

The same change should be applied to the order of fields in the native query object, moving `intervals` to the last. However, that's a bigger change.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `RequestLogLine`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by findingrish — APPROVED** [review]
LGTM, please rebase to re-trigger the build.

**Comment by cryptoe** [comment]
@Zeyu-Chen-SFDC Could you please fix CI ?

**Comment by Zeyu-Chen-SFDC** [comment]
@cryptoe 
Rebasing fixed the static check CI error. The errors from "[standard-its / integration-index-tests-middleManager (ldap-security) / ldap-security integration test (Compile=jdk17, Run=jdk17, Indexer=middleManager, Mysql=com.mysql.jdbc.Driver)](https://github.com/apache/druid/actions/runs/12294518184/job/34319926016?pr=17326#logs)" does not appear to be related to the PR.

**Comment by cryptoe** [comment]
@Zeyu-Chen-SFDC Thanks for the contribution to Apache Druid. Looking forward to many more 🚀

**Pull request merged**
