### PR TITLE
Fix hash calcuation in RendezvousHasher

### PR DESCRIPTION
**Pull request by rohangarg**
This change fixes the hash calculation logic in RendexvousHasher. @abhishekagarwal87 pointed that RendezvousHashing based JDBC connection balancing produces a skew in the distribution of the connections amongst brokers.

Upon checking further, it was found that the `combineOrdered` call to generate a composite hash wasn't uniformly distributing the hash value amongst all the brokers. So, the new logic creates the composite hash using the `Murmur_128` hasher which leads to a uniform distribution of load. On testing locally with 8 brokers, the old logic could produce as much as 20% skew between the lightest and heaviest broker. After this change, the skew is consistently observed to be < 5%.

The benchmark run also shows improvement in runtime with the new hashing logic.
```
Before 

Benchmark                       (numIds)  Mode  Cnt       Score     Error  Units
RendezvousHasherBenchmark.hash    100000  avgt   30  129676.458 ± 950.211  us/op

After 

Benchmark                       (numIds)  Mode  Cnt      Score      Error  Units
RendezvousHasherBenchmark.hash    100000  avgt   30  97226.880 ± 1019.564  us/op
``` 

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
Thanks for fixing this, Rohan. can you also add a test so that any change in the future doesn't cause a skew? For this, you will have to hardcode the input connection ids. so you can generate 100 random ids and then use them in test.

**Comment by rohangarg** [comment]
Thanks for the review @abhishekagarwal87. I have added a test for verifying distribution in 100 request keys amongst 5 brokers.

While testing, I found that as the number of request keys decrease the skewness increases in the new algorithm as well. I ran some tests with old and new rendezvous hashing algorithm along with consistent hashing. The test includes 8 brokers and computes the max skew for (100, 1000, 10_000) request keys. max skew is calculated as the difference in request between lightest and heaviest broker. Each request key count config is run 1000 times and the result is the maximum skew amongst all the runs.
Please find below the results : 

| hashing algorithm | max skew with 100 request keys | max skew with 1000 request keys | max skew with 10_000 request keys|
|-------------------|------------------|-------------------|----------------------|
| rendezvous old | 20 (20%) | 67 (6.7%) | 193 (1.93%) |
| rendezvous new | 34 (34%) | 238 (23.8%) | 2090 (21%) |
| consistent hash | 22 (22%) | 72 (7.2%) | 395 (3.95%) |

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
Thanks Rohan for the analysis. Changes LGTM. Once the CI passes, you can merge it yourself :)

**Comment by rohangarg** [comment]
Thanks for the review @abhishekagarwal87

**Pull request merged**
