### PR TITLE
Allow using jsonpath predicates with AvroFlattener

### PR DESCRIPTION
**Pull request by lkm**
References #5792. Not entirely relevant to error described, however, it's very closely related to being able to use jsonpath predicates

### Description

I'm trying to use more advanced jsonpath inline queries in while ingesting avro data. An example `flattenSpec` would be
```json
{
  "type": "path",
  "name": "attribute__test",
  "expr": "$.attributes[?(@.name == 'somekey')][0].value"
}
```
where the data looks like this (an array of avro records):

```json
{
  "attributes": [
    {
      "name": "somekey",
      "value": "test value",
    },
    {
      "name": "someotherkey",
      "value": "other value",
    }
  ]
}
```

Hoping to get the following data out in the dimension: `test value`. This would greatly improve Druid's ability to consume more intricate Avro schemas. 

The problem it seems was that when using queries the`GenericAvroJsonProvider::unwrap` method is called in Jayway, since it throws an exception the query is prevented and thus returning nothing (it silenced via `com.jayway.jsonpath.Option.SUPPRESS_EXCEPTIONS`). It doesn't seems that any wrapping occurs thus it should be safe to just return the object as is.

#### Added a forbidden-apis entry ...

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by dylwylie** [comment]
LGTM - thanks for the contribution

**Review by dylwylie — APPROVED** [review]

**Comment by lkm** [comment]
@dylwylie Thank you. Do you think there's any chance this will be merge before 0.20?

**Comment by dylwylie** [comment]
Hey @lkm there's been enough time for anyone else to make any comments so I'll merge.

The 0.20 branch has already been created so I'm not sure if it'll make it into the next release. I think it'd be worthwhile to include though so I'll assign it to the milestone but if the release manager disagrees it may get pushed out to the next release.

**Comment by lkm** [comment]
That was quick! Thanks again

**Comment by jon-wei** [comment]
@dylwylie We don't usually include non-bug patches after the branch cut, but I'll go ahead and pull this into 0.20.0

**Pull request merged**
