### PR TITLE
IdUtils: Forbid characters that cannot be used in znodes.

### PR DESCRIPTION
**Pull request by gianm**
Objects like datasources and tasks are commonly used in znode paths.

### CODE REVIEW

**Comment by a2l007** [comment]
Curious but did you run across any related curator exceptions which prompted this fix?

**Comment by gianm** [comment]
> Curious but did you run across any related curator exceptions which prompted this fix?

Not in production, but I was testing with a bunch of crazy characters to see what would happen and ran into this. #10645 and this patch both came from that effort. In a future patch I'd like to add all these crazy characters to the integration tests, but I didn't do it immediately, because I ran into problems with getting Maven to pass them along properly.

**Comment by vogievetsky** [comment]
And in a collaborative effort I have added this https://github.com/apache/druid/pull/10647/commits/4696d9c13d873b5a22a9ee00cc57a401617278ea#diff-038617639194a8d2235be0dd808371b8af5620f0b7d897c0a2adaff7eddc1f6bR41 to the web console e2e tests.

Partly because it tests characters that are apparently forbidden by maven 🤷‍♀️ ... JavaScript to the rescue I guess!

So these e2e tests open up the web console in a headless browser and create a datasource like ```load-data-from-local-disk-<=>+|!@#$%^&`'".,:;\*()[]{}Россия 한국 中国!?~2020-12-08T23:20:16.130Z```

and then query it:

image

this is a true e2e tests as it tests the web console also.

**Review by a2l007 — APPROVED** [review]
+1 after CI. Thanks!

**Comment by gianm** [comment]
Wow. Glad that absolute unit of a datasource name works end to end.

**Comment by gianm** [comment]
> forbidden by maven

Not necessarily forbidden, more that I just couldn't figure out how to get them escaped properly.

**Pull request merged**
