### PR TITLE
Bump commons-io to 2.11.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### Description

https://github.com/apache/druid/pull/11338 upgraded `commons-io` from 2.6 to 2.9.
https://github.com/apache/druid/pull/11392 reverted it back due to https://issues.apache.org/jira/browse/IO-741 .

Since commons-io 2.11.0 fixed IO-741, this PR aims to retry the upgrade and remove the commons-io pinning from Dependabot.

BTW, the integration test (https://github.com/apache/druid/issues/11393) is not added yet because it isn't easy.

#### Fixed the bug ...

This will bring the bug fixes of 2.7 ~ 2.11
- https://commons.apache.org/proper/commons-io/changes-report.html
    - 2.11: 2021-07-09
    - 2.10: 2021-06-10
    - 2.9: 2021-05-22
    - 2.8: 2020-09-05
    - 2.7: 2020-05-24

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The failure is the following, but it seems to be irrelevant from this PR.
```
[ERROR] server/src/main/java/org/apache/druid/segment/realtime/firehose/InlineFirehose.java:44 -- The declared exception <code>IOException</code> is never thrown
12965The command "./check_test_suite.py && travis_terminate 0 || docker run --rm -v $(pwd):/project -v ~/.m2:/home/inspect/.m2 ccaominh/intellij-inspect:1.0.0 /project/pom.xml /project/.idea/inspectionProfiles/Druid.xml --levels ERROR --scope JavaInspectionsScope
```

**Comment by jihoonson** [comment]
Hi @dongjoon-hyun, thank you for the PR. The change LGTM, but the CI failure seems legit because [IOUtils.lineIterator no longer throws IOException in 2.11](https://github.com/apache/commons-io/blob/rel/commons-io-2.11.0/src/main/java/org/apache/commons/io/IOUtils.java#L1599). Can you please remove it from the `InlineFirehose` constructor? You would probably want to remove it from `InlineFirehoseFactory.connect` as well.

**Comment by dongjoon-hyun** [comment]
Oh, sure. Thank you, @jihoonson !

**Comment by dongjoon-hyun** [comment]
The integration test failure looks irrelevant.
```
 32357.73 (Compile=openjdk8, Run=openjdk11) batch index integration test
```

**Comment by jihoonson** [comment]
@dongjoon-hyun thanks for fixing the CI failure. The one failed looks flaky. I restarted it.

**Review by suneet-s — APPROVED** [review]
👍

**Comment by dongjoon-hyun** [comment]
Thank you, @jihoonson and @suneet-s !

**Comment by dongjoon-hyun** [comment]
All tests passed finally.

**Review by jihoonson — APPROVED** [review]
LGTM. Thanks @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by suneet-s** [comment]
Thanks @dongjoon-hyun !

**Pull request merged**
