### PR TITLE
Fix hostname validation not skipping with `druid.client.https.validateHostnames=false` in java 8u275 and later

### PR DESCRIPTION
**Pull request by maytasm**
Fix hostname validation not skipping with `druid.client.https.validateHostnames=false` in java 8u275 and later

### Description

Hostname validation is not skipped even after setting `druid.client.https.validateHostnames=false` in java 8u275 and later. This is due to code change introduced in Java 8u275. To disable validate hostnames, Druid sets the endpointIdentificationAlgorithm of the SSLParameters in the SSLEngine to null (using the SSLEngine#setSSLParameters method). This is done in CustomCheckX509TrustManager#checkServerTrusted. In 8u242, the SSLEngine#setSSLParameters (https://github.com/openjdk/jdk8u/blob/b996dbe72ce338fdc430fbba1bb995ce622109e3/jdk/src/share/classes/sun/security/ssl/SSLEngineImpl.java#L2102 ) simply get the new endpointIdentificationAlgorithm from the given input SSLParameters (params) and set it without any verification of the new endpointIdentificationAlgorithm value. In 8u275,  the SSLEngine#setSSLParameters (https://github.com/openjdk/jdk8u/blob/37d4863386fb7fccb846f46b1bc85b4c61fe1c88/jdk/src/share/classes/sun/security/ssl/SSLEngineImpl.java#L763 ) calls TransportContext#SSLConfiguration#setSSLParameters (https://github.com/openjdk/jdk8u/blob/37d4863386fb7fccb846f46b1bc85b4c61fe1c88/jdk/src/share/classes/sun/security/ssl/SSLConfiguration.java#L199 ). This method will not set endpointIdentificationAlgorithm to the new value if the new value is null (https://github.com/openjdk/jdk8u/blob/37d4863386fb7fccb846f46b1bc85b4c61fe1c88/jdk/src/share/classes/sun/security/ssl/SSLConfiguration.java#L231 ). Hence, the endpointIdentificationAlgorithm would remains as HTTPS and trigger validate hostnames in X509TrustManagerImpl. The code that determines to validate hostname or not in X509TrustManagerImpl is actually the pre and post 8u275, which is to validate hostname if the identityAlg != null && identityAlg.length() != 0 (note that identityAlg variable is the EndpointIdentificationAlgorithm of the SSLParameters).

As a workaround, we can set EndpointIdentificationAlgorithm to an empty String instead. This will still cause the hostname validation to be skipped.

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by jon-wei — APPROVED** [review]
I was curious why our integration tests failed to catch this before and looked into that, we don't have coverage for the case where a Druid client talks to a Druid server that has an invalid hostname with hostname validation disabled.

I was able to run that case with the following patch that makes the server certs have invalid hostnames, with hostname validation disabled for both client/server:

```
diff --git a/integration-tests/docker/environment-configs/common b/integration-tests/docker/environment-configs/common
index 2ded3965bb..dcf41dec61 100644
--- a/integration-tests/docker/environment-configs/common
+++ b/integration-tests/docker/environment-configs/common
@@ -61,7 +61,7 @@ druid_server_https_requireClientCertificate=true
 druid_server_https_trustStoreAlgorithm=PKIX
 druid_server_https_trustStorePassword=druid123
 druid_server_https_trustStorePath=/tls/truststore.jks
-druid_server_https_validateHostnames=true
+druid_server_https_validateHostnames=false
 druid_zk_service_host=druid-zookeeper-kafka
 druid_auth_basic_common_maxSyncRetries=20
 druid_indexer_logs_directory=/shared/tasklogs
@@ -76,3 +76,5 @@ druid_coordinator_period_metadataStoreManagementPeriod=PT10S
 # Testing the legacy config from https://github.com/apache/druid/pull/10267
 # Can remove this when the flag is no longer needed
 druid_indexer_task_ignoreTimestampSpecForDruidInputSource=true
+
+druid_client_https_validateHostnames=false
diff --git a/integration-tests/docker/tls/generate-server-certs-and-keystores.sh b/integration-tests/docker/tls/generate-server-certs-and-keystores.sh
index 931b6e4752..eef5d8cbef 100755
--- a/integration-tests/docker/tls/generate-server-certs-and-keystores.sh
+++ b/integration-tests/docker/tls/generate-server-certs-and-keystores.sh
@@ -55,7 +55,7 @@ basicConstraints=CA:FALSE,pathlen:0
 IP.1 = ${DOCKER_IP}
 IP.2 = ${MY_IP}
 IP.3 = 127.0.0.1
-DNS.1 = ${MY_HOSTNAME}
+DNS.1 = badhostname${MY_HOSTNAME}
 DNS.2 = localhost
 
 EOT
```

The tests fail due to service startup errors from the invalid hostname without this PR (they're not able to pull auth info from the coordinator), and pass with the PR, running with JDK8 282 in the Druid containers (aside from `ITTLSTest.checkAccessWithWrongHostname` which is expected since that tests that hostname validation is working).

It would be a good follow-on to add that coverage into the integration tests, but I don't think it's a blocker for merging this since I think we'd likely need to put some thought into the number of service containers we're creating in the integration tests to cover this (and we can ignore the test coverage failure in the server module, IMO, for this kind of change I think the integration tests with real TLS interactions are most useful).

**Comment by maytasm** [comment]
@jon-wei Thank you so much for reviewing and verifying with the IT. I can look into adding the new IT you suggested but this will require a separate job since we need a different cluster config. This will adds a bit of time to the build pipeline. Btw, I think our IT runs on container with Java OpenJdk 1.8.0_292. You mentioned that you tested with 282, is this a typo or did you had to change the version on the existing IT containers?

**Comment by maytasm** [comment]
@jon-wei I have added unit test to verify this fix. The unit test verify that CustomCheckX509TrustManager does set the EndpointIdentificationAlgorithm to null or empty String when validateServerHostnames is set to false. The disadvange to the unit test is that we do not / can not control the specific version of OpenJdk8 that Travis uses to run the unit test. Currently Travis uses openjdk version "1.8.0_252". Hence, the unit test ran in Travis actually does not verify the bug caused by Java 8u275+. The advantages are that 1) the unit test adds very very little additional runtime to the pipeline 2) the unit test ensure that no regression in Java version that is used by Travis tests (which are openjdk version "1.8.0_252", some version of 11 and some version of 15 -- got to lazy to check the specific version) and 3) You can still run the unit test locally against any Java version by changing your IDE Java version, which I did against 8u275 to verify that the fix works. (I also build Druid and run the cluster with 8u275 to verify the fix). Anyway, having unit test is better than no unit test :)

**Comment by jon-wei** [comment]
> This will adds a bit of time to the build pipeline. Btw, I think our IT runs on container with Java OpenJdk 1.8.0_292. You mentioned that you tested with 282, is this a typo or did you had to change the version on the existing IT containers?

I ran it in my local environment, I checked that it was 282, maybe it was using an older image there

**Comment by maytasm** [comment]
Merging this in. The only job failing is due to code coverage on 1.8.0_252. The new code will only be hit when running in Java version 8u275 or later.

**Pull request merged**
