### PR TITLE
Add `examples/` to CI UT/IT ignore

### PR DESCRIPTION
**Pull request by abhishekrb19**
Skip Java UTs and ITs when there are changes to `examples` folder which contain the quickstart tutorials. Also, sort the  ignored paths.
This PR has:
- [x] been self-reviewed.

### CODE REVIEW

**Comment by abhishekrb19** [comment]
I think GHA is running all the CI checks because of the change to workflow file. I can't think of a way to test this change besides verifying it later in a follow on test PR once this PR is merged to master. The test commit has now been reverted

**Review by clintropolis — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
This shouldn’t have been merged. ITs use files in examples directory which
is why we don’t skip ITs when there are changes in examples folder.

**Comment by clintropolis** [comment]
>This shouldn’t have been merged. ITs use files in examples directory which is why we don’t skip ITs when there are changes in examples folder.

I guess I assumed that any changes there with test implications would also have changes to java files, though if that's not true we can revert this

**Comment by abhishekrb19** [comment]
@abhishekagarwal87 what part of the Java UTs and ITs rely on the example QuickStart stuff? Do we need some restructuring?

**Comment by abhishekagarwal87** [comment]
@abhishekrb19 - you will find various examples if you search for `examples` in the integration-test module. The examples are not changed frequently so it's just best to not skip them altogether. can you revert this change?

**Pull request merged**
