### PR TITLE
remove unecessarily strict check on partitioning type

### PR DESCRIPTION
**Pull request by michaelschiff**
Index task enforcement of PartitionSpec is overly strict with respect to choice of rollup guarantee.  If forceGuaranteeRollup is  disabled, any PartitionSpec should be allowed.  In the case that 'forceGuaranteeRollup' is enabled we still need to enforce that the PartitionSpec can support this guarantee. 

This PR removes the requirement that the user pick dynamic PartitionSpec when forceGuaranteedRollup is false

This PR has:

- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by kfaraz — COMMENTED** [review]
Why do we want to disable this check, @michaelschiff ? If users get back a well-formed error, they can resubmit a modified task spec.
I think there are many places in the code which assume that when we are using `hashed` or `range`, `forceGuaranteedRollup` must be true. Breaking that assumption might cause erratic behaviour in some cases.

So what should we do if the user has set `forceGuaranteedRollup = false` and partitioning to say `hashed`?
1. We can just ignore `forceGuaranteedRollup`. This requires fixing the assumptions in all the other places in the code.
2. We can reset `forceGuaranteedRollup = true` in the code and proceed with that. This seems preferable but essentially there are two user-specified configs which are competing here. The given value of `forceGuaranteedRollup` and `partitioningType`. So if we decide that `partitioningType` takes precedence, we must call it out clearly in the docs and give a warning message to the user too.
3. We can continue to throw the error so that users know exactly what they are going to get.

**Comment by michaelschiff** [comment]
> I think there are many places in the code which assume that when we are using hashed or range, forceGuaranteedRollup must be true. Breaking that assumption might cause erratic behaviour in some cases.

I wasn't aware of this assumption elsewhere, but if thats the case then I think those places should probably change - so I'd go with your option 1

It seems reasonable to me that there are use-cases where its desirable to retain un-aggregated data in druid, but where you would still want to take advantage of the performance improvements that come from hash/range based partitioning.  The "no rollup" use-case is also described in the docs https://druid.apache.org/docs/latest/ingestion/rollup/#:~:text=When%20you%20disable%20rollup%2C%20Druid,is%2C%20without%20any%20rollup%20summarization and it seems weird that you can disable rollup, but that if you then want to re-organize your partitioning you're not able

**Comment by kfaraz** [comment]
> I wasn't aware of this assumption elsewhere, but if thats the case then I think those places should probably change - so I'd go with a slight modification of your option 1 - all partitioning modes should respect the value of forceGuaranteedRollup if it they can (i.e. its still an error to ask for guaranteed rollup and dynamic partitioning, but otherwise we can respect the user's preference)

I think there is some confusion here because of the two flags:
- The flag [`rollup`](https://druid.apache.org/docs/latest/ingestion/ingestion-spec#granularityspec) in `granularitySpec` (default is `true`) is used to control whether we want to rollup data or not.
- The flag [`forceGuaranteedRollup`](https://druid.apache.org/docs/latest/ingestion/native-batch-simple-task#tuningconfig) in `tuningConfig` (default is `false`) controls the type of rollup i.e. perfect or best-effort.
- `hashed` and `range` partitioning _always_ perform perfect rollup (if `rollup` is enabled), same way as `dynamic` never does.
- So while using `range` or `hashed`, `forceGuaranteedRollup` has to be `true`, because they always give perfect rollup. Thus the options are to either (a) ignore the value of `forceGuaranteedRollup` and use perfect rollup _only_ if the user has asked for rollup, or (b) throw an error.
- Users can still choose to have data that is not rolled up by simply setting `rollup` to `false`.

Screenshot 2023-08-31 at 8 41 14 AM

I think we should update the docs to clarify that for Native batch, the _kind_ of rollup we get depends on the partitioning type.

**Comment by michaelschiff** [comment]
Ah you're right - I was confused.  But it does now seem to me that `forceGuaranteedRollup` is redundant. If I understand correctly, its value is entirely determined by the choice of partitioning scheme.  Could we simplify things and remove this option?

**Pull request closed without merging**
