### PR TITLE
Fix aggregation filter expression processing in the absense of projection

### PR DESCRIPTION
**Pull request by kgyrtkirk**
After #14510 some queries become unplannable; like:

```sql
select count(1) filter (where __time > date '2023-01-01')
from druid.foo where 'a' = 'b'
```

The reason behind it was that the initial plan of
```
LogicalAggregate(group=[{}], EXPR$0=[COUNT() FILTER $0])
  LogicalProject($f1=[>($0, 2023-01-01 00:00:00)])
    LogicalFilter(condition=[=('a', 'b')])
      LogicalTableScan(table=[[druid, foo]])
```
was simplified by  some `RelBuilder` usage and `PruneEmptyRules.PROJECT_INSTANCE` into
```
LogicalAggregate(group=[{}], EXPR$0=[COUNT() FILTER $0])
  LogicalValues(tuples=[[]]) 
```

which become unplannable because the `FILTER` clause processing put a hard constraint on the existence of a `Project` in the actual plan [here](https://github.com/apache/druid/blob/92906059d2997a6902eac03b2a5198e5164043df/sql/src/main/java/org/apache/druid/sql/calcite/rule/GroupByRules.java#L78)

Proposed solution is to use `Expressions.fromFieldAccess` to optionally use the `project` - or use a direct field access that's absent.

This PR has:

- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
it's a bit weird that we were not doing this already. Though the change makes sense to me so I am approving it.

**Comment by kgyrtkirk** [comment]
Thank you for reviewing the changes :)
the original bail-out goes back [beyond 2018](https://github.com/apache/druid/blob/431d3d8497f9079857c3baa7ae7ab4cb44a22355/sql/src/main/java/org/apache/druid/sql/calcite/rule/GroupByRules.java#L70) - so it was handled like this for historical reasons :cowboy_hat_face:

**Review by soumyava — APPROVED** [review]
Checked out and ran a bunch of queries too. LGTM. Thanks for the fix.

**Comment by kgyrtkirk** [comment]
Thank you Somu and Abhishek for reviewing these changes!

**Pull request merged**
