### PR TITLE
Docs: move search to the left

### PR DESCRIPTION
**Pull request by vogievetsky**
Put the doc search on the left of all the links

image

### CODE REVIEW

**Comment by fjy** [comment]
Vadim, can we move the search into the ToC and out of the nav bar?

**Comment by fjy** [comment]
It feels so out of place and hard to find in the nav bar

**Comment by ccaominh** [comment]
The security vulnerabilities travis job failure is unrelated to this PR. Please merge master to get the fix: https://github.com/apache/druid/pull/9189

**Comment by fjy** [comment]
@vogievetsky I think it is extremely hard to find the doc search bar and we should try to put it somewhere else. Can we have a sub-header bar or something?

**Pull request closed without merging**
