### PR TITLE
Web console: Estimate rollup ratio for a datasource

### PR DESCRIPTION
**Pull request by renevan10**
This PR adds a dialog to preview and estimate rollup of a datasource under the datasources section. The top 20 rows of the datasource will be previewed. The user may get the estimated rollup ratio by:

- changing the interval of the data, 
- selecting columns to exclude for the rollup(which will highlight the entire column in grey)
- changing the granularity

If the ingested data was previously rolled up, the original rollup ratio will also be displayed. 

image

Note that you must leave at least one column de-selected for the calculation.

### CODE REVIEW

**Comment by fjy** [comment]
@renevan10 this supporting arbitrarily selecting multiple columns to exclude right?

**Comment by renevan10** [comment]
@fjy yes! You can select multiple columns.

**Comment by fjy** [comment]
@renevan10 @vogievetsky does the algorithm only look at the first 20 rolls? I don't think that is going to accurately estimate the rollup ratio

**Comment by renevan10** [comment]
@fjy No it will calculate the ratio for the entire datasource based on the interval, the first 20 rows is just to serve as a preview for the user to look at.

**Comment by fjy** [comment]
> @fjy No it will calculate the ratio for the entire datasource based on the interval, the first 20 rows is just to serve as a preview for the user to look at.

What happens if the interval covers a lot of data?

**Comment by vogievetsky** [comment]
I think you are missing a snapshot test here

**Comment by vogievetsky** [comment]
@fjy I think if there is a lot of data for the selected interval then the tool will be slow. It should probably mention it in the blurb

**Comment by fjy** [comment]
> @fjy I think if there is a lot of data for the selected interval then the tool will be slow. It should probably mention it in the blurb

Uh... it seems like we should think about this more.

**Comment by vogievetsky** [comment]
@fjy  what do you mean?

**Comment by vogievetsky** [comment]
FYI this view is powered by a `cardinality(byRow)` query. There should be some tweaks around making the slow state work nice and also around setting good priorities and timeouts - so more UI work. But the idea is solid.

**Pull request closed without merging**
