### PR TITLE
Improve doc of movingAverage

### PR DESCRIPTION
**Pull request by FrankChen021**
### Description

There're some questions about how to enable movingAverage on brokers(eg #11086), this PR improves the doc to make operational steps more directive and also adds a limitation that movingAverage is not supported  by druid router.

This PR has:
- [X] been self-reviewed.

### CODE REVIEW

**Review by asdf2014 — APPROVED** [review]
:+1:

**Comment by bananaaggle** [comment]
> ### Description
> There're some questions about how to enable movingAverage on brokers(eg #11086), this PR improves the doc to make operational steps more directive and also adds a limitation that movingAverage is not supported by druid router.
> 
> This PR has:
> 
> * [x]  been self-reviewed.

Actually, add  binder.bind(c.class).to(FakeQuerySegmentWalker.class).in(LazySingleton.class)  to  CliRouter.java, user can query movingAverage through router. One line code can break this limit, but it is not very graceful because router not use QuerySegmentWalker.class.

**Comment by bananaaggle** [comment]
> ### Description
> There're some questions about how to enable movingAverage on brokers(eg #11086), this PR improves the doc to make operational steps more directive and also adds a limitation that movingAverage is not supported by druid router.
> 
> This PR has:
> 
> * [x]  been self-reviewed.

Actually, add  binder.bind(c.class).to(FakeQuerySegmentWalker.class).in(LazySingleton.class)  to  CliRouter.java, users can query movingAverage through router. One line code can break this limit, but it is not very graceful because router not use QuerySegmentWalker.class.

**Comment by FrankChen021** [comment]
> > ### Description
> > There're some questions about how to enable movingAverage on brokers(eg #11086), this PR improves the doc to make operational steps more directive and also adds a limitation that movingAverage is not supported by druid router.
> > This PR has:
> > 
> > * [x]   been self-reviewed.
> 
> Actually, add binder.bind(c.class).to(FakeQuerySegmentWalker.class).in(LazySingleton.class) to CliRouter.java, users can query movingAverage through router. One line code can break this limit, but it is not very graceful because router not use QuerySegmentWalker.class.

Thanks for pointing out this. Yes, we need to make some code change to support moving average running from router. This is not what this PR aims for. I'm planning to do it later or if you're interested in this feature, you could take it.

**Comment by bananaaggle** [comment]
> > > ### Description
> > > There're some questions about how to enable movingAverage on brokers(eg #11086), this PR improves the doc to make operational steps more directive and also adds a limitation that movingAverage is not supported by druid router.
> > > This PR has:
> > > 
> > > * [x]    been self-reviewed.
> > 
> > 
> > Actually, add binder.bind(c.class).to(FakeQuerySegmentWalker.class).in(LazySingleton.class) to CliRouter.java, users can query movingAverage through router. One line code can break this limit, but it is not very graceful because router not use QuerySegmentWalker.class.
> 
> Thanks for pointing out this. Yes, we need to make some code change to support moving average running from router. This is not what this PR aims for. I'm planning to do it later or if you're interested in this feature, you could take it.

Last June I do this adjust on my cluster for using moving average for analysts. It works, but not graceful. Do you think it is a suitable idea to solve this problem? If you think it's OK, I can test it on master branch and open PR. It's very easy and I'm glad to do this.

**Review by suneet-s — APPROVED** [review]

**Comment by suneet-s** [comment]
Travis seems to be failing on spellcheck for `pull-deps` and I can't figure out why, it seems like this is used in other files without a problem. 🤔

**Comment by FrankChen021** [comment]
> Travis seems to be failing on spellcheck for `pull-deps` and I can't figure out why, it seems like this is used in other files without a problem. 🤔

Sorry, I forgot the CI. A suppression rule has been added to the `.spelling` file, and now let's wait to see the result of CI.

**Comment by clintropolis** [comment]
>Travis seems to be failing on spellcheck for pull-deps and I can't figure out why, it seems like this is used in other files without a problem. 🤔

The .spelling file is sort of funny, the top of the file is like global suppressions, then below that there are page specific suppressions, which I'm not quite certain why they need to exist (do we need some things to be spelling errors on some pages but not on others), but explains why it was failing here, since pull-deps is suppressed in `docs/development/extensions.md` and `docs/development/extensions-contrib/redis-cache.md` (funny enough not in `docs/operations/pull-deps.md` which always refers to it with back ticks)

**Comment by suneet-s** [comment]
> > Travis seems to be failing on spellcheck for pull-deps and I can't figure out why, it seems like this is used in other files without a problem. 🤔
> 
> The .spelling file is sort of funny, the top of the file is like global suppressions, then below that there are page specific suppressions, which I'm not quite certain why they need to exist (do we need some things to be spelling errors on some pages but not on others), but explains why it was failing here, since pull-deps is suppressed in `docs/development/extensions.md` and `docs/development/extensions-contrib/redis-cache.md` (funny enough not in `docs/operations/pull-deps.md` which always refers to it with back ticks)

HA! that explains it. I don't think we need to make `pull-deps` a global suppression in this PR, so this change is good to go as is for me, although I wouldn't be opposed to a global `pull-deps` suppression either. @FrankChen021 I'll leave it to you to press the merge button for when you're happy with the change

**Pull request merged**
