### PR TITLE
Docs: Add hadoop based multi-dimension partitioning doc

### PR DESCRIPTION
**Pull request by hqx871**
### Description

Add hadoop based multi-dimension partitioning doc.

#### Release note

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by kfaraz** [comment]
Thanks for the changes, @hqx871 .
It seems that the added lines have been copied over from the doc on native batch ingestion [here](https://github.com/apache/druid/blob/master/docs/ingestion/native-batch.md#multi-dimension-range-partitioning). It would be better to just add a reference to that content rather than copying the same information.

Since range partitioning is now supported with both hadoop and native batch, it would even make sense to pull out the descriptions of various kinds of secondary partitioning (hash, range and dynamic) into the partitioning doc (`partitioning.md`) itself and just add references to these in `native-ingestion.md` and `hadoop-ingestion.md` docs.
@techdocsmith , @317brian , what do you think?

**Comment by techdocsmith** [comment]
:+1: for @kfaraz comment. Description of partitioning types would be better suited for https://github.com/apache/druid/blob/master/docs/ingestion/partitioning.md . With links out from native batch and from hadoop indexing.

**Review by kfaraz — CHANGES_REQUESTED** [review]
@hqx871 , we would need to do the following:
- move all partitioning definitions to partitioning.md
- reference these definitions from Hadoop and native ingestion docs

Would you be willing to update this PR to have these changes instead?

**Comment by hqx871** [comment]
> @hqx871 , we would need to do the following:
> 
> * move all partitioning definitions to partitioning.md
> * reference these definitions from Hadoop and native ingestion docs
> 
> Would you be willing to update this PR to have these changes instead?

Hi @kfaraz, I am afraid I can't. I know few about the native batch ingestion and when I try to read it's doc, I found there are some difference between native and hadoop-based. May some else can do it better.

**Comment by kfaraz** [comment]
Sounds good, @hqx871 , I will try to create a PR for the changes then.

**Comment by kfaraz** [comment]
Closing this PR as we would have to create a separate one that addresses this:
https://github.com/apache/druid/pull/13850#pullrequestreview-1317397663

**Pull request closed without merging**
