### PR TITLE
Add @VisibleForTesting annotation for the backingArray() method

### PR DESCRIPTION
**Pull request by asdf2014**
### Description

It would be better to annotate the `backingArray()` method in the `TournamentTree` class with `@VisibleForTesting` as this method only be used by unit tests to enhance the maintainability.

#### Release note

This PR has:

- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] a release note entry in the PR description.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by gianm — APPROVED** [review]

**Comment by gianm** [comment]
Sounds good to me!

**Comment by gianm** [comment]
Sounds good to me!

**Comment by LakshSingla** [comment]
Removing it from the milestone, since it isn't adding a new functionality or fixing any bugs. @asdf2014 LMK if you feel otherwise, and I will backport it.

**Comment by asdf2014** [comment]
@LakshSingla Oh, I see. That's okay, it is not big deal. IMO, we could build up more efficient channel via Mergify instead of creating these [[Backport]](https://github.com/apache/druid/pulls?q=is%3Apr+%5BBackport%5D+is%3Aclosed) PRs manually. FYI, https://github.com/apache/druid/issues/8545 :smile:

**Pull request merged**
