### PR TITLE
Enable query request queuing by default when total laning is turned on.

### PR DESCRIPTION
**Pull request by abhishekagarwal87**
This PR enables the flag by default to queue excess query requests in the jetty queue. Still keeping the flag so that it can be turned off if necessary. But the flag will be removed in the future. 

Release notes
- When query scheduler threads are less than server HTTP threads, total laning becomes on. This lets reserve some HTTP threads for non-query requests such as health checks. The total laning previously would reject any query request that exceeds the lane capacity. But now, those excess requests will instead be queued with a timeout equal to `MIN(Integer.MAX_VALUE, druid.server.http.maxQueryTimeout`)

if value of `druid.server.http.maxQueryTimeout` is negative, then the excess requests will be queued forever. 

This PR has:

- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by LakshSingla — APPROVED** [review]

**Comment by LakshSingla** [comment]
Perhaps we should point it out in the developer release notes in the next release.

**Comment by gianm** [comment]
The docs for `druid.query.scheduler.numThreads` should be updated too, as the out of box config will no longer result in HTTP 429 when the scheduler limit is exceeded.

**Comment by abhishekagarwal87** [comment]
Updated the docs.

**Comment by maytasm** [comment]
Is this doc incorrect https://github.com/apache/druid/blob/master/docs/configuration/index.md?plain=1#L1777
It says "Requests in excess of the capacity are discarded with an HTTP 429 status code."

**Comment by abhishekagarwal87** [comment]
No. It's correct. This PR queues requests when the total lane is at capacity but any other lane will still see the excess request being rejected.

**Comment by maytasm** [comment]
> No. It's correct. This PR queues requests when the total lane is at capacity but any other lane will still see the excess request being rejected.

What does "total lane" and "other lane" means?

**Pull request merged**
