### PR TITLE
Change the `id` for `kubernetes` doc link to work

### LINKED ISSUE #11175: 404 Not Found for Kubernetes Extension Docs `0.21.0`
Hello
@jihoonson , @himanshug 

- Getting 404 Not found error for Kubernetes Extension docs.
- Link got from release notes (https://github.com/apache/druid/releases/tag/druid-0.21.0)
- Also I cannot see extension in https://druid.apache.org/docs/latest/development/extensions.html
https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html

Thank you

### PR DESCRIPTION
**Pull request by jp707049**
Fixes #11175

Currently the doc link is not working because the `id` in kubernetes.md is `druid-kubernetes`
In this PR, changed the `id` to `kubernetes` to be more inline with other extensions naming conventions and for https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html link to work. 

This PR has:
- [x] been self-reviewed.

### CODE REVIEW

**Comment by jp707049** [comment]
FYI @jihoonson

**Comment by jihoonson** [comment]
Nice catch! Could you please add a link to the extension in https://github.com/apache/druid/blob/master/docs/development/extensions.md as well? It can go at last of the core extensions.

**Comment by jp707049** [comment]
Done

**Review by jihoonson — APPROVED** [review]
Thanks a lot! I will backport this fix to the 0.21.0 branch once it is merged after the doc CI passes.

**Comment by jp707049** [comment]
Why build is failing?

**Comment by suneet-s** [comment]
I've re-triggered what appears to be flaky tests

**Comment by jihoonson** [comment]
@jp707049 some of our tests are flaky unfortunately. The CI passed in the second attempt. Thanks!

**Pull request merged**
