### PR TITLE
Support rolling log files

### LINKED ISSUE #10127: Housekeeping Druid log files
Is there a preferred approach in housekeeping Druid service log files in a production implementation.

Over the period of time, the logs become too large in size causing space issues in server. Simply deleting the logfiles does not seem to resolve the problem, as the process ids of delete command is still running in background

### PR DESCRIPTION
**Pull request by FrankChen021**
This PR fixes #10127 

### Description

Druid(including ZooKeeper launched by Druid's script) outputs logs to log files through redirection of standard console output, in which way after a long time running, the log files can be very large, up to tens or hundreds of GB in size.  This introduces extra work for users to clean or roll those log files to save disk space.

Since log4j2 is used by Druid to record logs, it's better to take advantage of log4j2's file appender to save log in files directly and roll log files as a default way. 

This PR
1.  fixes the startup scripts to pass down two variables as system properties to Druid or ZooKeeper process so that log4j.xml knows where to save log files and how to name the log files
2. replaces the console appender in the default log4j2.xml configuration files with `RollingRandomAccessFile` to roll log files and remove expired log files
3. modify the supervisor script(indirectly called by start-xxx scripts) to stop redirect sub-processes' console log to file since there're no console log by default

With the these changes , we also provide an easy way for user
1.  to config (through environment variable `DRUID_LOG_DIR`) where to save the log files 
2.  to change how long they want to keep log files (in log4j2.xml)

<hr>

This PR has:
- [X] been self-reviewed.
- [X] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
Oh, I almost forgot this PR. It's been a long time awaiting for review. Could someone review it please ? @clintropolis @asdf2014 @jihoonson @suneet-s

**Comment by FrankChen021** [comment]
The branch has been rebased onto the lastest master to resolve some conflicts. And I highly recommend to merge this PR to the master because we suffer this problem every time when we download a new  druid version to setup a new cluster.

**Comment by Gabriel39** [comment]
It's a meaningful feature and I think you need approval from PMC. Cc @jihoonson

**Comment by kailiu6** [comment]
@FrankChen021  use this  commit: https://github.com/apache/druid/pull/10147/commits/3949d884b03b0b89ed978c75ef3b8d8cb474c30b    
it take effect  and can split log  , but i find a problem,  the log writes log to today log and last day log at the same time；
for example: 
-rw-rw-r--+ 12:10 /opt/log/druid_new/middleManager-2021-06-27.log
-rw-rw-r--+ 12:10 /opt/log/druid_new/middleManager.log      
Can you find some problems？ thank you.

**Review by abhishekagarwal87 — APPROVED** [review]
LGTM. btw did you test this locally with a distribution? Just to rule out any unexpected effect.

**Comment by FrankChen021** [comment]
@kailiu6 Are you running Druid in Docker ?

**Comment by FrankChen021** [comment]
> LGTM. btw did you test this locally with a distribution? Just to rule out any unexpected effect.

Yes, I built a distribution and tested this change on my local environment.

**Comment by kailiu6** [comment]
@FrankChen021  Hi,   thanks for your replay，  I’m not in docker,  by maybe it's my problem .  I find me  lost a step:
nohup $JAVA -Ddruid.node.type=$nodeType -Ddruid.log.path=$LOG_DIR `cat $CONF_DIR/$nodeType/jvm.config | xargs` -cp $CONF_DIR/_common:$CONF_DIR/$nodeType:$LIB_DIR/*:$HADOOP_CONF_DIR org.apache.druid.cli.Main server $nodeType >> /dev/null 2>&1 &

I have changed old code  to above  and  is testing

this is my log4j configuration:
 <RollingFile  name="RollingFileInfo" fileName="${sys:druid.log.path}/${sys:druid.node.type}.log"
                      filePattern="${sys:druid.log.path}/${sys:druid.node.type}-%d{yyyyMMddHH}.log">
            <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
            </Policies>
            <DefaultRolloverStrategy>
                <Delete basePath="${sys:druid.log.path}" maxDepth="1">
                    <IfFileName glob="${sys:druid.node.type}*.log" />
                    <IfLastModified age="3d" />
                </Delete>
            </DefaultRolloverStrategy>
    </RollingFile>

**Comment by FrankChen021** [comment]
@kailiu6 Yeah, the `nohup` command should redirect console output to /dev/null instead of a file.

**Comment by kailiu6** [comment]
hi， @FrankChen021 ，  I have tested ok and no repeat write now. But  I found a  new problem that  the start failed message will not wirte to  ${sys:druid.log.path}/${sys:druid.node.type}.log.  The reason I find that may  be  “/dev/null 2>&1 &”。 So  if I  no set “/dev/null” and it will writes repeat， but if I set and the start failed message will not wirte.

**Comment by FrankChen021** [comment]
@kailiu6 What does the 'start failed message' show ?

**Comment by kailiu6** [comment]
> @kailiu6 What does the 'start failed message' show ?

for example： if start coordinator faied beause of lost a jar ,  if not use “/dev/null 2>&1 &” , the message of "Error: Could not find or load main class org.apache.druid.cli.Main"  will  write  to coordinator.log, but now will not write to coordinator.log。

you can reproduce this problem by  this step:
1) mv  lib lib_bak
2)./bin/coordinator.sh start

**Comment by FrankChen021** [comment]
@kailiu6 I see. You're using the node.sh to start the Druid process instead of using the supervise, which uses the run-druid.sh to start Druid. You could redirect the the stderr to a file like this:

```bash
nohup $JAVA -Ddruid.node.type=$nodeType -Ddruid.log.path=$LOG_DIR `cat $CONF_DIR/$nodeType/jvm.config | xargs` -cp $CONF_DIR/_common:$CONF_DIR/$nodeType:$LIB_DIR/*:$HADOOP_CONF_DIR org.apache.druid.cli.Main server $nodeType > $LOG_DIR/$nodeType-console.log  2>&1 &
```

The stdout and stderr will be both redirected into a file like coordinator-console.log under `DRUID_LOG_DIR` which defaults to 'log'.

If Druid processes run normally, there will be two log files: one is xxx-console.log, and another one is xxx.log.

If your log4j2.xml configures no console output, these two log files are different.

**Review by smit-aterlo — APPROVED** [review]

**Comment by FrankChen021** [comment]
@suneet-s I will do it in this weekend and resolve some comments mentioned above.

**Comment by FrankChen021** [comment]
I made some improvments and now I think it's ready for the final review. @suneet-s @clintropolis

**Comment by suneet-s** [comment]
I've re-triggered the flaky tests 🤞 it passes this time!

**Comment by smit-aterlo** [comment]
@FrankChen021 can you please merge this branch so that we can get this in the next release? Thank you

**Comment by FrankChen021** [comment]
@suneet-s @clintropolis Do you have any other comments?

**Comment by smit-aterlo** [comment]
@FrankChen021 Any update on this? Thank you

**Comment by clintropolis** [comment]
this PR breaks standalone task logs that get pushed to deep storage in the "out of the box" configuration. Adding a `log4j2.xml` file in the middle manager conf directory resolves the issue, but the middle-managers own logs no longer end up redirected to the file, which is ugly when running the quickstart configs. I'm not sure the best way to resolve this, since i guess only the middle manager should be redirecting console output to the log file, since the others are controlled by log4j2.xml.

**Comment by FrankChen021** [comment]
@clintropolis Thank you for your information. Let me take a look later this week. If you think this might be a blocker or something that is not mature, it's OK to revert it.

**Comment by FrankChen021** [comment]
@clintropolis the problem is that middle manager redirects the output of a task into a task log file, so for tasks, they must output the log to the console. Since peon tasks also can find the `log4j2.xml` under the `_common` directory, and they derivate system properties from the parent process (middle manager), so all logs are written the log middle manager's log.


There're two alternatives for us:
1. put another log4j2 configuration file, say `log4j2_task.xml`, which contains the console appender configuration, under the _common directory, and we put `-Dlog4j2.configurationFile=log4j2_task.xml` to `druid.indexer.runner.javaOpts` property.

    For this alternative, users can still edit the log4j2_task.xml or delete the required argument from `druid.indexer.runner.javaOpts`, which will lead to the failure of task log mechanism.

2. Implements a customer log4j2 `ConfigurationFactory` class in the task module, this class override the default configuration from the `log4j2.xml`, and override the appenders to ConsoleAppender. Also, middle manager should pass a `-Dlog4j2.configurationFactory=THIS_CUSTOMER_CLASS_NAME` to the task process.

    For this alternative, it forces the peon tasks to use a console log appender even if the user provides a wrong configuration file. 

I prefer the latter one, because it's more reliable that users can't break the task log mechanism.

**Comment by gianm** [comment]
We should mention this in 0.23.0 release notes, because it means that anyone that is using the `supervise` program and has pre-existing log4j2.xml files doing console logging should switch to file-based logging. Otherwise, all the logs will appear jumbled up in the `supervise` output. In the notes we could suggest using the ones shipped in the new distribution as an example.

cc @abhishekagarwal87

**Pull request merged**
