### PR TITLE
Update druid.indexer.storage.type default value in documentation

### PR DESCRIPTION
**Pull request by OliveBZH**
The `druid.indexer.storage.type` default value in the doc is wrong, by default it is not `local`but `metadata`

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
I can see it being set to local in the code. Where do you see `metadata` being set by default?

**Comment by OliveBZH** [comment]
didn't check in the code but in the docker image the `runtime.properties` has that : `druid.indexer.storage.type=metadata`

**Comment by cryptoe** [comment]
@OliveBZH Its `metadata` by default. I am closing this PR since there is nothing to do here. Thanks for taking interest in the druid project.

**Comment by OliveBZH** [comment]
Hello @cryptoe, thanks for your update. I just want to understand why we see `druid.indexer.storage.type=metadata` in the `runtime.properties` in the original druid image without any modification ?

**Pull request closed without merging**
