### PR TITLE
Update ambari-metrics-common to version 2.6.1.0.0 

### PR DESCRIPTION
**Pull request by nishantmonu51**
prev version is available in only hortonworks repo. 
This PR upgrades to ambari-metrics-common 2.6.1.0.0 and also remove dependency on hortonworks repo

### CODE REVIEW

**Comment by pjain1** [comment]
travis is failing because of code coverage issues, its complaining about the code in getters not being covered which does not make much sense to me.

**Comment by nishantmonu51** [comment]
@pjain1 : added test that would address code coverage

**Comment by nishantmonu51** [comment]
@pjain1 : the base build is failing due to broken hortonworks repo. This should be good to be merged now.

**Comment by jihoonson** [comment]
I restarted the failed LGTM analysis. It won't take long, please wait for the CI to pass. I understand the transient CI failure is annoying, but it often finds legit issues so it would be better to fix the issue in the PR if any rather than making the master branch fail.

**Pull request merged**
