### PR TITLE
DruidViewMacro: Remove unused escalator field.

### PR DESCRIPTION
**Pull request by gianm**
It isn't used.

### CODE REVIEW

**Comment by kfaraz** [comment]
Should `DruidViewMacroFactory` also be updated to remove the `escalator` argument?

**Comment by gianm** [comment]
@kfaraz Good point; I removed that as well.

**Review by kfaraz — APPROVED** [review]
LGTM

**Review by clintropolis — APPROVED** [review]
:+1: this was my bad, i forgot to remove in #10812

**Pull request merged**
