### PR TITLE
Add handoff wait time to IngestionStatsAndErrorsTaskReportData

### PR DESCRIPTION
**Pull request by capistrant**
### Description

Follow on to #10676. 

The main change is adding `segmentAvailabilityWaitTimeMs` to `IngestionStatsAndErrorsTaskReportData`. This is the milliseconds that a task waited for its segments to be handed off to Historical nodes. If there is no wait for handoff, the value is simply 0. Otherwise the handoff value can be between 0 and the configured timeout.

Secondly, I made a small refactor of `AbstractBatchIndexTask#waitForSegmentAvailability`. The method now sets the value for `segmentAvailabilityConfirmationCompleted` as well as returns the boolean value assigned to that variable. In the past the code only returned the boolean and relied on the caller to set the value, this seemed like poor practice.

<hr>

##### Key changed/added classes in this PR
 * `IngestionStatsAndErrorsTaskReportData`
 * `AbstractBatchIndexTask`
 
<hr>

This PR has:
- [x] been self-reviewed.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by capistrant** [comment]
@jihoonson you mentioned that it would be nice to have this added to the report in #10676 ([discussion](https://github.com/apache/druid/pull/10676#discussion_r566380095)) If you get a chance, could you take a peek at this in the next few weeks? would be great to get it into the code before 0.22.0 release cycle starts so it goes in as the same time as the pr to add the handoff wait. Thanks!

**Comment by jihoonson** [comment]
Thank you for the follow-up! Code changes LGTM, but can you please add some integration tests? I guess you can modify those integration tests you added in the previous PR to verify that the waitTime is always larger than 0.

**Comment by capistrant** [comment]
> Thank you for the follow-up! Code changes LGTM, but can you please add some integration tests? I guess you can modify those integration tests you added in the previous PR to verify that the waitTime is always larger than 0.

good point. I went with a simple assertion in the existing code to verify the report has a non-zero wait time for the IT that perform a handoff wait. I believe that should suffice in making sure the report stays valid

**Comment by capistrant** [comment]
@jihoonson should we have to do anything more than adding this to release notes in future release to notify clients of json payload change? I suppose it is possible that clients are relying on some static schema for this report JSON so the new field could break code that doesn't ignore new fields being added.

**Review by jihoonson — APPROVED** [review]

**Comment by jihoonson** [comment]
LGTM, Thanks @capistrant. I don't particularly worry about it but we can include some warning about it in the release notes if you want.

**Comment by maytasm** [comment]
This change is causing build to fail. Seems like this change https://github.com/apache/druid/pull/11688 that went in a few days ago use the IngestionStatsAndErrorsTaskReportData constructor which is now changed in this PR. Travis green check in this PR was from 25 days ago. In the future, I recommend rerunning Travis before merging for checks that passed long time ago.

**Comment by capistrant** [comment]
> This change is causing build to fail. Seems like the change #11688 that went in a few days ago use the IngestionStatsAndErrorsTaskReportData constructor which is now changed in this PR. Travis green check in this PR was from 25 days ago. In the future, I recommend rerunning Travis before merging for checks that passed long time ago.

agree 100%. I've been trying to stay on top of merging with master on a regular basis to make sure I keep CI fresh but let this one slip. Thanks for the quick fix for master

**Pull request merged**
