### PR TITLE
Initialize NullValueHandlingConfig for failed tests 

### PR DESCRIPTION
**Pull request by a2l007**
When run independently, tests `DelegateOrMinKeyCollectorTest` and `QuantilesSketchKeyCollectorTest` currently fail  with the following error:
```
[ERROR] Errors: 
[ERROR] org.apache.druid.msq.statistics.DelegateOrMinKeyCollectorTest.testAdd
[ERROR]   Run 1: DelegateOrMinKeyCollectorTest.testAdd:81->createKey:148 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR] org.apache.druid.msq.statistics.DelegateOrMinKeyCollectorTest.testDownSampleSingleKey
[ERROR]   Run 1: DelegateOrMinKeyCollectorTest.testDownSampleSingleKey:99->createKey:148 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR] org.apache.druid.msq.statistics.DelegateOrMinKeyCollectorTest.testDownSampleTwoKeys
[ERROR]   Run 1: DelegateOrMinKeyCollectorTest.testDownSampleTwoKeys:125->createKey:148 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR] org.apache.druid.msq.statistics.QuantilesSketchKeyCollectorTest.test_sequentialKeys_unweighted
[ERROR]   Run 1: QuantilesSketchKeyCollectorTest.test_sequentialKeys_unweighted:66 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR] org.apache.druid.msq.statistics.QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_barbellWeighted
[ERROR]   Run 1: QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_barbellWeighted:136 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR] org.apache.druid.msq.statistics.QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_inverseBarbellWeighted
[ERROR]   Run 1: QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_inverseBarbellWeighted:163 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
[ERROR]   Run 1: QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_unweighted:85 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
ERROR] org.apache.druid.msq.statistics.QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_unweighted_downSampledToSmallestSize
[ERROR]   Run 1: QuantilesSketchKeyCollectorTest.test_uniformRandomKeys_unweighted_downSampledToSmallestSize:103 » IllegalState NullHandling module not initialized, call NullHandling.initializeForTests()
```

This PR initializes the NullValueHandlingConfig to fix these tests.

<hr>

This PR has:
- [x] been self-reviewed.

### CODE REVIEW

**Review by kfaraz — COMMENTED** [review]
Following the example of other tests, I think it would be better to do the `NullHandling.initializeForTests()` in the test class themselves rather than the utils class.

**Comment by a2l007** [comment]
@kfaraz Thanks for the review. Refactored the tests based on your comment.

**Review by kfaraz — APPROVED** [review]
Thanks for the fix, @a2l007 🚀

**Comment by kfaraz** [comment]
@a2l007 , you might need to merge the latest master to fix these failures using #13083

**Pull request merged**
