### PR TITLE
issue-12426 upgrade k8s client due to cve

### LINKED ISSUE #12426: Security: update kubernetes java client due to cve
### Description

https://github.com/advisories/GHSA-m8wh-mqgf-rr8g

Needs upgrade from 10.0.1 to 11.0.1

### Motivation

Please provide the following for the desired feature or change:
- It is not good practice to rely on jars with publicly disclosed security issues - and if you do you should make public why you think your project is not affected

2 changes in the k8s java client cause compile problems for druid:

```
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR] /opt/src/extensions-core/kubernetes-extensions/src/main/java/org/apache/druid/k8s/discovery/DefaultK8sApiClient.java:[83,36] method listNamespacedPod in class io.kubernetes.client.openapi.apis.CoreV1Api cannot be applied to given types;
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   required: java.lang.String,java.lang.String,java.lang.Boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Boolean
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   found: java.lang.String,<nulltype>,<nulltype>,<nulltype>,<nulltype>,java.lang.String,int,<nulltype>,<nulltype>,<nulltype>
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   reason: actual and formal argument lists differ in length
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR] /opt/src/extensions-core/kubernetes-extensions/src/main/java/org/apache/druid/k8s/discovery/DefaultK8sApiClient.java:[116,24] method listNamespacedPodCall in class io.kubernetes.client.openapi.apis.CoreV1Api cannot be applied to given types;
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   required: java.lang.String,java.lang.String,java.lang.Boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Boolean,io.kubernetes.client.openapi.ApiCallback
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   found: java.lang.String,<nulltype>,boolean,<nulltype>,<nulltype>,java.lang.String,<nulltype>,java.lang.String,int,boolean,<nulltype>
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   reason: actual and formal argument lists differ in length
```

### PR DESCRIPTION
**Pull request by pjfanning**
cve in k8s jar 

Fixes #12426.

https://github.com/advisories/GHSA-m8wh-mqgf-rr8g

Needs upgrade from 10.0.1 to 11.0.1

## Motivation

It is not good practice to rely on jars with publicly disclosed security issues - and if you do you should make public why you think your project is not affected

2 changes in the k8s java client cause compile problems for druid:

```
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR] /opt/src/extensions-core/kubernetes-extensions/src/main/java/org/apache/druid/k8s/discovery/DefaultK8sApiClient.java:[83,36] method listNamespacedPod in class io.kubernetes.client.openapi.apis.CoreV1Api cannot be applied to given types;
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   required: java.lang.String,java.lang.String,java.lang.Boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Boolean
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   found: java.lang.String,<nulltype>,<nulltype>,<nulltype>,<nulltype>,java.lang.String,int,<nulltype>,<nulltype>,<nulltype>
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   reason: actual and formal argument lists differ in length
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR] /opt/src/extensions-core/kubernetes-extensions/src/main/java/org/apache/druid/k8s/discovery/DefaultK8sApiClient.java:[116,24] method listNamespacedPodCall in class io.kubernetes.client.openapi.apis.CoreV1Api cannot be applied to given types;
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   required: java.lang.String,java.lang.String,java.lang.Boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Boolean,io.kubernetes.client.openapi.ApiCallback
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   found: java.lang.String,<nulltype>,boolean,<nulltype>,<nulltype>,java.lang.String,<nulltype>,java.lang.String,int,boolean,<nulltype>
[2022-04-11 23:16:03] [build-stdout] [2022-04-11 23:16:03] [autobuild] [ERROR]   reason: actual and formal argument lists differ in length
```

#### Added a forbidden-apis entry ...

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by xvrl** [comment]
@pjfanning can we indicate in the PR description what version we are upgrading to, and point out that this is a major version bump. Did we look to make sure there aren't anything in the release notes we need to worry about?

**Comment by pjfanning** [comment]
> @pjfanning can we indicate in the PR description what version we are upgrading to, and point out that this is a major version bump (including a link to the release notes would be nice). Did we look to make sure there aren't anything in the release notes we need to worry about?

I modified the description

**Comment by FrankChen021** [comment]
@pjfanning Could you fix the license check?

```text
Error: found 6 missing licenses. These licenses are reported, but missing in the registry
druid_module: kubernetes-extensions, groupId: io.kubernetes, artifactId: client-java-api, version: 11.0.1, license: Apache License version 2.0
druid_module: kubernetes-extensions, groupId: io.gsonfire, artifactId: gson-fire, version: 1.8.5, license: Apache License version 2.0
druid_module: kubernetes-extensions, groupId: io.kubernetes, artifactId: client-java-proto, version: 11.0.1, license: Apache License version 2.0
druid_module: kubernetes-extensions, groupId: org.bitbucket.b_c, artifactId: jose4j, version: 0.7.3, license: Apache License version 2.0
druid_module: kubernetes-extensions, groupId: io.kubernetes, artifactId: client-java, version: 11.0.1, license: Apache License version 2.0
druid_module: kubernetes-extensions, groupId: io.kubernetes, artifactId: client-java-extended, version: 11.0.1, license: Apache License version 2.0
```

**Comment by pjfanning** [comment]
@FrankChen021 I updated the licenses.yaml

**Review by FrankChen021 — APPROVED** [review]

**Pull request merged**
