### PR TITLE
emit processed bytes metric

### PR DESCRIPTION
**Pull request by pjain1**
### Description

Currently there is no way to know how much data is processed by task during ingestion. This PR adds `ingest/events/processedBytes` metric to emit number of bytes read since last emission time. 

 - This PR adds `InputStats` class which is present in all task types and acts as holder for task level counts like processed bytes in this case. Thus standardized metrics throughout the task types can be added in future and emitted using `InputStatsMonitor` which is automatically initialized for all tasks

- This PR provides convenient wrapper class named  `CountableInputEntity` which can warp any `InputEntity` to count number of bytes processed through that `InputEntity`, thus its easier for new implementations to emit this metric just by wrapping the base input entity in this while creating `InputEntityIteratingReader`

- Since Kafka and Kinesis does not use `InputEntity`, therefore processed bytes is increment directly in `SeekableStreamIndexTaskRunner` as it has access to `InputStats`

- This does not support Firehoses

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.
<hr>

##### Key changed/added classes in this PR
 * `InputStats`
 * `InputStatsMonitor`
 * `CountableInputEntity`
 * `AbstractBatchIndexTask`
 * `SeekableStreamIndexTask`

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @pjain1, have you checked https://github.com/apache/druid/issues/10352? This proposal describes some idea on ingestion metrics.

**Comment by pjain1** [comment]
@jihoonson  The proposal looks great, I did this PR because bytes ingested is not available for streaming or batch tasks. I see your proposal only includes metrics for batch tasks, probably we can do another PR for emitting bytes ingested for kafka/kinesis directly through `FireDepartment`. 

I believe the bytes ingested reported through your proposed changes will be all types of `InputEntity` and will include the bytes read for determining partitions as well indexing ?

**Comment by jihoonson** [comment]
> @jihoonson The proposal looks great, I did this PR because bytes ingested is not available for streaming or batch tasks. I see your proposal only includes metrics for batch tasks, probably we can do another PR for emitting bytes ingested for kafka/kinesis directly through `FireDepartment`.

Yeah, it sounds reasonable to me to add bytes ingested for both streaming and batch. My proposal only talks about metrics for batch, but I have been also thinking about the metrics system for ingestion in general. Currently, both batch and streaming ingestion uses `FireDepartmentMetrics` which was designed for `RealtimeIndexTask` which is now deprecated. I'm not sure if it's good to continue to use it. Rather, I think batch and streaming tasks should use different classes for their own metrics since you will want to see different metrics per your ingestion type (ex, there is no handoff in batch ingestion while handoff time could be important in streaming ingestion). To do so, I have been thinking to add new classes each of which defines _all_ metrics useful for batch and streaming ingestion, respectively. I'm not sure why we should keep metrics separately in different classes such as the bytes ingested in `InputStats` added in this PR. Does this make sense?

> I believe the bytes ingested reported through your proposed changes will be all types of `InputEntity` and will include the bytes read for determining partitions as well indexing ?

Yes, correct. More precisely, most of metrics including both the bytes read and the bytes written will be available for individual phase (determining partitions, indexing, etc) as well as for the overall metrics across all phases.

**Comment by pjain1** [comment]
> To do so, I have been thinking to add new classes each of which defines all metrics useful for batch and streaming ingestion, respectively. I'm not sure why we should keep metrics separately in different classes such as the bytes ingested in InputStats added in this PR. Does this make sense?

I added this class with the vision that more metrics can be added in future regarding ingestion as this class is available at task and InputSource/InputEntity level as well. Also I don't see `FireDepartmentMetrics` being used in batch tasks apart from `SinglePhaseSubTask`, so I though a new framework of `InputStatsMonitor` which is enabled by default with `InputStats` can be used which can be expanded to include ingestion stats similar to one being reported by kafka indexing task.

**Comment by pjain1** [comment]
@jihoonson are you actively working on your proposal ? do you think you can reuse the `InputStats` strategy from here ?

**Comment by jihoonson** [comment]
> @jihoonson are you actively working on your proposal ? do you think you can reuse the `InputStats` strategy from here ?

@pjain1 sorry, I forgot about this PR. I could reuse it, but I'm still not sure why it

**Comment by pjain1** [comment]
As long as we get the metrics about how many raw bytes are processed from the source (including scans for determining shard specs) I think I am ok with any approach you follow. It doesn't necessarily be the code from this PR, I am already using this code internally so thought if its reused there would be less conflicts but totally up to you. Thanks

**Comment by jihoonson** [comment]
Apologize, I accidentally clicked the button which published my previous comment incomplete. Updated it now.

**Comment by pjain1** [comment]
Makes sense, so as long as https://github.com/apache/druid/pull/10407#issuecomment-713016099 is satisfied things seems good to me.

**Comment by jihoonson** [comment]
@pjain1 thanks. Yes, per-phase metrics and total metrics will be available for raw input bytes. Other than the issue we have talked, this PR makes sense to me. I don't think my proposal necessarily blocks this PR or vice versa. I just wanted to make sure what design is best for us. I can review this PR probably this week.

**Comment by somu-imply** [comment]
@pjain1 I have started taking a look at this PR. Deepest apologies that it has not been reviewed yet. Any chances, you can help resolve the conflicts ?

**Comment by pjain1** [comment]
hey @somu-imply, I can look into resolving conflicts over the weekend. However, @jihoonson was working on something similar iirc so not sure whats the status of it and if this is needed anymore.

**Comment by somu-imply** [comment]
@pjain1 thanks, I have resolved some conflicts and have made this PR up-to-date. #12750 has the changes. I'll appreciate if you can help add to it and review it

**Comment by kfaraz** [comment]
Closing this as #13520 is already merged.

**Pull request closed without merging**
