### PR TITLE
Prepare 28.0.0 branch for the release

### PR DESCRIPTION
**Pull request by LakshSingla**
Updates the links in the `links.ts` and related files to 28.0.0

It is done as a part of [Preparing the release branch](https://github.com/apache/druid/blob/master/distribution/asf-release-process-guide.md#preparing-the-release-branch) and analogous to https://github.com/apache/druid/pull/14569

### CODE REVIEW

**Review by clintropolis — COMMENTED** [review]
hmm, I think this is usually done in the release branch itself, else we have to change back to latest in master branch

**Comment by LakshSingla** [comment]
I messed up the target branch to 'master', it should have been 28.0.0. Thanks for catching!

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
didn't you need to update the docker-compose files?

**Comment by LakshSingla** [comment]
The docker-compose file mentioned in the release guide was already updated in the previous release update to the master https://github.com/apache/druid/blob/28.0.0/distribution/docker/docker-compose.yml.

I'll raise a similar PR for updating the master shortly.

**Pull request merged**
