### PR TITLE
Increase timeout of call to get worker capacity in console

### PR DESCRIPTION
**Pull request by abhishekagarwal87**
Screenshot 2023-04-14 at 4 21 46 PM

Been seeing the above very frequently of late.

### CODE REVIEW

**Review by amaechler — APPROVED** [review]
🐻

**Comment by kfaraz** [comment]
@abhishekagarwal87 , what size of cluster are you seeing this on? Is it only during startup or other situations as well?

**Review by pranavbhole — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
@kfaraz - They are not big clusters. One is 35 servers. btw this timeout is client-side timeout so latency would also vary from where you access the console.

**Review by cryptoe — APPROVED** [review]

**Comment by cryptoe** [comment]
Changes LGTM!!

**Pull request merged**
