### PR TITLE
Fix UnsupportedOperationException when sorting segments in auto compaction

### PR DESCRIPTION
**Pull request by jihoonson**
### Description

The auto compaction currently fails since the `NewestSegmentFirstIterator` creates an `UnmodifiableList` but the auto compaction needs to sort it.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by suneet-s** [comment]
can we add an integration test for this?

**Comment by jihoonson** [comment]
@suneet-s I'm thinking to add some in a follow-up PR.

**Comment by suneet-s** [comment]
> @suneet-s I'm thinking to add some in a follow-up PR.

cool. Any reason not to do it in this patch? Is it hard to add an integration test (fwiw - I've been fighting with them for about a day :( )

**Comment by jihoonson** [comment]
@suneet-s yeah, I agree we need some integration tests for the auto compaction. But, I think it's a different issue than fixing this bug. Since we are currently lack of any tests for it, I think it would be better to add a couple of tests required in a separate issue.

**Pull request merged**
