### PR TITLE
Imporve on incremental compilation

### PR DESCRIPTION
**Pull request by kgyrtkirk**
This patch fixes a few issues toward #14858
* some phony classes were added to enable maven to track the compilation of those classes
* cyclonedx [2.7.9](https://github.com/CycloneDX/cyclonedx-maven-plugin/releases/tag/cyclonedx-maven-plugin-2.7.9) seem to handle incremental compilation better; it had a PR relating to that
* needed to update root pom to `25`
* update antlr to 4.5.3 
  * older one didn't really worked incrementally; 4.5.3 works much better

left out:
* update commit-id plugin to 6.0.0
  * no idea what it was doing - but every module invoked it and it sit there for a few secs; newer version doesn't do this
  * this was able to shave off around 8 seconds from the build time of these 4 modules
  * unfortunately that version is not jdk8 compatible...so I had to remove it

These changes enable incremental compilation up to the `sql` module; where `javacc` regenerates some sources

```
clean="git clean -dfx"
build="mvn install -pl sql,!sql -am -Dtest=nonexistent -q -Dsurefire.failIfNoSpecifiedTests=false -Pskip-static-checks"
```

| cmd | base | pr | pr with commit-id:6.0.0 |
| --- | ---- | --- | --- |
| `$clean` | / | / | / |
| `$build` | 0m32.638s   | 0m33.844s | 0m24.660s |
| `$clean` | / | / | / |
| `$build -T9` | 0m30.250s |0m30.435s | 0m23.962s |
| `$build` | 0m32.841s | 0m30.435s |0m5.334s |
| `$build -T9` | 0m30.671s | 0m11.197s |0m5.190s |

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
cannot reproduce failure of `SinglePhaseParallelIndexingTest` from maven...merged master see if it passes now or not

**Comment by kgyrtkirk** [comment]
I've envountered #14861 again

**Review by cryptoe — APPROVED** [review]
Thanks for the pr @kgyrtkirk . Changes LGTM.

**Comment by kgyrtkirk** [comment]
Thank you @cryptoe for reviewing/merging these changes! :)

**Pull request merged**
