### PR TITLE
PulsarIndexingService and PulsarSchemaRegistryBytesDecoder

### LINKED ISSUE #7030: Add apache pulsar based indexing service
Be able to index records by reading a set of pulsar topics.

https://pulsar.apache.org/

### PR DESCRIPTION
**Pull request by josephglanville**
Fixes #7030 

### Description

Implements an indexing service extension for reading from Apache Pulsar.

Addtionally includes an implementation of `AvroBytesDecoder` that takes advantage of passing through `PulsarRecordEntity` to extract schema information such that messages can be automatically decoded into Avro `GenericRecord` types.

##### Key changed/added classes in this PR
 * `PulsarSchemaRegistryAvroBytesDecoder`
 * `PulsarSupervisor`
 * `PulsarIndexTask`

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by josephglanville** [comment]
@bananaaggle I noticed you opened #11223 today also. Perhaps we could merge our efforts?

**Comment by bananaaggle** [comment]
> @bananaaggle I noticed you opened #11223 today also. Perhaps we could merge our efforts?

Yes. How can I do for that?

**Comment by josephglanville** [comment]
@bananaaggle I have invited you as a collaborator to my fork. I think my branch is currently a little more complete.
Should credit @rueian as I adapted some of their code as a starting point for my implementation.

The main things left to do are implement tests and do some real world testing. I think we can spin up in-process Pulsar clusters to do this similar to how testing is done in https://github.com/streamnative/mop and https://github.com/streamnative/kop which should allow for fairly robust tests.

Also need to work out correct place for the extension to live, I put it in extensions-core for now but perhaps it belongs in extensions-contrib?

It also isn't clear where `PulsarSchemaRegistryAvroBytesDecoder` should live, it could either live in `avro-extensions` as it does now or could be put in `pulsar-indexing-service`.

**Comment by bananaaggle** [comment]
> @bananaaggle I have invited you as a collaborator to my fork. I think my branch is currently a little more complete.
> Should credit @rueian as I adapted some of their code as a starting point for my implementation.
> 
> The main things left to do are implement tests and do some real world testing. I think we can spin up in-process Pulsar clusters to do this similar to how testing is done in https://github.com/streamnative/mop and https://github.com/streamnative/kop which should allow for fairly robust tests.
> 
> Also need to work out correct place for the extension to live, I put it in extensions-core for now but perhaps it belongs in extensions-contrib?
> 
> It also isn't clear where `PulsarSchemaRegistryAvroBytesDecoder` should live, it could either live in `avro-extensions` as it does now or could be put in `pulsar-indexing-service`.

I think PulsarSchemaRegistryAvroBytesDecoder should be separated into another commit.

**Comment by josephglanville** [comment]
It's in a separate commit right now, if you mean a separate PR can certainly do that.

**Comment by binlijin** [comment]
I think PartitionIdType/SequenceOffsetType for pulsar should be String/MessageId or String/String like in pr https://github.com/apache/druid/pull/11223

**Comment by josephglanville** [comment]
@binlijin I considered that but using `MessageIDUtils.offset` seemed simpler. Is the motivation to use `MessageID` or `String` mostly to make it easier for human operators to inspect the current offsets? Are there any other benefits to this over the offset?

**Comment by binlijin** [comment]
https://github.com/apache/pulsar/blob/6704f12104219611164aa2bb5bbdfc929613f1bf/pulsar-client/src/main/java/org/apache/pulsar/client/util/MessageIdUtils.java#L30

        // Combine ledger id and entry id to form offset
        // Use less than 32 bits to represent entry id since it will get
        // rolled over way before overflowing the max int range

Because it can be overflow.

**Comment by josephglanville** [comment]
@binlijin I see. Ok, I will make the required changes. Thanks!

**Comment by polyzos** [comment]
@josephglanville great job on this one.. im wondering why this work has stayed idle though and what needs to be done in order to push the effort forward.

**Comment by josephglanville** [comment]
@polyzos mostly just lack of time on my part. Happy to collaborate with anyone that has bandwidth though.

**Comment by polyzos** [comment]
@josephglanville yes it would be great if we could push this effort forward, i think it can unlock many use cases.
Wondering what are the missing pieces and what needs to be done. Are there any points to reference?
Won't have much bandwidth over the next weeks, but i want to try an allocate some time to better understand the work thats in place along with next steps.
And maybe slowly piece by piece we can get this done

**Comment by josephglanville** [comment]
@polyzos I'm active on the Pulsar and Apache Slack instances if you want to chat. I will probably be looping back to this shortly once I finish my current tasks.

**Comment by rkaw92** [comment]
Hi, any chance of this integration seeing the light of day? Does this need picking up by somebody else?

**Comment by polyzos** [comment]
@rkaw92 needs to be picked up by somebody else

**Comment by dat-vikash** [comment]
Hi, if we can get a description of whats left on this, I'm sure someone can pick it up. Druid badly needs a pulsar integration.

**Comment by dat-vikash** [comment]
@josephglanville I (my team and I) would like collab with you on this. We already have a fork of your branch and have added tests and are working to get this deployed to our druid clusters in dev and prod. KoP is a non starter for us due to security reasons, so we would like to build off this PR.

**Comment by josephglanville** [comment]
Unfortunately I never really got back to this and moved on from where it was relevant, anyone can feel free to pick up any of this if they are so motivated.

**Pull request closed without merging**
