### PR TITLE
Add read timeout for getting records when sampling a stream

### PR DESCRIPTION
**Pull request by zachjsh**
### Description

Previously, when sampling streaming data, the sampler would wait `timeoutMs` for `numRows` to be returned. If the stream has less rows than `numRows`, the sampler would wait the full `timeoutMs` period. In some cases, initially connecting to a given stream to sample may take a considerable amount of time, but reading subsequent records thereafter is a much faster operation. For these cases, this PR adds a new sampler config property `readTimeoutMs`, which if specified, causes the sampler to return after this period of time if no further records are found between the last record found, or `timeoutMs`, whichever comes first.  The new `readTimeoutMs` is only applied once some records have been read from the stream during sampling. For example if a stream has only 1 record in it at a given time, and `timeoutMs` is configured as `15000` miliseconds and `readTimeoutMs` is configured as `2000` milliseconds while `numRows` is configured as `500`, then assuming the first record is read quickly, the sampler will return after roughly `2000` milliseconds, whereas previously it would have returned after the full `15000` millesecond `timeoutMs` config value.

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
We really have to resist the temptation to add a config for every corner case we run into. Is it absolutely necessary to have this config? Even if you need these, why not use standard terms such as connectTimeout, readTimeout that are more common names and easier to relate to than something like nextRecordTimeout?

**Comment by zachjsh** [comment]
> We really have to resist the temptation to add a config for every corner case we run into. Is it absolutely necessary to have this config? Even if you need these, why not use standard terms such as connectTimeout, readTimeout that are more common names and easier to relate to than something like nextRecordTimeout?

@abhishekagarwal87 , yes I can change to `readTimeout`, that is a better name.

**Comment by kfaraz** [comment]
I am not entirely sure we need a config here either. Irrespective of what we name the config, it is going to cause confusion with the existing `timeoutMs`, especially since the `SamplerConfig` is used with batch too where this config would not be meaningful.

I think we could just have a __fixed__ maximum number of empty polls. When we poll the topic for records, and say we don't get anything for 10 tries or say, we just wrap up the sampler.

Since this is only used for sampling, there is no real obligation to keep waiting until we have read the requested number of records. Compare this to batch where if there is no file at the specified path, we just fail or return empty and don't wait for data to show up.

@zachjsh , @abhishekagarwal87 , what do you think?

**Comment by zachjsh** [comment]
> I am not entirely sure we need a config here either. Irrespective of what we name the config, it is going to cause confusion with the existing `timeoutMs`, especially since the `SamplerConfig` is used with batch too where this config would not be meaningful.
> 
> I think we could just have a **fixed** maximum number of empty polls. When we poll the topic for records, and say we don't get anything for say 10 tries, we finish the sampling.
> 
> Since this is only used for sampling, there is no real obligation to keep waiting until we have read the requested number of records. Compare this to batch where if there is no file at the specified path, we just fail or return empty and don't wait for data to show up.
> 
> @zachjsh , @abhishekagarwal87 , what do you think?

thanks @kfaraz , just wanted to be clear that this new config is not strictly needed for things to work properly, most users will not have to touch this. However its usage enabled an improved UX

About your idea described above, the poll timeout is hardcoded to 100 milliseconds. There could be cases where a user may want to allow for longer than 1 second to for the next record to be read. As for confusion with timeoutMs, let me know if there is something I can add that helps differentiate them

**Comment by jon-wei** [comment]
I feel that some kind of config here makes sense, either as a timeout or a max number of tries after encountering an empty read, to allow the behavior to be disabled or adjusted to the characteristics of a specific stream

imo it should be called something like `streamingNextRecordTimeout` or something with "streaming" in the name if we're concerned that there would be confusion with batch sampling cases

**Comment by gianm** [comment]
It seems that the intent here is to prevent sampling from Kafka getting stuck when fewer than `numRows` exist in the stream. Instead of adding a second shorter timeout, could we tackle that problem directly? Something like having the sampler check the latest offset available in Kafka first (using `RecordSupplier#getLatestSequenceNumber`) and then returning early once it has read up through that latest message.

**Comment by gianm** [comment]
Btw, on general design. Sampling is intended to be used in a very specific situation— it's there so the web console (& any similar third-party UIs) can show people a few records from a stream prior to configuring their supervisors. I can't imagine that most users will set any of these config parameters in a case like that. They'll just get whatever behavior the UI requests from the API.

For that reason I think it's important to focus on the out-of-box behavior, so users using the builtin web console get the benefit of these adjustments.

**Comment by dkoepke** [comment]
> Something like having the sampler check the latest offset available in Kafka first (using RecordSupplier#getLatestSequenceNumber) and then returning early once it has read up through that latest message.

Would this cause issues when `useEarliestOffset` is false? Or if the earliest offset happens to be close to the latest in a stream that's actively receiving data?

From my understanding, the timeout here is basically defining how long a stream can be idle (have no data arrive / offsets stay the same). The goal is to improve the experience for web console (and similar UIs) when a stream is low volume at the time ingestion is being setup in Druid. Right now, for the web console, if there are fewer than 500 (`numRows`) rows, each call to the sampler always takes 15 seconds (`timeoutMs`). The web console calls the sampler a lot during the normal flow, so this can be pretty slow.

>  I can't imagine that most users will set any of these config parameters in a case like that.

Agreed. The intent of the config in the sampler payload is to allow UIs to tweak their settings without users having to redeploy Druid. It's not intended to be set (or even seen) by normal end users.

**Pull request closed without merging**
