### PR TITLE
Adjust SQL "cannot plan" error message.

### PR DESCRIPTION
**Pull request by gianm**
Two changes:

1) Restore the text of the SQL query. It was removed in #12897, but
   then it was later pointed out that the text is helpful for end
   users querying Druid through tools that do not show the SQL queries
   that they are making.

2) Adjust wording slightly, from "Cannot build plan for query" to
   "Query not supported". This will be clearer to most users. Generally
   the reason we get these errors is due to unsupported SQL constructs.

### CODE REVIEW

**Review by abhishekagarwal87 — APPROVED** [review]
LGTM.

**Comment by abhishekagarwal87** [comment]
There are test failures in SqlResourceTest.

**Comment by gianm** [comment]
Merged master and repushed. I ran SqlResourceTest locally an dit passed, so I guess the errors in Travis were unrelated (flakey test maybe?)

**Comment by abhishekagarwal87** [comment]
thanks @gianm. I just merged this.

**Pull request merged**
