### PR TITLE
Support to show leader of coordinators in `Services` web console view

### LINKED ISSUE #10329: Add support to show leader coordinator in `Services` web console view
### Description

Add support to show leader coordinator in `Services` web console view

### Motivation

As we know, compared with standby coordinators, leader of coordinators does a lot of tasks such as checking whether to launch compaction tasks. To check whether these tasks are being processed correctly when debugging or solving problems, the first thing is to determine which coordinator right now is the leader.

Currently, there's no way to know which coordinator is the leader from the web console ui. One has to use `/druid/indexer/v1/leader` RESTful API to send request to any coordinator nodes to get the information of leader. It's not a intuitive way for users.

So, this proposal aims to simplify this by indicating which coordinator is leader on the web console.

There's two ways achieve this: 

### Alternative 1

When switching to the `Services` view on web console, the frontend calls the `/druid/indexer/v1/leader` API to get the leader and then show the result in the `Tier` column of corresponding row in that view.

This is like the way current web console ui uses to show the last task status of middle manager in `Services` view

##### The Pros

No backend changes are involved.

##### The Cons

`/druid/indexer/v1/leader` must be sent to the coordinator, but the frontend can't sent this request util it gets services list from router through SQL query to know where coordinators locate. It's a little bit complex for the frontend.

### Alternative 2

When processing query on `sys.servers` table, broker calls `/druid/indexer/v1/leader` to get the leader and mark the leader coordinator in `tier` field. The frontend ui will automatically show the leader once there's value in `tier` property.

##### The Pros

No changes are involved in frontend but backend services. 

Any discussion would be appreciated.

### PR DESCRIPTION
**Pull request by FrankChen021**
This PR resolves #10329, which was proposed to show which coordinator node is the current leader on web console so that it saves us some time to find leader when addressing problems of druid clusters.

### Description

In this PR, only backend service is involved to meet this need. 

The `ServersTable` now requests leader information of coordinators and overlords and marks corresponding node as leader in the `Tier` field before returning the query results.

With this PR, Web console automatically shows the leader information in the `Service` view
image

<hr>

This PR has:
- [X] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by vogievetsky** [comment]
If this is modifying the behaviour of the system table I think it would be better to surface leader as an 'is_leader' column (and then the console can format it as it wants by asking the right query). No need to overload the `tier` column I think. More columns = better!

**Comment by FrankChen021** [comment]
Hi @vogievetsky  What you suggestion depends on how we define `tier`. The initial `tier` comes from historical nodes that serve different data retention rules. 

From the user's view on all druid nodes, I think `tier` could also used to describe different `roles` of nodes with same node type, which means for coordinators, the division of leader and non-leader also fit into this definition. And for the back-end implementation, this PR chooses to put the information in `tier` field for simplicity.

BTW,  I'll check and fix the integration tests failure later.

**Comment by jihoonson** [comment]
Oops, sorry @FrankChen021 I missed this PR before. It seems like the same functionality is implemented in https://github.com/apache/druid/pull/10680. Could you check if that's the case?

**Comment by clintropolis** [comment]
>Oops, sorry @FrankChen021 I missed this PR before. It seems like the same functionality is implemented in #10680. Could you check if that's the case?

My bad, I totally missed this as well, I think this functionality should be covered by the thing I did by side-effect in my PR, sorry @FrankChen021!

**Comment by FrankChen021** [comment]
@jihoonson @clintropolis Thank you for your information. Changes in this PR has been covered by the PR you mentioned above. 

The difference is that the leader indicator in this PR is returned in `tier` column which means, for the web console, there's no work to be done to display the leader information.

So, based on #10680, we still have to do some work on the web console side. I wonder what's your suggestion for the web console to show the leader indicator, is the indicator displayed in a new column or displayed in `tier` column ?

**Comment by clintropolis** [comment]
>So, based on #10680, we still have to do some work on the web console side. I wonder what's your suggestion for the web console to show the leader indicator, is the indicator displayed in a new column or displayed in tier column ?

Ah that is a good point, I didn't consider the 'services' tab of the web-console, currently you can only determine leadership after #10680 by querying sys.servers directly in the query tab, so it doesn't really resolve #10329 without additional work to the web-console. I'm not sure what would be the best UX to indicate which servers are the leaders on the 'services' tab, I guess the most straightforward way would be to just add the column, but I would imagine there are alternative ways this could be done? I think re-using 'tier' is sort of confusing, which is why I ended up just added a new column to the underlying table. @vogievetsky any ideas?

**Comment by FrankChen021** [comment]
Considering that leader is only available for overlord and coordinator nodes, and the number of these two nodes are far less than that of other kind of nodes, adding another new column on the 'Services' tab would leave the most of cells blank, which I think is not a good UX. 

I wonder if we could could change the column name 'Tier' on the 'Services' tab to another name(I have not come up with an appropriate name), so that it could hold not only the tier information of historical nodes, but also other information from different kind of nodes.  @clintropolis @vogievetsky

**Comment by clintropolis** [comment]
>Considering that leader is only available for overlord and coordinator nodes, and the number of these two nodes are far less than that of other kind of nodes, adding another new column on the 'Services' tab would leave the most of cells blank, which I think is not a good UX.

>I wonder if we could could change the column name 'Tier' on the 'Services' tab to another name(I have not come up with an appropriate name), so that it could hold not only the tier information of historical nodes, but also other information from different kind of nodes. @clintropolis @vogievetsky

What about the detail column? I think that might be more appropriate than reworking the tier column, unless there is something better I'm not thinking of...

**Comment by vogievetsky** [comment]
I think replacing the tier column with detail and having it show both pieces of info works. I think having another `Is leader` column would work also. I am 👍 to both ideas

**Comment by FrankChen021** [comment]
I think we can reach an agreement that 'Tier' should be replaced by 'Detail' on 'Service' tab on web console to show tier information of historical nodes and leader of coordinators.  @clintropolis @vogievetsky 

I'll make some changes to this PR later this week.

**Comment by FrankChen021** [comment]
> I think details is already on the 'service' tab; for historicals it contains load/drop queue information, and most recently completed task information for indexing stuffs. I don't see any reason to remove the tier and fold it into details along with the other stuff, lots of servers probably have that column populated, I was just suggesting that coordinators and overlords could make use of details instead of it being an empty column

Sorry, I misunderstood it.

**Comment by FrankChen021** [comment]
This PR is replaced by 10951

**Pull request closed without merging**
