### PR TITLE
Add a query context param allowedServerKeyword to optionally get partial results from a subset of data servers whose hostname matches a given keyword

### PR DESCRIPTION
**Pull request by wjhypo**
### Description

This PR adds a query context param `allowedServerKeyword` used by broker to optionally get partial results from a subset of data servers whose hostname matches a given keyword. This is useful when you only want the queries to hit a subset of data servers for performance testing, debugging purposes, etc. E.g., this value can be set to "data-memory-tier" if that's a substring of the hostname convention of historicals you'd like to query and similarly can be set to "middle" to only gather results from peon tasks running in middle managers. Note that this feature can only further filter on data servers that are already been selected by the routing logic. In other words, it doesn't allow you to query arbitrary data servers ignoring `druid.broker.select.tier` and `druid.server.priority`.

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by a2l007** [comment]
Thanks for the PR! 
Instead of having the allowed server check in `CachingClusteredClient`, have you considered creating a new [ServerSelectorStrategy](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/client/selector/ServerSelectorStrategy.java) implementation that can perform the similar filtering via the pick method? The implementation could be a separate extension that users can include if they would like to perform hostname based filtering.

**Comment by wjhypo** [comment]
@a2l007 Thanks for the idea! I think we can probably add a param to the `pick` function in `ServerSelectorStrategy` to push down the filtering logic to `ServerSelectorStrategy` to filter on the results of either `random` or `connectionCount` or other future extensions which seems cleaner than the current approach but not able to achieve the purpose through adding a new `ServerSelectorStrategy` because for the same tier of servers, the hostnames usually have the same convention, e.g., data-`server-memory-abc`, `data-server-memory-def`, and let's say there are 2 replicas for the same segment A on these 2 servers, if using `random`, either of them will be picked; if using `connectionCount`, the server with less connections will be picked; however, if we create a new `ServerSelectorStrategy` called `HostnameServerSelectorStrategy`, unless we specify the full host name in query context, e.g., `data-server-memory-abc` which is rare, if we just specify `data-server-memory`, we will get multiple candidates and need to fallback to use a sorting mechanism again such us `random` or `connectionCount` to order and pick one. Let me know if you have better ideas, thanks!

**Comment by a2l007** [comment]
> @a2l007 Thanks for the idea! I think we can probably add a param to the `pick` function in `ServerSelectorStrategy` to push down the filtering logic to `ServerSelectorStrategy` to filter on the results of either `random` or `connectionCount` or other future extensions which seems cleaner than the current approach but not able to achieve the purpose through adding a new `ServerSelectorStrategy` because for the same tier of servers, the hostnames usually use the same convention, e.g., `data-server-memory-abc`, `data-server-memory-def`, and let's say there are 2 replicas for the same segment A on these 2 servers, if using `random`, either of them will be picked; if using `connectionCount`, the server with less connections will be picked; however, if we create a new `ServerSelectorStrategy` called `HostnameServerSelectorStrategy`, unless we specify the full host name in query context, e.g., `data-server-memory-abc` which is rare, if we just specify `data-server-memory`, we will get multiple candidates and need to fallback to use a sorting mechanism again such us `random` or `connectionCount` to order and pick one. Let me know if you have better ideas, thanks!

For the new `ServerSelectorStrategy` implementation, what I had in mind is that the implementation would have a delegate serverselectorstrategy. The `HostnameServerSelectorStrategy` could have either `random` or `connectionCount` as its delegate strategy(based on user configuration). So, its pick implementation would do a `delegate.pick()` first followed by the hostname filtering. Would that work for your use case?

**Comment by wjhypo** [comment]
> > @a2l007 Thanks for the idea! I think we can probably add a param to the `pick` function in `ServerSelectorStrategy` to push down the filtering logic to `ServerSelectorStrategy` to filter on the results of either `random` or `connectionCount` or other future extensions which seems cleaner than the current approach but not able to achieve the purpose through adding a new `ServerSelectorStrategy` because for the same tier of servers, the hostnames usually use the same convention, e.g., `data-server-memory-abc`, `data-server-memory-def`, and let's say there are 2 replicas for the same segment A on these 2 servers, if using `random`, either of them will be picked; if using `connectionCount`, the server with less connections will be picked; however, if we create a new `ServerSelectorStrategy` called `HostnameServerSelectorStrategy`, unless we specify the full host name in query context, e.g., `data-server-memory-abc` which is rare, if we just specify `data-server-memory`, we will get multiple candidates and need to fallback to use a sorting mechanism again such us `random` or `connectionCount` to order and pick one. Let me know if you have better ideas, thanks!
> 
> For the new `ServerSelectorStrategy` implementation, what I had in mind is that the implementation would have a delegate serverselectorstrategy. The `HostnameServerSelectorStrategy` could have either `random` or `connectionCount` as its delegate strategy(based on user configuration). So, its pick implementation would do a `delegate.pick()` first followed by the hostname filtering. Would that work for your use case?

Thanks, that should work, I'll make the change accordingly.

**Pull request closed without merging**
