### PR TITLE
Replace source call to make scripts more portable

### LINKED ISSUE #10744: druid 0.20.0 start scripts expect bash to be /bin/sh.  This is NOT true on debian/ubuntu causing the start scripts to fail
### Affected Version

0.20.0

### Description
upgrading 3 master/2 query/2 data node cluster from 0.16.0-incubating to 0.20.0. on Ubuntu 16.04. 
On this system /bin/sh is symlinked to /bin/dash. 

The incantation on line 44 of bin/node.sh fails to find the java-util script when run under dash.
all of the startup scripts (broker.sh, etc) have the following form:

```
cd $(dirname $0)/../
sh ./bin/node.sh historical $1
```
this fails on ubuntu.

Changing the sh line to bash ... fixes it. 

error with the script as distributed:

```
$ bin/historical.sh start
./bin/node.sh: 44: ./bin/node.sh: source: not found
Could not find java - please run /opt/druid/apache-druid-0.20.0/bin/verify-java to confirm it is installed.
$
```
changing the last line to 
```
bash ./bin/node.sh historical $1
```
allows it to work as expected:
```
$ bin/historical.sh start
Started historical node (53662)
$
```

### PR DESCRIPTION
**Pull request by iMichka**
Fixes #10744

#### Fixed the bug ...

Fixes:
./bin/node.sh: 44: ./bin/node.sh: source: not found
Could not find java - please run /opt/druid/apache-druid-0.20.0/bin/verify-java to confirm it is installed.

#### Renamed the class ...

N/A

#### Added a forbidden-apis entry ...

N/A

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by iMichka** [comment]
Ping @lrosenman who opened the initial issue. You might be interested in testing this.

**Comment by iMichka** [comment]
For reference, this issue while packaging `druid` for Linux in Homebrew: https://github.com/Homebrew/homebrew-core/pull/90196

**Comment by iMichka** [comment]
Test failure looks unrelated.

**Review by FrankChen021 — APPROVED** [review]
Thank you for your first contribution 👍

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
Thank you @iMichka. I have merged your PR.

**Pull request merged**
