### PR TITLE
Save a metadata call when reading files from CloudObjectInputSource.

### PR DESCRIPTION
**Pull request by gianm**
The call to `createSplits(inputFormat, null)` in `formattableReader` would use the default split hint spec, `MaxSizeSplitHintSpec`, which makes `getObjectMetadata` calls in order to compute its splits. This isn't necessary; we're just trying to unpack the files inside the input source.

To fix this, use `FilePerSplitHintSpec` to extract files without any funny business.

### CODE REVIEW

**Comment by kfaraz** [comment]
Does this mean that for cloud input sources, if we don't specify a split hint spec explicitly, each file would correspond to a single split? Couldn't that potentially cause a large skew between the amount of work each batch ingestion task does?

**Comment by gianm** [comment]
> Does this mean that for cloud input sources, if we don't specify a split hint spec explicitly, each file would correspond to a single split? Couldn't that potentially cause a large skew between the amount of work each batch ingestion task does if the files differ a lot in size?

Ah, no, because the code here runs on worker tasks after the splits have already been made by the main task. (Or on the Overlord to do sampling, where there is no parallelism anyway.) It is using `createSplits` simply as a way of getting the list of objects out of `prefixes`, `objects`, or `uris`.

**Comment by kfaraz** [comment]
> Ah, no, because the code here runs on worker tasks after the splits have already been made by the main task. (Or on the Overlord to do sampling, where there is no parallelism anyway.) It is using createSplits simply as a way of getting the list of objects out of prefixes, objects, or uris.

Ah, I see. Thanks for the clarification!

> You can especially tell it doesn't matter because the splits are flatMap together anyway.

Yes, fair point.

**Review by kfaraz — APPROVED** [review]
LGTM

**Pull request merged**
