### PR TITLE
Fix flakiness in query-retry ITs

### PR DESCRIPTION
**Pull request by rohangarg**
Possible fix for flakiness in query-retry ITs as explained in #12700 
Tested by running locally ~ 50 times with an automation, all the runs pass.

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by paul-rogers** [comment]
@rohangarg, thanks for fixing this flaky test! Thanks also for your detailed analysis. From prior observations, and based on your analysis, here's my guess as to what was happening. We spin up the Docker cluster and then start tests. The current ITs don't check the status of the cluster before they run: they simply rely on the retry utility to handle any failures.

I've noticed that, on a single machine, it can take significant time for the cluster to come up. The "new ITs" specifically check the health of each service before starting the tests, and I've seen that this can take a while.

So, in the scenario you describe, it may be that the good historical comes up and serves the 50 queries before the bad one has had a chance to get itself organized. So, an alternative fix would have been to check the health of all services before running the tests.

Still, that leaves the statistical nature of the failure detection, which is unappealing. The deterministic mechanism you implemented seems much better.

One suggestion: please add your explanation of the new behavior to the test code itself as a comment. I had a hard time figuring out what the code was doing until I read your explanation, which cleared thing right up. Would be great to preserve that explanation for future readers of the code.

**Comment by rohangarg** [comment]
@paul-rogers : Thanks a lot for review and the feedback! 

> We spin up the Docker cluster and then start tests. The current ITs don't check the status of the cluster before they run: they simply rely on the retry utility to handle any failures.
I've noticed that, on a single machine, it can take significant time for the cluster to come up. The "new ITs" specifically check the health of each service before starting the tests, and I've seen that this can take a while.
So, in the scenario you describe, it may be that the good historical comes up and serves the 50 queries before the bad one has had a chance to get itself organized.

Yes, that's what my conjecture was too regarding the flakiness. The current test only has some application level checks which acts as a proxy for test setup valdiation too, which seems a bit shaky. The delay in test setups due to load on CI is probably the reason I can't reproduce it locally. Great to know that the new framework has first class support for test setup check!

> So, an alternative fix would have been to check the health of all services before running the tests.
Still, that leaves the statistical nature of the failure detection, which is unappealing. The deterministic mechanism you implemented seems much better.

Yes, I had thought of that approach but didn't move in that direction unless we have a good reason. Seemed better to me to make the test verify only the query-retry mechanism on the bad historical.

> One suggestion: please add your explanation of the new behavior to the test code itself as a comment. I had a hard time figuring out what the code was doing until I read your explanation, which cleared thing right up. Would be great to preserve that explanation for future readers of the code.

Yes, totally agree with you. I have added more explanation to the existing code documentation in the test and also updated some of it which has become outdated after the re-write. Thanks for catching that!

**Review by paul-rogers — APPROVED** [review]
LTGM (Non-binding)

**Review by clintropolis — APPROVED** [review]

**Comment by rohangarg** [comment]
Thanks for the review @paul-rogers and @clintropolis! 
I also ran the test via Travis multiple times and the runs were successful

**Pull request merged**
