### PR TITLE
Changed combine old data with new data and overwrite data and ingesti…

### PR DESCRIPTION
**Pull request by ajurcenk**
### Description
Found the issue with the "[Combine old data with new data and overwrite](https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html#combine-old-data-with-new-data-and-overwrite)" section in the Druid update data tutorial.
The ingestion (file spec [updates-append-index2.json](https://github.com/apache/druid/blob/master/examples/quickstart/tutorial/updates-append-index2.json)) ) uses combining input source type with two different types: `druid` and `local` file data sources. As a result, the time dimension columns are different: the `__time` in the druid type input source and the `timestamp` in the local input source. The result is the incorrect data rollup result.

#### Changes

1. Changed the timestamp column name to `__time` in the ingestion specs. for [Updating existing data tutorial](https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html) :

```json
"timestampSpec": {
        "column": "__time",
        "format": "iso"
  }
```
2. Renamed timestamp column to `__time` in the  [Updating existing data tutorial](https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html) data files.

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by vtlim — APPROVED** [review]
Thanks for your first contribution @ajurcenk! The changes look good to me.

**Review by kfaraz — CHANGES_REQUESTED** [review]
@ajurcenk , thanks for trying to improve the tutorials!
In this case, the files are correct. `__time` column is a Druid concept and the input column used for timestamp can have any name and not just `__time`.

Could you please elaborate on the issue that you faced with the tutorial that led you to consider this?

**Comment by ajurcenk** [comment]
The issue is with the combining input source. I can't find how to change the file data source primary time column name to Druid data source primary time column (__time) or reverse when the input source is combining type.

**Comment by techdocsmith** [comment]
@kfaraz see related https://github.com/apache/druid/pull/13641 for some context. Maybe this should be addressed another way?

**Pull request closed without merging**
