### PR TITLE
coordinator compactionTask filter locked interval before submitted

### PR DESCRIPTION
**Pull request by liuxiaohui1221**
Fixes #XXXX.
Coordinator submit compaction task sometimes failed,because timechunkLock is locked by other task(like kafka indexing task).

### Description
The purpose of this PR is to reduce the failure rate of CompactTask and increase the success rate of CompactTask when useing timechunk lock task.

#### Added a forbidden-apis entry ...

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @liuxiaohui1221, thank you for your contribution. I'm wondering how this change can reduce the compaction task failures due to lock contention. Here are what should happen when two or more tasks try to lock overlapped intervals.

- A high priority task is submitted while a low priority task is running. In this case, the high priority task revokes the lock of the low priority task. The low priority task stops with the `FAILED` state.
- A low or equal priority task is submitted while a high or equal priority task is running. In this case, the second task waits (in the `WAITING` state) until the first task releases the lock.

Compaction tasks can fail in the first case above when there is lock contention. However, the new overlord API (`getNonLockIntervalSnapshots()`) can be useful only for the second case by preventing the coordinator from submitting compaction tasks that can lead to lock contention. The `skipOffsetFromLatest` in the auto compaction config should be enough to avoid both cases unless data can arrive late frequently. Or am I missing something?

**Comment by liuxiaohui1221** [comment]
> 
> 
> Hi @liuxiaohui1221, thank you for your contribution. I'm wondering how this change can reduce the compaction task failures due to lock contention. Here are what should happen when two or more tasks try to lock overlapped intervals.
> 
>     * A high priority task is submitted while a low priority task is running. In this case, the high priority task revokes the lock of the low priority task. The low priority task stops with the `FAILED` state.
> 
>     * A low or equal priority task is submitted while a high or equal priority task is running. In this case, the second task waits (in the `WAITING` state) until the first task releases the lock.
> 
> 
> Compaction tasks can fail in the first case above when there is lock contention. However, the new overlord API (`getNonLockIntervalSnapshots()`) can be useful only for the second case by preventing the coordinator from submitting compaction tasks that can lead to lock contention. The `skipOffsetFromLatest` in the auto compaction config should be enough to avoid both cases unless data can arrive late frequently. Or am I missing something?

@jihoonson Thank you for your comments, yes, our data arrieve late frequantely, we collected the data, the specific scenario is as follows: of them around `90%` came from the day, but with `10%` distributed in the last 3 months, I need to set `SkipoffsetFromLatest` large enough to avoid frequent Compact task failure.
I want to success as much as possible the compression of a lot of small files, for this reason, I also want to add a different from `NewestSegmentFirstIterator` iteration strategy: `HighScoreSegmentFirstIterator`, it consider interval, segmentsNum, segmentsSize three factors to calculate the score(like at first,use `Min - Max standardization` to convert these columns,and then intervalScore=w1 * intervalEndTime+w2 * segmentsSize+w3 * segmentsNum), high score interval will submit a compaction task priority.

**Comment by liuxiaohui1221** [comment]
> 
> 
> > Hi @liuxiaohui1221, thank you for your contribution. I'm wondering how this change can reduce the compaction task failures due to lock contention. Here are what should happen when two or more tasks try to lock overlapped intervals.
> > ```
> > * A high priority task is submitted while a low priority task is running. In this case, the high priority task revokes the lock of the low priority task. The low priority task stops with the `FAILED` state.
> > 
> > * A low or equal priority task is submitted while a high or equal priority task is running. In this case, the second task waits (in the `WAITING` state) until the first task releases the lock.
> > ```
> > 
> > 
> > Compaction tasks can fail in the first case above when there is lock contention. However, the new overlord API (`getNonLockIntervalSnapshots()`) can be useful only for the second case by preventing the coordinator from submitting compaction tasks that can lead to lock contention. The `skipOffsetFromLatest` in the auto compaction config should be enough to avoid both cases unless data can arrive late frequently. Or am I missing something?
> 
> @jihoonson Thank you for your comments, yes, our data arrieve late frequantely, we collected the data, the specific scenario is as follows: of them around `90%` came from the day, but with `10%` distributed in the last 3 months, I need to set `SkipoffsetFromLatest` large enough to avoid frequent Compact task failure.
> I want to success as much as possible the compression of a lot of small files, for this reason, I also want to add a different from `NewestSegmentFirstIterator` iteration strategy: `HighScoreSegmentFirstIterator`, it consider interval, segmentsNum, segmentsSize three factors to calculate the score(like at first,use `Min - Max standardization` to convert these columns,and then intervalScore=w1 * intervalEndTime+w2 * segmentsSize+w3 * segmentsNum), high score interval will submit a compaction task priority.

In fact, 90% of the real-time data arrives, the vast majority of the data arrives within the last month, very little data arrives within a month or more.

**Comment by liuxiaohui1221** [comment]
@jihoonson Do you have any suggestions for me, and I already submit a new PR #10863 about new policy: `HighScoreSegmentFirstIterator`.

**Comment by zhangyue19921010** [comment]
Hi @liuxiaohui1221 maybe you can have a try about segment lock instead of timechunk lock.

**Comment by liuxiaohui1221** [comment]
> 
> 
> Hi @liuxiaohui1221 maybe you can have a try about segment lock instead of timechunk lock.

Thanks. segmentLock is experimental, I might need to set both index_kafka & compact tasks lockType to `segmentLock` for it to work. So  I'm worried about some other problems, Have you set any other effects?

**Pull request closed without merging**
