### PR TITLE
Add the ability to supply client certificate to dsql command line tool.

### PR DESCRIPTION
**Pull request by misqos**
### Description

Add the ability to supply client certificate to dsql command line tool.
If the server is configured to do mutual SSL auth, there is no way of making dsql command line tool to work with Druid set up in this way. This PR adds the possibility to supply client certificate parameters, so that the appropriate cert is presented to server.

Added three new flags: `--certchain`, `--keyfile` and `--keypass`. Their values are supplied to `SSLContext`'s `load_cert_chain()` method if they're present.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by clintropolis — APPROVED** [review]
lgtm, thanks for the contribution :+1:

**Comment by suneet-s** [comment]
@misqos Thanks for the contribution! I've re-triggered the failed test because I think it's flaky.

Do you think we should add documentation for this in https://github.com/apache/druid/blob/master/docs/tutorials/tutorial-query.md#query-sql-via-dsql ?

Also, do you think we can add an automated test for this by reusing the current integration test cluster that's set up for the security integration tests? See the tests under the group `TestNGGroup.SECURITY` and the cluster set up in https://github.com/apache/druid/blob/master/integration-tests/docker/docker-compose.security.yml

**Comment by misqos** [comment]
hello @suneet-s
In terms of documentation I am not convinced we should add those details - if we want to do so, we should probably create the rest of documentation for `dsql`, since even the information about `--host` flag is missing. IMO this is beyond the scope of this PR, but I can do that if that's needed for this PR to be merged.
I will take a look at tests later this week.

**Comment by suneet-s** [comment]
> hello @suneet-s
> In terms of documentation I am not convinced we should add those details - if we want to do so, we should probably create the rest of documentation for `dsql`, since even the information about `--host` flag is missing. IMO this is beyond the scope of this PR, but I can do that if that's needed for this PR to be merged.
> I will take a look at tests later this week.

Thanks @misqos! I don't think you need to update the docs on all the different config options. However writing a line or two on why someone would use these new options would be helpful for new users. Something similar to your PR description would be perfect.

**Pull request merged**
