### PR TITLE
Delete buildV9Directly in Kafka and Kinesis Indexing Service

### PR DESCRIPTION
**Pull request by bananaaggle**
Parameter "buildV9Directly" in Kafka and Kinesis tunningConfig will be removed 0.12, but it still reserved in code. I think it is safe to remove it.

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
Thanks for clean up the code. 

I see this parameter is still referenced in 'native-batch.md' but not used in the `ParallelIndexTuningConfig`. Could you delete it from the doc ?

**Comment by bananaaggle** [comment]
> Thanks for cleaning up the code.
> 
> I see this parameter is still referenced in 'native-batch.md' but not used in the `ParallelIndexTuningConfig`. Could you delete it from the doc ?

I find it, but I'm not very sure delete this parameter from batch job is safe.

**Comment by FrankChen021** [comment]
> I find it, but I'm not very sure delete this parameter from batch job is safe.

Actually it's not used in the code, you could check it.

**Comment by bananaaggle** [comment]
> > I find it, but I'm not very sure delete this parameter from batch job is safe.
> 
> Actually it's not used in the code, you could check it.

I delete this method from every where I can find it and pass all unit tests. This is a field in restful API, so I think it's safe to remove it even if some old config had it, because it will not be used and cause no exception.

**Comment by FrankChen021** [comment]
Pls check the CI.

**Comment by bananaaggle** [comment]
> Pls check the CI.

Thanks! Checking now.

**Comment by bananaaggle** [comment]
Hi, @FrankChen021 , happy weekend! I run some integration tests on one EC2 like -Dgroups=batch-index, -Dgroups=query-retry, this branch passed those tests. But it failed on Travis. Is there something wrong for integration tests in Travis?

**Comment by FrankChen021** [comment]
> Hi, @FrankChen021 , happy weekend! I run some integration tests on one EC2 like -Dgroups=batch-index, -Dgroups=query-retry, this branch passed those tests. But it failed on Travis. Is there something wrong for integration tests in Travis?

Might be due to flaky test. I re-triggered the failed tasks. Let's wait to see the result.

**Comment by bananaaggle** [comment]
> > Hi, @FrankChen021 , happy weekend! I run some integration tests on one EC2 like -Dgroups=batch-index, -Dgroups=query-retry, this branch passed those tests. But it failed on Travis. Is there something wrong for integration tests in Travis?
> 
> Might be due to flaky test. I re-triggered the failed tasks. Let's wait to see the result.

Thank you very much!

**Review by FrankChen021 — APPROVED** [review]
👍

**Comment by suneet-s** [comment]
Added release notes, just in case someone is still using this even though it was deprecated for a very long time

If the release manager thinks we don't need to call this out - we can exclude this from the release notes

**Comment by clintropolis** [comment]
>Added release notes, just in case someone is still using this even though it was deprecated for a very long time

This isn't necessary, it looks like this was left in place for upgrades between 0.11 and 0.12, and we just forgot to remove it. It's not hooked into anything, since all of that stuff was removed in #4420.

**Review by clintropolis — APPROVED** [review]

**Comment by zachjsh** [comment]
@bananaaggle there are some dangling references to this property, for example in https://druid.apache.org/docs/latest/ingestion/native-batch.html. Would you mind making a follow-up pr to remove this references?

**Comment by bananaaggle** [comment]
I can clean it. But I think this html is generated according to docs/ingestion/native-batch.md, which is removed this property in master branch. I'm not sure my idea &nbsp;is correct or not. Do you think it's correct? If I was wrong, I would clean it in a &nbsp;follow-up pr.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/druid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 凌晨2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/druid] Delete buildV9Directly in Kafka and Kinesis Indexing Service (#11351)





 
@bananaaggle there are some dangling references to this property, for example in https://druid.apache.org/docs/latest/ingestion/native-batch.html. Would you mind making a follow-up pr to remove this references?

**Pull request merged**
