### PR TITLE
Make dropExisting flag for Compaction configurable and add warning documentations

### PR DESCRIPTION
**Pull request by maytasm**
Make dropExisting flag for Compaction configurable and add warning documentations

### Description
In PR https://github.com/apache/druid/pull/11025 I have introduced a new option for ingestion task to drop (mark unused) all existing segments that are contained by the interval in the ingestionSpec. However, it was pointed out after the PR was merged that this new option can cause temporary data unavailability for data within the specified interval of the ingestion task. Compaction task created manually and by auto compaction were hardcoded to always use the new dropExisting flag in PR https://github.com/apache/druid/pull/11025. This PR make dropExisting flag for Compaction task configurable and set the default behavior when dropExisting is not specified to not use the dropExisting functionality (which is the same behavior as before the PR https://github.com/apache/druid/pull/11025). This PR also adds documentation with warning to temporary data unavailability if dropExisting flag is used.

**This PR does not contain the fix for this problem yet. The fix will come later.**

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by jihoonson** [comment]
@asdf2014 I removed the 0.21.0 milestone because this PR is a follow-up of https://github.com/apache/druid/pull/11025 which was merged into only master.

**Comment by loquisgon** [comment]
LGTM

**Comment by asdf2014** [comment]
@jihoonson Sure, thanks.

**Review by zachjsh — APPROVED** [review]
LGTM

**Pull request merged**
