### PR TITLE
Add LoadDropByPeriod to improve retention rules

### PR DESCRIPTION
**Pull request by 599166320**
Fixes [#13080](https://github.com/apache/druid/issues/13080).

### Description

The existing retention rules cannot handle the following cases well:

Data upto 3 days old lives on  default tiers
Data more than 3 days old and upto 7 days old lives only on cold tier
older data is dropped

This case can be handled by the following retention rules:
```
loadByPeriod P3D _defaultTier
loadByPeriod P7D cold
dropForever
```

This retention rule can improve the tier query at the router level, but default tier stores the data of the last 7 days, which will waste the storage of default tier.

 By configuring the following retention rules, you can perfectly solve the problem of _defaultTier resource waste, without affecting the existing retention rules

```
loadDropByPeriod P3D _defaultTier
loadDropByPeriod P7D cold
dropForever
```

<hr>

##### Key changed/added classes in this PR
 * `RunRules`
 * `LoadDropByPeriod`
 * `PeriodLoadRule`
 * `Rule`

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by kfaraz** [comment]
@599166320 , thanks for the changes.

I don't think these changes are really needed. The existing load rules are meant to handle the use case that you mention in the issue #13080 . You seem to have configured your rules correctly, but the segments that are moved to cold tier are not being fully dropped from the default tier.

You might need to look at your logs and metrics to figure out the real root cause. Please let us know how we can help you debug the issue. I would also advise you to join the Druid slack:
[https://druid.apache.org/community/join-slack](https://druid.apache.org/community/join-slack?v=1)
It's a great forum for troubleshooting and discussing improvements.

Alongwith this, there are also some segment loading improvements currently in progress, which should further mitigate such problems in the future. #12881

**Comment by 599166320** [comment]
@kfaraz Thank you for your tips. After checking, I found that the expired data in the large table was not deleted in time. The small table is normal. Because the storage cost is too expensive, LoadDropByPeriod can delete expired data in a timely manner. I plan to use LoadDropByPeriod to solve the problem of deleting expired data.

**Comment by 599166320** [comment]
In addition, it is suggested to increase maxSegmentsToMove, but it will lead to a large number of replica migrations in the entire cluster, which is easy to fail and cannot solve the current problem.
Also, if the data in the large table is not deleted in time, the data in the small table will also have problems.

**Comment by kfaraz** [comment]
As described [here](https://github.com/apache/druid/pull/13121#issuecomment-1251945766), the root cause of the issue is probably something else.

[This comment](https://github.com/apache/druid/issues/13080#issuecomment-1250095588) also discusses an approach to tackle outlier cases. But I am still not sure if that case applies here. 

@599166320 , I would advise you to close this PR and share more information on the issue #13080 or preferably on Druid slack so that the community can help you debug the issue.

**Comment by 599166320** [comment]
> 

Thanks for your help, I have closed it

**Comment by 599166320** [comment]
At present, our production environment has added LoadDropByPeriod. The changes are slightly different from this pr. It runs normally. If I have time later, I will deploy a large-scale test cluster to see if this problem can recur and provide more information.

**Pull request closed without merging**
