### PR TITLE
Update the link of Helm Chart to avoid 404 error

### PR DESCRIPTION
**Pull request by asdf2014**
### Description

Because a new code repository has been created to maintain the Helm Chart for Apache Druid, the links inside the README have been updated to avoid 404 error. We can merge this after https://github.com/apache/druid/pull/15904

<hr>

This PR has:

- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] a release note entry in the PR description.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
How about leaving a note in docs that point to your repo? So someone searching for helm charts could at least find the charts in your repo.

**Comment by asdf2014** [comment]
@abhishekagarwal87 Yes, that'll be great. Please feel free to raise another PR to add note in docs, meanwhile let's focus on updating the links here, how does that sound to you :smile:

**Comment by abhishekagarwal87** [comment]
Why not do it in this PR itself? :)

**Comment by asdf2014** [comment]
@abhishekagarwal87 I think we should ensure that the content of the PR closely aligns with the theme as much as possible. Content with weaker relevance can be included in subsequent PRs, making it easier to review the code. :)

**Review by FrankChen021 — APPROVED** [review]
Let's fix the link first

**Pull request merged**
