### PR TITLE
fix issue with SQL sum aggregator due to bug with DruidTypeSystem and AggregateRemoveRule

### PR DESCRIPTION
**Pull request by clintropolis**
### Description
This PR fixes an issue that occurs when using a `SUM` function in sub-query that is a result of a bug in the version of Calcite that we are using in `SqlSplittableAggFunction.AbstractSumSplitter`. Queries impacted will be of this form and involve INTEGER (or FLOAT) literals:

```
SELECT
  dim1,
  SUM(CASE WHEN sum_l1 = 0 THEN 1 ELSE 0 END) AS outer_l1
from (
  select
    dim1,
    SUM(l1) as sum_l1
  from numfoo
  group by dim1
)
group by 1
```

This issue is described by https://issues.apache.org/jira/browse/CALCITE-4609 and was fixed by https://github.com/apache/calcite/commit/c96d85ccad32cbdc9b52b5e2488887ed14a1b5ec.

The problem arises because `RelDataTypeSystem` implementations are allowed to define the built-in `SUM` function return type inference via [`deriveSumType`](https://github.com/apache/druid/blob/master/sql/src/main/java/org/apache/druid/sql/calcite/planner/DruidTypeSystem.java#L102) which we have done, however in our version [`AggregateRemoveRule`](https://github.com/apache/calcite/blob/branch-1.21/core/src/main/java/org/apache/calcite/rel/rules/AggregateRemoveRule.java#L112) attempts to simplify the query using `SqlSplittableAggFunction.singleton`, which "Generates an expression for the value of the aggregate function when applied to a single row." in this case, to compare the subquery signature to the outer signature to see if it can remove the outer aggregate (and eventually collapse the outer and inner query).

The default [implementation of this for `SUM`](https://github.com/apache/calcite/blob/branch-1.21/core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java#L263) however just passes through the argument as the output, which in this case is an `INTEGER` literal, instead of a `BIGINT` which the Druid type system would have chosen if it was consulted.

This is the part of the bug, and for my fix I have duplicated `SqlSumAggFunction` as `DruidSumAggFunction` and overwritten `unwrap` to use a new `DruidSumSplitter` which checks to see if the type of the `aggregateCall` is the same as the type of the argument, otherwise it will wrap the identifier in a cast expression to ensure it is the correct type.

Without this, the query planning fails with an error like
```
java.lang.AssertionError: Type mismatch:
rowtype of new rel:
RecordType(VARCHAR dim2, BIGINT NOT NULL outer_l2) NOT NULL
rowtype of set:
RecordType(VARCHAR dim2, INTEGER NOT NULL $f1) NOT NULL
```

This is already fixed upstream, where [`AggregateRemoveRule`](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/rel/rules/AggregateRemoveRule.java#L112) now ensures that the output of `singleton` is the correct type or casts it, which is basically what I've done here. We will no longer need this change once we can upgrade to a newer version of Calcite.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by clintropolis** [comment]
This could also be fixed by making a fixed version of `AggregateRemoveRule` and using that instead of one built-in to our version of Calcite, I don't feel super strongly either way.

**Review by gianm — APPROVED** [review]

**Comment by calummiller** [comment]
Unfortunately Druid 24.0 and and 24.0.1 sill contain calcite 1.21.0. We tried replacing with calcite 1.27 but see the following error 

2022-11-30T09:39:39,807 ERROR [main] org.apache.druid.cli.CliBroker - Error when starting up.  Failing.
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects

**Comment by abhishekagarwal87** [comment]
We have not upgraded Calcite library yet. That cannot happen till we get rid of guava dependencies coming from Hadoop 2.

**Comment by calummiller** [comment]
Thanks for the feedback. We did notice that this sum issue does not happen when a join is used in the outer SQL aggregation. This temporary hack may help some users until the calcite library is upgraded.

**Pull request merged**
