### PR TITLE
Add new metrics from v30 to prometheus-emitter

### PR DESCRIPTION
**Pull request by ztzxt**
#### Added new metrics for prometheus emitter

This PR has:

- [ ] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by ztzxt** [comment]
Newly introduced metrics in druid release v30 are added per @cryptoe's comment https://github.com/apache/druid/pull/16340#issuecomment-2080504820

**Review by cryptoe — APPROVED** [review]

**Comment by cryptoe** [comment]
Thank you @ztzxt

**Comment by cryptoe** [comment]
@ztzxt Could you please rebase this patch on top of the latest master. Post that CI will run

**Comment by ztzxt** [comment]
hi @cryptoe I just saw your comment. it should be good to go now

**Review by asdf2014 — APPROVED** [review]

**Comment by cryptoe** [comment]
Thank you for the patch @ztzxt . Looking forward to more contributions from you

**Pull request merged**
