### PR TITLE
[Backport] Fix json inputs for drill windowing tests

### PR DESCRIPTION
**Pull request by kgyrtkirk**
Backport of #15148 to 28.0.0.

### CODE REVIEW

**Comment by cryptoe** [comment]
@kgyrtkirk Looks like failure are legit. 
```
Error:  Failures: 
Error:  org.apache.druid.sql.calcite.DrillWindowQueryTest.test_frameclause_RBUPACR_RBUPACR_dt_4
Error:    Run 1: DrillWindowQueryTest.test_frameclause_RBUPACR_RBUPACR_dt_4:7856->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 2: DrillWindowQueryTest.test_frameclause_RBUPACR_RBUPACR_dt_4:7856->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 3: DrillWindowQueryTest.test_frameclause_RBUPACR_RBUPACR_dt_4:7856->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 4: DrillWindowQueryTest.test_frameclause_RBUPACR_RBUPACR_dt_4:7856->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
[INFO] 
Error:  org.apache.druid.sql.calcite.DrillWindowQueryTest.test_frameclause_RBUPAUF_RBUPAUF_dt_4
Error:    Run 1: DrillWindowQueryTest.test_frameclause_RBUPAUF_RBUPAUF_dt_4:7283->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 2: DrillWindowQueryTest.test_frameclause_RBUPAUF_RBUPAUF_dt_4:7283->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 3: DrillWindowQueryTest.test_frameclause_RBUPAUF_RBUPAUF_dt_4:7283->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 4: DrillWindowQueryTest.test_frameclause_RBUPAUF_RBUPAUF_dt_4:7283->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
[INFO] 
Error:  org.apache.druid.sql.calcite.DrillWindowQueryTest.test_frameclause_defaultFrame_RBUPACR_dt_4
Error:    Run 1: DrillWindowQueryTest.test_frameclause_defaultFrame_RBUPACR_dt_4:6816->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 2: DrillWindowQueryTest.test_frameclause_defaultFrame_RBUPACR_dt_4:6816->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 3: DrillWindowQueryTest.test_frameclause_defaultFrame_RBUPACR_dt_4:6816->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
Error:    Run 4: DrillWindowQueryTest.test_frameclause_defaultFrame_RBUPACR_dt_4:6816->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT FIRST_VALUE(c7) OVER(PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM "t_alltype.parquet": arrays first differed at element [0]; expected:<null> but was:<0>
[INFO] 
Error:  org.apache.druid.sql.calcite.DrillWindowQueryTest.test_frameclause_subQueries_frmInSubQry_59
Error:    Run 1: DrillWindowQueryTest.test_frameclause_subQueries_frmInSubQry_59:7353->windowQueryTest:484->BaseCalciteQueryTest.assertResultsEquals:1198 result #141: SELECT
      *
      
```

**Comment by LakshSingla** [comment]
https://github.com/apache/druid/pull/15205 has not been backported yet, perhaps that might be causing this failure.

**Comment by kgyrtkirk** [comment]
thank you @cryptoe and @LakshSingla 
yes; these cases depend on the order quite a bit

**Comment by LakshSingla** [comment]
Restarting CI since the other backport is merged.

**Comment by cryptoe** [comment]
I guess @kgyrtkirk would have to pull the changes from 28.0 branch again and merge them in kgyrtkirk:backport-15148-to-28.0.0

**Comment by LakshSingla** [comment]
The CI merges with the base branch before creating a build, so that won't be required.

**Comment by kgyrtkirk** [comment]
oh...I've just merged it and pushed...

**Pull request merged**
