### PR TITLE
Enable vectorized virtual column processing by default.

### PR DESCRIPTION
**Pull request by gianm**
In the majority of cases, this improves performance.

There's only one case I'm aware of where this may be a net negative: for `time_floor(__time, <period>)` where there are many repeated `__time` values. In nonvectorized processing, SingleLongInputCachingExpressionColumnValueSelector implements an optimization to avoid computing the `time_floor` function on every row. There is no such optimization in vectorized processing.

IMO, we shouldn't mention this in the docs. Rationale: It's too fiddly of a thing: it's not guaranteed that nonvectorized processing will be faster due to the optimization, because it would have to overcome the inherent speed advantage of vectorization. So it'd always require testing to determine the best setting for a specific dataset. It would be bad if users disabled vectorization thinking it would speed up their queries, and it actually slowed them down. And even if users do their own testing, at some point in the future we'll implement the optimization for vectorized processing too, and it's likely that users that explicitly disabled vectorization will continue to have it disabled. I'd like to avoid this outcome by encouraging all users to enable vectorization at all times. Really advanced users would be following development activity anyway, and can read this issue 🙂

### CODE REVIEW

**Review by suneet-s — APPROVED** [review]
🚀

**Comment by suneet-s** [comment]
What are your thoughts on making this part of the 0.23.0 release? We just missed the cutoff, but I don't see a big risk in back-porting this change to the upcoming release.

**Comment by gianm** [comment]
> What are your thoughts on making this part of the 0.23.0 release? We just missed the cutoff, but I don't see a big risk in back-porting this change to the upcoming release.

It's up to @abhishekagarwal87 (release manager for 0.23.0). IMO, it'd be good to get this change out there as soon as practicable.

**Comment by gianm** [comment]
Fixed one of the tests.

**Comment by abhishekagarwal87** [comment]
+1 on back-porting since it's going to improve the performance for many users.

**Comment by abhishekagarwal87** [comment]
Backport PR - https://github.com/apache/druid/pull/12525

**Pull request merged**
