### PR TITLE
Dimension dictionary reduce locking

### PR DESCRIPTION
**Pull request by jasonk000**
### Description

Following from https://github.com/apache/druid/pull/12105 with 1-20% CPU in `DimensionDictionary`, there are some improvements to be made to the `add()` path on the `StringDimensionIndexer`. The main concern is that the locking is more complicated than necessary.

There are three sub-changes:
- Introduce a benchmark
- Swap the existing lock implementation to use a StampedLock
- Reduce the number of times we have to cross the lock

Estimate this code reduces CPU by ~5-7% on our indexing jobs overall, with ~30% improvements to the uncontended path.

### Related

#12105, #12109, 

##### Key changed/added classes in this PR
 * Introduce benchmark `StringDimensionIndexerProcessBenchmark`
 * `DimensionDictionary` locking changes

<hr>

This PR has:

- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] been tested in a test Druid cluster. -- a solution more like 12105 on top of 0.20 is currently running in Production for many months.

### CODE REVIEW

**Comment by jasonk000** [comment]
@kfaraz I started a conversation on slack; I think this is in a similar area you've been working recently. CC @maytasm

**Comment by clintropolis** [comment]
it would probably be worth checking that query performance for realtime tasks is not negatively impacted too much by this change (especially from multiple concurrent threads). There is only one writer thread but potentially many reader threads, as new dimension selectors are created on top of this dictionary during realtime queries.

For batch ingestion tasks, it might be worth using a separate `DimensionDictionary` implementation that has no locks. I use a similar thing for the `NestedDataColumnIndexer`, `ComparatorDimensionDictionary`, which is basically a copy of `DimensionDictionary` except uses a `Comparator` instead of requiring a `Comparable`, and doesn't have any locks since the nested column indexer doesn't currently use the dictionary it is building for realtime queries.

**Comment by jasonk000** [comment]
@clintropolis , thx for comments. I think it's ready to take a look at.

I've included benchmark results [for each commit](https://github.com/apache/druid/pull/13710/commits), and shown the progress. Each commit is broken to a small change so if we would prefer distinct PRs we can do that too.

> it would probably be worth checking that query performance for realtime tasks is not negatively impacted too much by this change (especially from multiple concurrent threads). There is only one writer thread but potentially many reader threads, as new dimension selectors are created on top of this dictionary during realtime queries.

I've added test explicitly for the contended situation and brought in StampedLock which has much better performance with mixed read workloads.

It looks to me like most of the time it is one-thread-writing with possibly many readers, so I think this is a good blend. We could build a more advanced ArrayList structure that would be lockfree since this is append-only, but i'm not sure it's warranted. Let me know your thoughts.

> For batch ingestion tasks, it might be worth using a separate `DimensionDictionary` implementation that has no locks. I use a similar thing for the `NestedDataColumnIndexer`, 

I included a benchmark for single-writer only and it shows up with similar performance to the contended writer situation.

Overall, for JDK11, 

BEFORE
```
jdk11 -- Benchmark                                                       Mode  Cnt      Score     Error  Units
StringDimensionIndexerProcessBenchmark.parallelReadWrite                 avgt   10  18769.135 ± 705.057  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelReader  avgt   10  23772.439 ± 947.011  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelWriter  avgt   10   3759.221 ±  59.897  us/op
StringDimensionIndexerProcessBenchmark.soloReader                        avgt   10    666.688 ±  12.723  us/op
StringDimensionIndexerProcessBenchmark.soloWriter                        avgt   10   3013.473 ±  13.480  us/op
```

AFTER
```
jdk11 - Benchmark                                                        Mode  Cnt     Score    Error  Units
StringDimensionIndexerProcessBenchmark.parallelReadWrite                 avgt   10   873.654 ± 12.358  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelReader  avgt   10   283.315 ±  0.067  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelWriter  avgt   10  2644.672 ± 49.549  us/op
StringDimensionIndexerProcessBenchmark.soloReader                        avgt   10   284.451 ±  0.588  us/op
StringDimensionIndexerProcessBenchmark.soloWriter                        avgt   10  2284.851 ± 51.339  us/op
```

Overall, both the contended and solo read/write is all improved.

**Comment by clintropolis** [comment]
cool, thanks for checking. Btw, I actually had a bug in that lockless dictionary used by nested columns that resulted in it not fully merging dictionaries which is fixed in this PR https://github.com/apache/druid/pull/13714/files#diff-b00489e26a5bff0e308349f4bdf8dc21a55798f8d0f35c995c56599cb6485eb1R93 😅

anyway, I'll try to have a closer look at this PR sometime soon

**Comment by jasonk000** [comment]
Made a typo in the old test cases, so I've rebased the lot and reprocessed the tests, which confirmed another opt I had in mind. Updated results:
```
BEFORE
jdk11 -- Benchmark                                                       Mode  Cnt      Score     Error  Units
StringDimensionIndexerProcessBenchmark.parallelReadWrite                 avgt   10  30471.552 ±  456.716  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelReader  avgt   10  18069.863 ±  327.923  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelWriter  avgt   10  67676.617 ± 2351.311  us/op
StringDimensionIndexerProcessBenchmark.soloReader                        avgt   10   1048.079 ±    1.120  us/op
StringDimensionIndexerProcessBenchmark.soloWriter                        avgt   10   4629.769 ±   29.353  us/op

AFTER
jdk11 - Benchmark                                                        Mode  Cnt      Score    Error  Units
StringDimensionIndexerProcessBenchmark.parallelReadWrite                 avgt   10   2914.859 ± 22.519  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelReader  avgt   10    508.010 ± 14.675  us/op
StringDimensionIndexerProcessBenchmark.parallelReadWrite:parallelWriter  avgt   10  10135.408 ± 82.745  us/op
StringDimensionIndexerProcessBenchmark.soloReader                        avgt   10    205.415 ±  0.158  us/op
StringDimensionIndexerProcessBenchmark.soloWriter                        avgt   10   3098.743 ± 23.603  us/op
```

**Review by clintropolis — APPROVED** [review]
lgtm :+1:

**Pull request merged**
