### PR TITLE
Add Pig-specific file handling to Avro parser

### LINKED ISSUE #9211: Reanimate Pig specific handling in the Avro parser
### Description

Apache Pig dependencies as well as related functionality were removed from the Avro parser in #7810 
We internally use Pig extensively and the Pig specific transformation within the Avro parser extension is useful for us especially for parsing data bags. I would like to add the `fromPigAvroStorage` flag based processing back to the Avro Parser. In terms of tests, I can find a way to test this without adding the Pig dependency back.
I apologize for missing out on raising this concern on the original PR.

Any objections @gianm @Fokko ?

### PR DESCRIPTION
**Pull request by a2l007**
Fixes #9211 .

### Description

Adds Pig-specific data file handling back to the  avro hadoop parser. The tests are no longer dependent on Apache Pig since the dependency was the primary reason why the functionality was removed.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added unit tests or modified existing tests to cover new code paths.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by gianm** [comment]
@a2l007 Could you please add `fromPigAvroStorage` and `AvroStorage` to the spellcheck file?

(See https://travis-ci.org/apache/druid/jobs/642082497)

**Comment by a2l007** [comment]
@gianm Fixed that, but it looks like build is timing out now. Could you please restart the build?

**Comment by jihoonson** [comment]
Restarted the failed one.

**Comment by jihoonson** [comment]
@a2l007 thanks for the fix!

**Pull request merged**
