### PR TITLE
Return HTTP 404 instead of 400 for supervisor/task endpoints

### PR DESCRIPTION
**Pull request by FrankChen021**
### Description

We're using supervisor/task HTTP APIs to manage supervisor and tasks in a independent system. Current supervisor/task  endpoint return 400 when a supervisor or a task is not found. This status code is not friendly and confusing for the 3rd system. And according to the definition of HTTP status code,  404 is right code for such case. So this PR changes the status code from 400 to 404 to eliminate the ambigiuty.

This PR has:
- [X] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [X] added integration tests.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

**Review by jihoonson — COMMENTED** [review]
This change seems reasonable. @FrankChen021 can you add some tests for this change?

**Comment by FrankChen021** [comment]
> This change seems reasonable. @FrankChen021 can you add some tests for this change?

Sure, I will add some tests later this week.

**Review by suneet-s — COMMENTED** [review]
+1 from me after tests. Returning 404 instead of 400 seems more like a bug fix vs introducing an incompatible change so I'm also ok with this without a feature flag to fall back to the old behavior for any users who wouldn't want to incorporate this change on an upgrade.

**Review by suneet-s — APPROVED** [review]

**Review by asdf2014 — APPROVED** [review]
👍 LGTM

**Review by jihoonson — APPROVED** [review]
LGTM. Thanks @FrankChen021!

**Comment by FrankChen021** [comment]
@jihoonson @asdf2014 @suneet-s @kfaraz Thank you for your review.

**Pull request merged**
