### PR TITLE
Support join in decoupled mode

### PR DESCRIPTION
**Pull request by kgyrtkirk**
* plan join(s) in decoupled mode
* configure `DecoupledPlanningCalciteJoinQueryTest`
   * the test has `593` cases; however there are quite a few parameterized
   * from the `107` methods annotated with `@Test` - `42` is not yet working
* replace the `isRoot` hack in `DruidQueryGenerator` with a logic that instead looks ahead for the next node; and doesn't let the previous node do the `Project` - this makes it plan more likely than the existing planner

here is a summary of the not-yet-working cases:

| class | num | annotation |
| ---- | --- | --- |
 | CalciteJoinQueryTest | 12 | JOIN_CONDITION_NOT_PUSHED_CONDITION |
 | CalciteJoinQueryTest | 10 | JOIN_TABLE_TABLE | 
 | CalciteJoinQueryTest | 8 | JOIN_CONDITION_UNSUPORTED_OPERAND | 
 | CalciteJoinQueryTest | 4 | CORRELATE_CONVERSION | 
 | CalciteJoinQueryTest | 3 | UNION_WITH_COMPLEX_OPERAND | 
 | CalciteJoinQueryTest | 2 | CANNOT_JOIN_LOOKUP_NON_KEY | 
 | CalciteJoinQueryTest | 1 | SORT_REMOVE_TROUBLE | 
 | CalciteJoinQueryTest | 1 | STACK_OVERFLOW | 
 | CalciteQueryTest | 2 | ERROR_HANDLING | 
 | CalciteQueryTest | 2 | UNION_WITH_COMPLEX_OPERAND | 
 | CalciteQueryTest | 1 | JOIN_CONDITION_NOT_PUSHED_CONDITION | 

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by imply-cheddar — APPROVED** [review]
This seems low risk as it's primarily just changing things for decoupled mode.  Some logic was moved to static methods in order to make the logic reusable, but that should be fine.

**Review by cheddar — APPROVED** [review]
Leaving a green check

**Comment by cheddar** [comment]
If you can resolve the conflicts, I see that it's all green now and the one failure with codeQL is okay to ignore.

**Comment by adithyachakilam** [comment]
@cheddar 

CI for all PRs failing with below error:

```
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/druid/druid/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:[15310,25] cannot find symbol
  symbol:   variable MISSING_JOIN_CONVERSION
  location: class org.apache.druid.sql.calcite.NotYetSupported.Modes
Error:  /home/runner/work/druid/druid/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:[15343,25] cannot find symbol
  symbol:   variable MISSING_JOIN_CONVERSION
  location: class org.apache.druid.sql.calcite.NotYetSupported.Modes
[INFO] 2 errors 
```

**Pull request merged**
