### PR TITLE
doc: fix markdown spacing

### PR DESCRIPTION
**Pull request by 317brian**
Fixes an extra blank code block

This PR has:

- [x] been self-reviewed.

### CODE REVIEW

**Review by amaechler — APPROVED** [review]
🐻

**Review by paul-rogers — APPROVED** [review]
LGTM

**Comment by kfaraz** [comment]
The lines above seem misaligned too. Maybe we align these too in this PR?

https://github.com/apache/druid/blob/fb26a1093d11f0574dbb905ac0d39c8eb3777312/docs/tutorials/tutorial-jupyter-index.md?plain=1#L45-L56

**Review by techdocsmith — APPROVED** [review]
LGTM & thanks for addressing @kfaraz comments

**Pull request merged**
