### PR TITLE
Add Spark Writer support.

### PR DESCRIPTION
**Pull request by JulianJaffePinterest**
Add code, utilities, tests, and documentation for writing data to Druid using Spark.

This is the final piecemeal PR recapitulating #10920 (see #11474 and #11823 for the previous two).

### Description

This connector writes Druid segment files to deep storage, one per input Spark partition. The connector also writes the segment descriptions to the Druid metadata SQL server, at which point the normal Druid coordination process handles loading, atomic updating,  and overshadowing.

#### Writing Segments

Each Spark partition is assigned to an executor. For each partition, one or more `IncrementalIndex` is created and passed the rows in the source Spark partition for the index's interval. The indices are flushed to local storage while being built before being pushed to deep storage. Internally, this writer uses a two-phase commit model to push segments: if all Spark partitions are successfully written to Druid segment files on deep storage, the segment metadata is published and the Druid segment coordination process takes over. However, if one or more partitions fail, the write is aborted, the segments already written to deep storage are deleted, and control is passed back to Spark for error handling.

##### Key Classes

`DruidDataSourceWriter`
`DruidWriterFactory`
`DruidDataWriter`

#### Partitioning

Spark's architecture means that the source dataframe is already partitioned by the time this writer is called. By default, this writer will attempt to "rationalize" input segments such that all covered time intervals are contiguous and complete. This means that Druid can atomically load and overshadow the produced segments but doesn't prevent sub-optimal partitioning from passing through from Spark to Druid. To address this issue, callers can partition their dataframes themselves and pass the writer a partition map describing the partitioning scheme. The writer provides four partitioners out of the box that callers can use as well (see the [docs](docs/operations/spark.md#provided-partitioners) for more information).

##### Key Classes

`SegmentRationalizer`
`org.apache.druid.spark.partitioners.*`

#### User Interface

Users call this writer like any other Spark writer: they call `.write()` on a DataFrame, configure their writer if desired, and then call `.save()`. Like the reader introduced in #11823, there is also a more ergonomic and type-safe wrapper if desired. As always, the documentation contains a complete configuration reference with further examples.

Example configuration:

```scala
val metadataProperties = Map[String, String](
  "metadata.dbType" -> "mysql",
  "metadata.connectUri" -> "jdbc:mysql://druid.metadata.server:3306/druid",
  "metadata.user" -> "druid",
  "metadata.password" -> "diurd"
)

val writerConfigs = Map[String, String] (
  "table" -> "dataSource",
  "writer.version" -> 1,
  "writer.deepStorageType" -> "local",
  "writer.storageDirectory" -> "/mnt/druid/druid-segments/"
)

df
  .write
  .format("druid")
  .mode(SaveMode.Overwrite)
  .options(Map[String, String](writerConfigs ++ metadataProperties))
  .save()
```

or using the convenience wrapper:

```scala
import org.apache.druid.spark.DruidDataFrameWriter

val deepStorageConfig = new LocalDeepStorageConfig().storageDirectory("/mnt/druid/druid-segments/")

df
  .write
  .metadataDbType("mysql")
  .metadataUri("jdbc:mysql://druid.metadata.server:3306/druid")
  .metadataUser("druid")
  .metadataPassword("diurd")
  .version(1)
  .deepStorage(deepStorageConfig)
  .mode(SaveMode.Overwrite)
  .dataSource("dataSource")
  .druid()
```

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by JulianJaffePinterest** [comment]
@jihoonson @samarthjain this is the final spark connector pr 🙂

**Comment by ilhanadiyaman** [comment]
Hi @JulianJaffePinterest, thank you for your great work. We consider using this connector in the production, however, while testing this PR, we encountered an error while writing the segment that includes `thetaSketch`. 

We first read a segment directly from the deep storage by providing the `reader.segments`.  

| number | count | animal  | __time        | animalTheta                                       |
|--------|-------|---------|---------------|---------------------------------------------------|
| 32     | 1     | bear | 1515459660000 | [01 03 03 00 00 3A CC 93 5E 90 53 47 FF 46 AD 47] |
| 3      | 1     | bird    | 1515466860000 | [01 03 03 00 00 3A CC 93 AA 00 F4 1D D3 FF F8 14] |
| 4      | 1     | tiger   | 1515466860000 | [01 03 03 00 00 3A CC 93 28 32 FA 04 88 6A BA 4B] |

Then we updated the `bear` to `giraffe` and try to write back the segment with `writer.metrics` and `writer.dimensions` provided.

| number | count | animal  | __time        | animalTheta                                       |
|--------|-------|---------|---------------|---------------------------------------------------|
| 32     | 1     | giraffe | 1515459660000 | [01 03 03 00 00 3A CC 93 91 0C 5B F9 33 1B E6 17] |
| 3      | 1     | bird    | 1515466860000 | [01 03 03 00 00 3A CC 93 AA 00 F4 1D D3 FF F8 14] |
| 4      | 1     | tiger   | 1515466860000 | [01 03 03 00 00 3A CC 93 28 32 FA 04 88 6A BA 4B] |

```java
writeOptions.put("writer.dimensions","[ \"animal\" ]");
writeOptions.put("writer.metrics","[ { \"type\": \"count\", \"name\": \"count\" }, { \"type\": \"longSum\", \"name\": \"number\", \"fieldName\": \"number\" }, { \"name\": \"animalTheta\", \"type\": \"thetaSketch\", \"fieldName\": \"animal\", \"isInputThetaSketch\": true } ]");
```

Write operation fails with the error below:

`
org.apache.druid.java.util.common.ISE: Object is not of a type[class org.apache.spark.unsafe.types.UTF8String] that can be deserialized to sketch.
	at org.apache.druid.query.aggregation.datasketches.theta.SketchHolder.deserialize(SketchHolder.java:223) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.query.aggregation.datasketches.theta.SketchMergeComplexMetricSerde$1.extractValue(SketchMergeComplexMetricSerde.java:62) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.query.aggregation.datasketches.theta.SketchMergeComplexMetricSerde$1.extractValue(SketchMergeComplexMetricSerde.java:50) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.serde.ComplexMetricExtractor.extractValue(ComplexMetricExtractor.java:41) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.incremental.IncrementalIndex$1IncrementalIndexInputRowColumnSelectorFactory$1.getObject(IncrementalIndex.java:184) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.query.aggregation.datasketches.theta.SketchAggregator.aggregate(SketchAggregator.java:54) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.incremental.OnheapIncrementalIndex.doAggregate(OnheapIncrementalIndex.java:254) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:167) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:481) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:462) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.spark.v2.writer.DruidDataWriter.write(DruidDataWriter.scala:171) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.spark.v2.writer.DruidDataWriter.write(DruidDataWriter.scala:68) ~[druid-spark.jar:0.22.0-SNAPSHOT]
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$2(WriteToDataSourceV2Exec.scala:118) ~[spark-sql_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394) ~[spark-core_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:116) ~[spark-sql_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.$anonfun$doExecute$2(WriteToDataSourceV2Exec.scala:67) ~[spark-sql_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) ~[spark-core_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.scheduler.Task.run(Task.scala:123) ~[spark-core_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:414) ~[spark-core_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360) [spark-core_2.12-2.4.8.jar:2.4.8]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417) [spark-core_2.12-2.4.8.jar:2.4.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
`

Tried to debug it but couldn't get anywhere. It seems like it tries to deserialize `UTF8String` but we provide thetaSketches as `byte array`.

Screenshot 2022-01-27 at 23 54 02

Do you have any ideas how we can resolve this issue?

P.S. Azure Deep Storage implementation is working. We didn't encounter any problem there.

**Comment by ilhanadiyaman** [comment]
Hi @JulianJaffePinterest, you can ignore my previous comment. The error was the definition of thetaSketch in the `writer.metrics`. Thank you again for great work!

**Comment by Lakomoff** [comment]
Hi,
Is it true that this functionality is not present in official release of Druid?
From where Is possible to download compiled jar-file for latest version of connector? If there are only source files I'v got the same question....
I am not using github a lot and can not find a way to download only a branch that contains source code for this extension.

**Comment by wangxiaobaidu11** [comment]
@JulianJaffePinterest  hi, I import a month's data to druid by spark connector. The data is partitioned by day. The number of lines per segment is in the tens of millions.
image
In my tests, I found that the import job took about an hour. How can I speed up the import?  Whether the segment can be split into numShard format for import?

**Comment by JulianJaffePinterest** [comment]
@Lakomoff you are correct, this pull request has not yet been merged into the main Druid branch. You can view the source code [here](https://github.com/JulianJaffePinterest/druid/tree/spark_druid_piecemeal_writer) - the connector code is in the spark module (for future reference, you can click the link at the top of a pr to access the source and target branches)
image

**Comment by JulianJaffePinterest** [comment]
@wangxiaobaidu11 there are a number of factors that affect the runtime of this connector. I don't know the specifics of your data, but it looks like you're trying to use a single-dimension partitioner on a timestamp. If that timestamp is the druid time column, you don't need to do that partitioning yourself - all druid segments are partitioned on the time column regardless of any other partitioning. In your case, the segments you're generating are probably ok size-wise (~200 MB) but if you wanted them to have fewer rows (and thus have more, smaller segments) you could use the numbered partitioner with a  target row count. This would increase the parallelism of your spark job and allow your writing to happen sooner, but could slow down your query speed. You'll have to use your judgement on what's more important to you. You might also want to look at the metrics for your import jobs and determine exactly where time is being spent - if the time it takes to read in data is small and the job spends most of its time writing to druid, you could check if you're memory-bound on your job (in which case giving your executors more memory will help) or cpu-bound (in which case you'll need to trade off more executors for more files). If you're reading from an external system you also may be able to shape your reads in such a way as to minimize or eliminate shuffling in Spark, which will greatly speed up your write. Keep in mind that the provided partitioners don't have any knowledge of your data and so will be slower than a partitioning approach that can take your data in to account.

More generally, the writing logic is some of the oldest in the connectors and there is likely substantial room for improvement in performance. Because the write performance has been mostly acceptable to users, I've been focused on getting these connectors merged into Druid rather than further latency or throughput improvements but hopefully Druid committers like @jihoonson will have some useful feedback in their reviews.

**Comment by wangxiaobaidu11** [comment]
> @wangxiaobaidu11 there are a number of factors that affect the runtime of this connector. I don't know the specifics of your data, but it looks like you're trying to use a single-dimension partitioner on a timestamp. If that timestamp is the druid time column, you don't need to do that partitioning yourself - all druid segments are partitioned on the time column regardless of any other partitioning. In your case, the segments you're generating are probably ok size-wise (~200 MB) but if you wanted them to have fewer rows (and thus have more, smaller segments) you could use the numbered partitioner with a target row count. This would increase the parallelism of your spark job and allow your writing to happen sooner, but could slow down your query speed. You'll have to use your judgement on what's more important to you. You might also want to look at the metrics for your import jobs and determine exactly where time is being spent - if the time it takes to read in data is small and the job spends most of its time writing to druid, you could check if you're memory-bound on your job (in which case giving your executors more memory will help) or cpu-bound (in which case you'll need to trade off more executors for more files). If you're reading from an external system you also may be able to shape your reads in such a way as to minimize or eliminate shuffling in Spark, which will greatly speed up your write. Keep in mind that the provided partitioners don't have any knowledge of your data and so will be slower than a partitioning approach that can take your data in to account.
> 
> More generally, the writing logic is some of the oldest in the connectors and there is likely substantial room for improvement in performance. Because the write performance has been mostly acceptable to users, I've been focused on getting these connectors merged into Druid rather than further latency or throughput improvements but hopefully Druid committers like @jihoonson will have some useful feedback in their reviews.

Thank you for your answer！

**Comment by Lakomoff** [comment]
> @Lakomoff you are correct, this pull request has not yet been merged into the main Druid branch. You can view the source code [here](https://github.com/JulianJaffePinterest/druid/tree/spark_druid_piecemeal_writer) - the connector code is in the spark module (for future reference, you can click the link at the top of a pr to access the source and target branches) image


Thank you, Julian!
I was managed to compile connector.
But now I am not able to connect to postgresql type metadata store. Is it supported? If yes how it should be configured?

I'v got 
Exception in thread "main" org.apache.druid.java.util.common.IAE: Unrecognized metadata DB type postgresql

**Comment by JulianJaffePinterest** [comment]
@Lakomoff PostgreSQL metadata stores should be supported using the metadata db type `postgres` (it looks like you're using `postgresql`). I'll update the documentation to list the options that ship with support - thank for catching!

**Comment by JulianJaffePinterest** [comment]
@wangxiaobaidu11 sorry Xiao Wang, I think I misinterpreted your question in my earlier comment. You're right to partition your dataframe by timestamp. I thought you were already doing that before the code snippet you shared and then applying the SingleDimensionPartitioner on top of the previous partition. If you were using the SingleDimensionPartitioner to partition your dataframe by timestamp, you will still need to do the partitioning but it will likely be faster to partition directly. You could start with 
```java
Dataset<Row> dataset = sparkSession.sql(querySql);
Dataset<Row> bucketedDataset = dataset.withColumn(<column_name>, SparkUdfs.bucketRow(col(tsCol), lit(tsFormat), lit(segmentGranularity)));
Dataset<Row> partitionedDataSet = bucketedDataset.repartition(col(<column name>)).dropColumn(<column name>);
```
if you want a single partition per segment or using the NumberedPartitioner as described above if you want to set the rows per partition. If that's not fast enough or you want to guarantee each bucket will correspond to exactly one partition, you can use a custom partitioner.

**Comment by wangxiaobaidu11** [comment]
@JulianJaffePinterest   I tested it this way
`Dataset<Row> dataset = sparkSession.createDataFrame(list, schema);`
` Dataset<Row> bucketedDataset =  dataset.withColumn("quick_col",
            SparkUdfs.bucketRow().apply(functions.col("_timeBucketCol"),
                    functions.lit("millis"),
                    functions.lit("DAY")));
    Dataset<Row> partitionedDataSet1 = bucketedDataset.repartition(functions.col("quick_col"))
            .drop(functions.col("quick_col"));
    Dataset<Row> partitionedDataSet2 = partitionedDataSet1.repartition(10);
    partitionedDataSet2.write().format("druid").mode(SaveMode.Overwrite).options(map).save();`

**Comment by JulianJaffePinterest** [comment]
@wangxiaobaidu11 calling `.repartition` _after_ the first repartition blows away the first repartition. If you want to generate more segments for a given bucket, use the NumberedPartitioner.

That pointer aside, the error is saying that multiple versions are being detected for a particular interval. In particular, it suggests that the version assignment logic for the case where no version is specified at write time has migrated to a per-partition or per-executor location instead of only occurring once. I checked the `DataWriterFactory` and that was the case, so I've pulled the version assignment logic back out to a run-once location. I also improved the logging for the error message you were seeing so in the future it will list the conflicting versions instead of just warning about them.

**Comment by wangxiaobaidu11** [comment]
@JulianJaffePinterest  I pulled up your latest code
Execute  “mvn clean install -DskipTests"
image

**Comment by wangxiaobaidu11** [comment]
@JulianJaffePinterest 
I use the way:
`    package$.MODULE$.DruidDataFrame(dataset).partitionAndWrite(`
`            "time_stamp", "millis", "DAY",`
`            1000,`
`   false,  Option.empty()).format("druid").mode(SaveMode.Overwrite).options(map).save();`

**Comment by JulianJaffePinterest** [comment]
@wangxiaobaidu11 are you able to query the segments correctly or are they corrupted as well? (Trying to ascertain if this is a problem with the data in the segments or an issue with the segment analysis that powers the Druid console)

**Comment by paul-rogers** [comment]
@JulianJaffePinterest, this is a great contribution! This code writes to Druid's metadata DB directly. I've found the need to support "external tasks": ingest tasks that run outside of Druid, but interact with Druid's Overlord the same way that an "internal" (Druid `Task`) would. I'll do a PR in a week or two. In creating that enhancement, I was reminded of the work you did here. Might such an approach work in this application as an alternative way to publish the segments which Spark creates?

Druid's own ingestion tasks do most of what you described for this set of PRs:

* Read some input.
* Build some segments and upload them to deep storage.
* Publish the segments (by telling the Overlord about them, which triggers the Coordination actions).
* Release locks obtained during the above process.

The main difference between Spark and Druid's native ingestion is that, with Spark, the ingestion "task" runs outside of Druid.  If the Spark task ran inside of Druid (that is, launched by Overlord), then the Overlord task could use the existing task APIs to do the steps above. But, since Spark (and my project) live outside of Druid, that doesn't work. So, the "external task" API is a variation on the existing, internal API, but with a way for Overlord to monitor the external task, since Overlord can't do so directly.

Basically, you need a way for Overlord to check that your task is still alive, and so it should maintain your locks. This can be done via ZK (for long-running services) or via a heartbeat (for everything else). With that:

* Register an external task. Either tell the Overlord of a ZK host to monitor, or promise to keep up a heartbeat.
* Submit `TaskAction`s (for locking, publishing, etc.)
* Either "commit" the task (saying your task succeeded) or "fail" the task (saying that your task failed). Both release any locks and tell OL to stop worrying about your task.

With this, Spark ingestion is easier: it looks to Overlord just like Druid's own internal ingestion, with the one difference that Overlord did not launch, and cannot monitor, the actual task. (Hence the heartbeat.) This will avoid the need for your code to handle all of Druid's metadata DB storage choices, and the need to track changes to Druid's metadata DB logic.

If the "external task" feature would be of interest for this feature, I can work with you to integrate that API once the external task PR goes through the review process.

**Comment by JulianJaffePinterest** [comment]
@paul-rogers a public external task API could certainly be something worth integrating with! I foresee a couple of solvable problems but I'd be happy to integrate if the new API meets the connector's needs.

- I think there would need to be scalability improvements to the overlord - suddenly dumping thousands of tasks on to the overlord while it's also running real time ingestion has caused me trouble in the past. I'd also be a little worried about the history footprint for these external tasks.
 - I'd also be a little concerned about the change in model for failure recovery - right now, if a Spark job hard crashes and doesn't clean up after itself, at worst it will have left some orphaned files in deep storage that can be easily cleared. If the job has obtained locks with Druid now a lot of business logic needs to go in to figure out how to recover (should Spark as a whole be re-entrant? That solves the daily batch workflow where a retry is usually the first recovery approach but fails for something like an hourly workflow where there may be time overruns. What about multiple jobs etc.?) These are obviously solvable problems but they will introduce a fair amount of orchestration complexity without an obvious place to abstract it away. If we want to heartbeat from Spark we'll need to support a variety of network topologies and permissions structures or else the connectors won't be useful for a lot of people (heartbeating from Spark to an external service is a tricky proposition with a lot of gotchas in my experience, and that's for single-site uses).

Finally, as a broader note the effort to add Spark connectors to Druid is now over two years old. I wouldn't worry too much on your side if the concerns I've highlighted are too onerous to solve on your side or aren't where you imagine the proposed API heading - it's unlikely these connectors will ever be part of the main Druid code base and so I'm not sure how much effort you should expend building against their requirements.

**Comment by samarthjain** [comment]
@abhishekagarwal87

**Comment by JulianJaffePinterest** [comment]
Hey @maytasm, what are you hoping to see out of this PR? There have been 5 new Spark releases and 6 new Druid releases since this PR was opened. If the Druid community wants something similar to the functionality this PR adds (e.g issue #9780), I think it makes more sense to open a new PR based on modern versions of the respective projects. If you or someone else would like, I can publish my Spark 3.x connectors for reference but I'm not planning to open any further PRs at this time.

**Comment by maytasm** [comment]
Hi @JulianJaffePinterest, 
I saw that https://github.com/apache/druid/pull/11474 and https://github.com/apache/druid/pull/11823 was already merged into `apache:spark_druid_connector` and that this PR (write support) is the only piece left. My aim is to review this PR and will get another committer to review this PR. Then we can merge this PR into `apache:spark_druid_connector`. I will then work on getting `apache:spark_druid_connector` up to dated with new Spark releases and new Druid releases. Once that is done, I am aiming to have `apache:spark_druid_connector` merge into Druid master branch and have this functionality (https://github.com/apache/druid/issues/9780) officially supported as part of Druid core extension (it will be part of Druid official docs, maintained, etc). The support for this will have at least two Druid Committers (myself and one other person) and production usage at external companies (such as Netflix). I am aiming to target Spark 3.3 (simply because that is the version of Spark we use at Netflix). Let me know if you think this is a good approach or if there are better approach. Thanks!

**Comment by Gauravshah** [comment]
@maytasm did you get a chance to review the writer PR ?
We are looking to see how we can use spark writer to perform batch processsing

**Comment by maytasm** [comment]
@Gauravshah No, we prioritized some other works over this.

**Comment by Gauravshah** [comment]
thanks @maytasm

**Comment by juhoautio** [comment]
@Gauravshah in case you'd find it helpful, rovio-ingest implements writing Druid segments with Spark (I'm one of the authors).

**Comment by Gauravshah** [comment]
Thanks you @juhoautio will take a look

**Pull request closed without merging**
