### PR TITLE
Support prometheus emitter

### PR DESCRIPTION
**Pull request by jaegwonseo**
### Description

modify helm chart to support scraping from prometheus automatically
Relates to [Issue 13530](https://github.com/apache/druid/issues/13530)

prometheus emitter metric is scraped by prometheus 
스크린샷 2022-12-08 오후 7 08 18

##### Key changed/added classes in this PR
 * `change helm chart` 
   * `add pods annotation`
   * `expose port to scrap from prometheus`

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by jaegwonseo** [comment]
@kfaraz 
Is there something wrong or needs to be corrected?
plz check this

**Comment by kfaraz** [comment]
Hi, @jaegwonseo , thanks for your patience! We have been a little occupied with the upcoming release of Druid 25. I will try to get this reviewed soon.

**Comment by abhishekagarwal87** [comment]
@jaegwonseo - The changes look good to me. can you resolve the conflicts so I can merge this PR?

**Comment by jaegwonseo** [comment]
@abhishekagarwal87 i resolve conflict. plz check this

**Comment by jaegwonseo** [comment]
@abhishekagarwal87 
i just change k8s config 
is it related with this error? [build fail link](https://app.travis-ci.com/github/apache/druid/jobs/595434161)

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
I will merge this soon.

**Comment by abhishekagarwal87** [comment]
thank you @jaegwonseo for your contribution.

**Pull request merged**
