### PR TITLE
add other region support for azure-extension

### LINKED ISSUE #11404: Not Support Other Region's Azure Storage
***Microsoft Azure Extension Does Not Support Other Azure Region's Storage***

### Description

The [Azure Storage Extension](https://druid.apache.org/docs/0.21.1/development/extensions-core/azure.html#deep-storage) do not have a config of ***Azure Storage Host***.

The storage host is [hard coded here](https://github.com/apache/druid/blob/a9c4b478ab7f992d8eeafa3703daff46a72d5812/extensions-core/azure-extensions/src/main/java/org/apache/druid/storage/azure/AzureUtils.java#L44), if we want to user other Azure region's storage, we need to change the host domain, which is not possible now.

### Proposal

Expose this AZURE_STORAGE_HOST_ADDRESS be configurable just like `account`, `container`

I am not good at java coding, can some one make this happen?

### PR DESCRIPTION
**Pull request by wilsoncai666**
Fixes #11404 .

### Description

This pr change AzureUtils.AZURE_STORAGE_HOST_ADDRESS to dynamic,the default value is still "blob.core.windows.net",but it can be changed to another address through druid.azure.hostAddress.

delete the  AzureUtils.AZURE_STORAGE_HOST_ADDRESS , add the hostAddress in "AzureAccountConfig".

#### Changed the method AzureUtils.maybeRemoveAzurePathPrefix()

<hr>

##### Key changed/added classes in this PR
 * `AzureAccountConfig`
 * `AzureDataSegmentPuller`
 * `AzureDataSegmentPusher`
 * `AzureUtils`
 * `AzureDataSegmentPullerTest`
 * `AzureUtilsTest`
AzureDataSegmentPullerTest

AzureUtilsTest

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by suneet-s** [comment]
Hi @wilsoncai666 - Welcome and thanks so much for the contribution! 

Could you update the PR description to include details about what the key changes are and how you tested them. Would you be able to add.an integration test for this so that we do not need to test this manually with every release to make sure this functionality isn't accidentally broken

**Comment by wemod123** [comment]
Will this PR be merged in next release?
Or do you have other plans

**Comment by clintropolis** [comment]
>Will this PR be merged in next release?

Sorry, this one didn't get fully reviewed in time to make 0.22 which is nearly ready to vote on RC1. We typically only backport bug fixes or user facing config/API adjustments after the release branch has been made, not new features.

That said, I'll try to have a look a this change soon so we can try to get it in for 0.23. I think we've gotten to be a bit behind and overwhelmed trying to work through and review the very large number of open PRs, but are very thankful for all the activity and contributions (and everyones patience)!

**Comment by fabricebaranski** [comment]
Hello,
I think it is very interesting to add that, particularly when we want to test with Azurite.
A workaround I tested is to use docker-compose and declare the container with Azurite like that:
```
  azure:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: blob.core.windows.net
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
```

**Pull request closed without merging**
