### PR TITLE
WIP: gcloud pubsub indexing service

### LINKED ISSUE #5773: gcloud pubsub support
Hi. I want to read data from gcloud pubsub and load it into druid.

http://druid.io/docs/0.12.0/ingestion/stream-ingestion.html

Docs suggest that there are 2 ways. What is the recommended way?

### PR DESCRIPTION
**Pull request by aditya-r-m**
Fixes #5773.

### Description

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/incubator-druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/incubator-druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by marklu2018** [comment]
@aditya-r-m , any chance this PR would be merged or released soon? Would really like to try out this extension as our data ingestion pipeline is using google pubsub.

**Comment by aditya-r-m** [comment]
@marklu2018 Hi Mark, we have got the core structure down & need to implement & test how the tasks scale. The development got a bit delayed in the recent weeks but I'll try to pick it up again from this weekend.
It may take a month or two to reach a serious state.

I'd recommend you to setup an intermediate kafka cluster for your immediate needs. KafkaIO.writeWithEOS works nicely on Cloud Dataflow & Druid-Kafka supervisors are already stable.

If this extension works for you, the migration should not be tricky & hopefully will save you half of the machines.

**Comment by kentakozuka** [comment]
@aditya-r-m Is this still an active branch? I am really looking forward to using this feature 😄

**Comment by aditya-r-m** [comment]
@kentakozuka thank you for your interest in the feature. The branch isn't stale, but turning it from an extremely crude prototype to a proper ingestion mechanism has a few blockers.
I've been unable to prioritize this work due to some stretch projects last quarter, but will try to push in the coming weekends.

**Comment by cre8ivejp** [comment]
@aditya-r-m Hi!
I would like to know if there are any plans to merge this by this year?
This PR would cut half of my current costs :(

**Comment by aditya-r-m** [comment]
Hi @cre8ivejp 
thank you for your interest in the feature. I've almost completed an at-least once ingestion mechanism with basic task count/duration management (off & on development for some reasons, sorry).

Can you share the key elements in your ingestion spec that you'd like to use? We can potentially test your use case before even merging this. More concretely, I'd like to know how much duplication can you tolerate and the parameters you need to tweak apart from basic io-config such as subscription, task duration, task counts.

Also, I will add a design doc detailing my findings & approach by this weekend - any form of contributions in terms of design improvements, development & testing are highly appreciated.

**Comment by cre8ivejp** [comment]
@aditya-r-m thank you for your response.
I really appreciate your help on this.
I will prepare all information and send it to you.

I will look at the design doc when you add it and help you as much as I can.

**Comment by smit-aterlo** [comment]
Hello @aditya-r-m, Any update on this branch. We would love to use druid if it comes with PubSub indexing.

**Comment by aditya-r-m** [comment]
@smit-aterlo @cre8ivejp please take a look at the following doc :
https://docs.google.com/document/d/1lDt15Eo4dudH2y2TmPcSd5E7VQP-Boc_UEZnXPRIrQE
It captures the ideas behind the prototype I've built. please request commenter access for review if needed.

I will also get some feedback from core committers, but would very much appreciate any feedback on requirements side. Also, any design/code contributions are very much welcome, regardless of whether the contributions extend this CL or take the basic ideas from my findings & move in a completely separate direction.

**Comment by smit-aterlo** [comment]
Hey @aditya-r-m, any update on this?

**Comment by aditya-r-m** [comment]
Hi @smit-aterlo, the prioritization (& next steps) for pushing this feature further are unclear to me.
It would be great if some core committer in druid can take over this prototype & design doc as I'm unable to fully commit here.
cc @suneet-s @jihoonson @gianm

**Comment by abhishekagarwal87** [comment]
@aditya-r-m - are you not planning to work on this? This seems like a useful feature.

**Comment by aditya-r-m** [comment]
Thank you for your interest @abhishekagarwal87.
I was able to get the implementation it to the point where ingestion with at-least-once semantics was functional.
But I could not build sufficient momentum on getting design/code reviewed & polishing the implementation.

Due to time constraints on my end, I can't contribute more here.
Since this feature is technically feasible & useful, requesting repository owners to take over the change & push through the remaining processes.
@gianm  @vogievetsky PTAL if this can be prioritized.

**Pull request closed without merging**
