### PR TITLE
Web console: fix SegmentTimeline query

### PR DESCRIPTION
**Pull request by vogievetsky**
Fix the issue that the segment timeline was showing unpublished and overshadowed segments.
Adds a filter of `is_published = 1 AND is_overshadowed = 0` to the SQL query.

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by clintropolis — APPROVED** [review]

**Comment by suneet-s** [comment]
@vogievetsky can we add a test to surface these types of issues in the web console?

**Comment by vogievetsky** [comment]
I am not sure how to test this effectively given the current test harness. I guess we would want and e2e test that loads a datasource with overshadowed and un-published segments and makes sure all the numbers are correct?

**Comment by vogievetsky** [comment]
I added a unit test around the query

image

**Comment by suneet-s** [comment]
> I guess we would want and e2e test that loads a datasource with overshadowed and un-published segments and makes sure all the numbers are correct?

This sounds like a good idea to me. Could you create a github issue to keep track of the testing needs so we can add more complete end to end tests like the one you suggested in the future.

Thanks for the fix and the unit test :)

**Pull request merged**
