### PR TITLE
MSQ: Plan without implicit sorting.

### PR DESCRIPTION
**Pull request by gianm**
This patch adds an EngineFeature "GROUPBY_IMPLICITLY_SORTS" and sets it true for native, false for MSQ. It's useful for two reasons:

1) In the future we'll likely want MSQ to hash-partition for GROUP BY
   instead of using a global sort, which would mean MSQ would not
   implicitly ORDER BY when there is a GROUP BY.

2) When doing REPLACE with MSQ, CLUSTERED BY is transformed to ORDER BY.
   We should retain that ORDER BY, as it may be a subset of the GROUP BY,
   and it is important to remember which fields the user wanted to include in
   range shard specs.

Due to (2), this patch fixes an issue where sometimes the `CLUSTERED BY` would be "forgotten". The new test case `testReplaceOnFoo1RangeClusteredBySubset` fails without the rest of the patch being applied, because `NumberedShardSpec` is used instead of `DimensionRangeShardSpec`.

### CODE REVIEW

**Comment by LakshSingla** [comment]
What do you think about some custom code into the MSQ layer that prevents resorting to the fields, in case the previous fields are already sorted by a superset of the given fields? For eg, if a stage wants to sort by columns A, B; while the previous single stage had sorted by columns A, B, C; then we can probably skip sorting for that stage.

This is likely to allow the same benefits associated with assuming a sorted signature, while also preserving the ORDER BY. I had a draft PR with some changes in similar area and this method conveys the above: https://github.com/apache/druid/pull/15945/files#diff-36986d11bec08663b26497269e520d6882a56c189a03de780759f8024ac08127R193

**Comment by gianm** [comment]
> What do you think about some custom code into the MSQ layer that prevents resorting to the fields, in case the previous fields are already sorted by a superset of the given fields? For eg, if a stage wants to sort by columns A, B; while the previous single stage had sorted by columns A, B, C; then we can probably skip sorting for that stage.

I think it makes sense as part of QueryKit. I don't think the `shuffleSpec` in the final `QueryDefinition`, once created by QueryKit, should be second-guessed by the MSQ controller. It looks like that's the path you took in that branch you linked, so that makes sense to me. Although, I don't understand why `aggregate` needs to be added to the hashed shuffle spec.

Do you have an opinion on this patch?

**Comment by LakshSingla** [comment]
> Although, I don't understand why aggregate needs to be added to the hashed shuffle spec.

I was trying out the second recommendation - using hash shuffle for group by, and added the aggregate flag, in case it gets used upstream somewhere.

**Review by LakshSingla — APPROVED** [review]

**Comment by LakshSingla** [comment]
Thanks for the patch, LGTM! This has caused some confusion to me in past as well.

**Comment by LakshSingla** [comment]
The CI failures look legit

**Comment by gianm** [comment]
> The CI failures look legit

Yep, I think I fixed them.

**Pull request merged**
