### PR TITLE
Web console: Double confirm before permanently delete unused segments

### PR DESCRIPTION
**Pull request by zhangyue19921010**
### Description

Delete unused segments is a permanent and dangerous action. This PR adds two warningChecks before users press the confirm button `Permanently delete unused segments`

1. Give tips and warnings.
2. Prevent operation errors.

#### Before
屏幕快照 2020-11-13 下午3 12 46

#### After
屏幕快照 2020-11-13 下午3 12 19
屏幕快照 2020-11-13 下午3 12 26

<hr>

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `web-console/src/views/datasource-view/datasource-view.tsx`

### CODE REVIEW

**Review by capistrant — APPROVED** [review]
Thanks for the contribution! I think this is a good idea. It is a non-intrusive way to ensure that clients understand the gravity of what they are doing. A small price to pay to avoid data loss.

I pulled it down and tested it out myself.

**Review by nishantmonu51 — APPROVED** [review]
👍

**Comment by zhangyue19921010** [comment]
@capistrant @nishantmonu51 Thanks for your review!

**Comment by zhangyue19921010** [comment]
@capistrant  Sorry to bother you , I have deployed this PR in our PRD druid cluster and it works fine. What should I do now?

**Comment by capistrant** [comment]
> @capistrant Hi capistrant! Sorry to bother you , I have deployed this PR in our PRD druid cluster recently and it works fine. What should I do next?

I'll merge it by the end of the week. I usually let approved PRs sit for a few days to give others in the community time to take a look and add any thoughts they may have

**Review by capistrant — APPROVED** [review]

**Comment by zhangyue19921010** [comment]
@capistrant Thanks for your review and merge ! 👍

**Pull request merged**
