### PR TITLE
FEAT : apiversion change to kubeversion

### PR DESCRIPTION
**Pull request by Lee2532**
### Description

Change apiVersion of ingress according to KubeVersion  [issue](https://github.com/apache/druid/issues/13536) 

#### Release note

For tips about how to write a good release note, see [Release notes](https://github.com/apache/druid/blob/master/CONTRIBUTING.md#release-notes).

<hr>

##### Key changed/added classes in this PR
 * change helm ingress

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by dampcake** [comment]
This might be a question for the larger Druid team but have we considered dropping support for Kubernetes versions prior to 1.19? All of the major cloud providers are well past 1.19 as a minimum supporter version and the open source support for 1.19 ended over a year ago.

I ask because that would really simplify this PR.

**Review by dampcake — CHANGES_REQUESTED** [review]
We can't just change the API version for Ingress because they are not compatible. Backend's format has changed and requires a service block. For example it currently looks like:
```
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
```
but would need to be modified to look like:
```    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
```

Supporting this in a compatible way is really annoying though doable but my suggestion would be to drop support for versions prior to 1.19 and update the payload.

Also I can't remember for sure but I think `pathType` might also be required in the new format as well which we should default but allow to be overridden with the new Ingress version.

**Comment by jwitko** [comment]
@dampcake Would you accept a similar PR that dropped support for k8s < 1.19?  I agree with your sentiment but the non-action on this change is really hurting anyone trying to deploy on a modern up to date kubernetes deployment.

**Comment by jwitko** [comment]
Created https://github.com/apache/druid/pull/13806 to do this in a backwards compatible way

**Pull request closed without merging**
