### PR TITLE
Fix a resource leak in JobHelper

### PR DESCRIPTION
**Pull request by asdf2014**
### Description

Fix a resource leak in JobHelper.

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by capistrant — COMMENTED** [review]
Looks like a good fix, but I see that this triggered the code coverage bot in CI

**Review by suneet-s — APPROVED** [review]
LGTM.

I think it's ok to manually override the coverage check for this change since the LGTM bot is saying this one line change fixes the resource leak. What do you think @capistrant ?

I've manually triggered the integration tests, just to make sure there are no unintended consequences (I doubt there will be any legitimate test failures 🤞 )

**Comment by capistrant** [comment]
> LGTM.
> 
> I think it's ok to manually override the coverage check for this change since the LGTM bot is saying this one line change fixes the resource leak. What do you think @capistrant ?
> 
> I've manually triggered the integration tests, just to make sure there are no unintended consequences (I doubt there will be any legitimate test failures 🤞 )

I'd be fine with that

**Comment by suneet-s** [comment]
I've tried re-triggering the integration tests many times today, and I can't figure out why the `other integration tests` are failing. The other test failures are because of a lack of code coverage, which I think is ok to overrule.

@asdf2014 do you think you can merge apache/master back into this branch to see if that fixes the test failures.

**Comment by suneet-s** [comment]
The 4 failing jobs in Travis are failing because of a lack of test coverage.

jdk8 - indexing modules test, jdk8 indexing modules test (SQL compatibility)
jdk11 - indexing modules test, jdk11 indexing modules test (SQL compatibility)

All other tests are passing. 

Overruling Travis as LGTM catches the resource leak

**Pull request merged**
