### PR TITLE
use native nvl expression for SQL NVL and 2 argument COALESCE

### PR DESCRIPTION
**Pull request by clintropolis**
### Description

Do what the title says. The native `nvl` expression, besides being simpler to evaluate than `case_searched(notnull(...)...)`, it is also vectorized, so this should result in a performance improvement for any queries that would be otherwise vectorizable if not for something like a `NVL(x, 'no x')` or `COALESCE(x, 'no x')`. Multi-argument `COALESCE` still plans to a `CASE` statement, which is not vectorized.

The built-in `COALESCE` operator definition does some super early mandatory rewriting into a `CASE` statement a lot earlier than a convertlet could handle it, so I have updated our handling of `CASE` to look for cases it can rewrite into the native `NVL`. Along with this, I added some additional conversion logic to try to plan what more complicated coalesce/nvl expressions can sometimes plan to, which is an expression filter of the form `case when x is not null then expr1 else expr2 end` instead into something like `expr1 or (expr2 and x is null)` if either of expr1 or expr2 can translate into more optimal native filters.

This should result in a performance improvement in some cases, see benchmarks https://github.com/apache/druid/pull/13897#issuecomment-1461122829

The performance of `NVL` vectorized hasn't really been optimized yet, so there might be some cases where vectorizing isn't always better, but it seems close enough for now. When the remaining conditional expressions are vectorized, my intention is to do them using a `VectorMatch` or something similar, in order to only partially evaluate the remaining conditional arguments as needed, instead of always evaluating all arguments like the current iteration of the vectorized `nvl` expression. At this point, I would expect it to almost always come out ahead of the non-vectorized version.

#### Release note
SQL operators `NVL` and `COALESCE` with 2 arguments now plan to a native `nvl` expression, which supports the vector engine. Multi-argument `COALESCE` still plans into a `case_searched`, which is not vectorized.

<hr>

This PR has:

- [x] been self-reviewed.
- [x] a release note entry in the PR description.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by clintropolis** [comment]
marking WIP because this results in a performance regression at times (but not always)

Ran the numbers before this PR and while queries 28 is same-ish, and 29 are significantly slower, 30 and 31 are a fair bit faster before this change.
```
Benchmark              (query)  (rowsPerSegment)  (storageType)  (stringEncoding)  (vectorize)  Mode  Cnt     Score    Error  Units
SqlBenchmark.querySql       28           5000000           mmap              none        false  avgt    5   141.133 ±  3.026  ms/op
SqlBenchmark.querySql       28           5000000           mmap     front-coded-4        false  avgt    5   151.020 ±  6.796  ms/op
SqlBenchmark.querySql       28           5000000           mmap    front-coded-16        false  avgt    5   142.013 ±  1.157  ms/op
SqlBenchmark.querySql       29           5000000           mmap              none        false  avgt    5   877.378 ± 11.754  ms/op
SqlBenchmark.querySql       29           5000000           mmap     front-coded-4        false  avgt    5  1263.192 ± 12.325  ms/op
SqlBenchmark.querySql       29           5000000           mmap    front-coded-16        false  avgt    5  1483.152 ± 10.696  ms/op
SqlBenchmark.querySql       30           5000000           mmap              none        false  avgt    5   100.516 ±  4.728  ms/op
SqlBenchmark.querySql       30           5000000           mmap     front-coded-4        false  avgt    5   100.432 ±  2.805  ms/op
SqlBenchmark.querySql       30           5000000           mmap    front-coded-16        false  avgt    5    91.875 ±  0.999  ms/op
SqlBenchmark.querySql       31           5000000           mmap              none        false  avgt    5    22.473 ±  0.182  ms/op
SqlBenchmark.querySql       31           5000000           mmap     front-coded-4        false  avgt    5    19.557 ±  0.258  ms/op
SqlBenchmark.querySql       31           5000000           mmap    front-coded-16        false  avgt    5    18.795 ±  0.270  ms/op
```

It turns out that for these queries some magic was happening for the case statements which resulted in native filters being used instead of expression filters, for example query 31 looks something like this in the native query

```
{
  "type": "and",
  "fields": [
    {
      "type": "selector",
      "dimension": "dimSequential",
      "value": "1"
    },
    {
      "type": "selector",
      "dimension": "dimSequentialHalfNull",
      "value": null
    }
  ]
},
{
  "type": "and",
  "fields": [
    {
      "type": "selector",
      "dimension": "dimSequential",
      "value": "10"
    },
    {
      "type": "selector",
      "dimension": "dimSequentialHalfNull",
      "value": null
    }
  ]
},
{
  "type": "and",
  "fields": [
    {
      "type": "selector",
      "dimension": "dimSequential",
      "value": "100"
    },
    {
      "type": "selector",
      "dimension": "dimSequentialHalfNull",
      "value": null
    }
  ]
},
{
  "type": "in",
  "dimension": "dimSequentialHalfNull",
  "values": [
    "1",
    "10",
    "100"
  ]
}
```

**Comment by clintropolis** [comment]
redid how i was doing some things and the benchmarks look better all the time now

before:
```
Benchmark              (query)  (rowsPerSegment)  (storageType)  (stringEncoding)  (vectorize)  Mode  Cnt     Score    Error  Units
SqlBenchmark.querySql       28           5000000           mmap              none        false  avgt    5   141.133 ±  3.026  ms/op
SqlBenchmark.querySql       29           5000000           mmap              none        false  avgt    5   877.378 ± 11.754  ms/op
SqlBenchmark.querySql       30           5000000           mmap              none        false  avgt    5   100.516 ±  4.728  ms/op
SqlBenchmark.querySql       31           5000000           mmap              none        false  avgt    5    22.473 ±  0.182  ms/op
```

after:
```
Benchmark              (query)  (rowsPerSegment)  (storageType)  (stringEncoding)  (vectorize)  Mode  Cnt    Score   Error  Units
SqlBenchmark.querySql       28           5000000           mmap              none        false  avgt    5  141.381 ± 1.813  ms/op
SqlBenchmark.querySql       28           5000000           mmap              none        force  avgt    5  103.825 ± 0.657  ms/op
SqlBenchmark.querySql       29           5000000           mmap              none        false  avgt    5  617.000 ± 4.266  ms/op
SqlBenchmark.querySql       29           5000000           mmap              none        force  avgt    5  582.123 ± 4.627  ms/op
SqlBenchmark.querySql       30           5000000           mmap              none        false  avgt    5   95.310 ± 0.528  ms/op
SqlBenchmark.querySql       30           5000000           mmap              none        force  avgt    5   34.568 ± 0.421  ms/op
SqlBenchmark.querySql       31           5000000           mmap              none        false  avgt    5   20.023 ± 0.159  ms/op
SqlBenchmark.querySql       31           5000000           mmap              none        force  avgt    5   18.774 ± 0.678  ms/op
```

**Review by imply-cheddar — APPROVED** [review]
I think this is good assuming tests pass.  Primary validation was that the tests haven't changed other than to expect the `nvl` instead of `case_searched`

**Comment by clintropolis** [comment]
ci failure seems unrelated

**Pull request merged**
