### PR TITLE
Enable already passing tests in DecoupledPlanningCalciteQueryTest

### PR DESCRIPTION
**Pull request by kgyrtkirk**
There are some tests which were disabled - however they seem to be able to pass already.

### CODE REVIEW

**Comment by LakshSingla** [comment]
What change caused the test to pass? If it was passing from the beginning then what was the rationale behind disabling them? (cc @rohangarg)

**Comment by kgyrtkirk** [comment]
@LakshSingla I'm not sure if that's really important
they can be easily overlooked as there is no failure in case they would silently start passing...

the mechanism employed here could be replaced with something which will fail if they start passing for some reason...
so that the same will not happen in the future

do you think it would be usefull to dig out and bisect when they started passing?

**Comment by kgyrtkirk** [comment]
there are a few which was silently fixed by the 1.35 calcite upgrade:
```
testGroupBySortPushDown
testGroupingWithNullInFilter
testNestedGroupBy
testQueryWithSelectProjectAndIdentityProjectDoesNotRename
testSortProjectAfterNestedGroupBy
testSubqueryTypeMismatchWithLiterals
testTimeseriesQueryWithEmptyInlineDatasourceAndGranularity
```

**Comment by kgyrtkirk** [comment]
I think we might want to use a better way to keep this tests disabled until we fix them: #15005

**Review by rohangarg — APPROVED** [review]
Thanks for the changes @kgyrtkirk - we can merge this and you can rebase the new changes in https://github.com/apache/druid/pull/15005

**Comment by kgyrtkirk** [comment]
Thank you @rohangarg for reviewing and merging these changes :)
I'll rebase that right away :D

**Pull request merged**
