### PR TITLE
fix the wget issue when create the docker image for integration test

### LINKED ISSUE #15663: Fail to download the jar when run integration test
### Affected Version

The master branch

### Description
Using following command to trigger integration test
```
mvn verify -P integration-tests
```
there is following error:
```
ERROR: failed to solve: process "/bin/sh -c if [ \"$MYSQL_DRIVER_CLASSNAME\" = \"com.mysql.jdbc.Driver\" ] ;     then wget -q \"https://repo1.maven.org/maven2/mysql/mysql-connector-java/$MYSQL_VERSION/mysql-connector-java-$MYSQL_VERSION.jar\"     -O /usr/local/druid/lib/mysql-connector-java.jar;     elif [ \"$MYSQL_DRIVER_CLASSNAME\" = \"org.mariadb.jdbc.Driver\" ] ;     then wget -q \"https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/$MARIA_VERSION/mariadb-java-client-$MARIA_VERSION.jar\"     -O /usr/local/druid/lib/mysql-connector-java.jar;     fi" did not complete successfully: exit code: 5
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

### PR DESCRIPTION
**Pull request by AlbericByte**
Fixes #15663 .

### Description
fix the wget issue when create the docker image for integration test

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `Dockerfile`

<hr>

This PR has:

- [x] been self-reviewed.
- [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by AlbericByte** [comment]
@FrankChen021 please help to review this.

**Comment by FrankChen021** [comment]
Don't get the point why the command fails to check the server certificate. Could you show us the full error message that you encounter?

**Comment by AlbericByte** [comment]
@FrankChen021 here is 
`ERROR: failed to solve: process "/bin/sh -c if [ \"$MYSQL_DRIVER_CLASSNAME\" = \"com.mysql.jdbc.Driver\" ] ;     then wget -q \"https://repo1.maven.org/maven2/mysql/mysql-connector-java/$MYSQL_VERSION/mysql-connector-java-$MYSQL_VERSION.jar\"     -O /usr/local/druid/lib/mysql-connector-java.jar;     elif [ \"$MYSQL_DRIVER_CLASSNAME\" = \"org.mariadb.jdbc.Driver\" ] ;     then wget -q \"https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/$MARIA_VERSION/mariadb-java-client-$MARIA_VERSION.jar\"     -O /usr/local/druid/lib/mysql-connector-java.jar;     fi" did not complete successfully: exit code: 5
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:1000)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:947)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:471)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:827)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:272)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:195)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)`

**Comment by FrankChen021** [comment]
Just want to confirm the root cause. 

For the integraton-test, the `wget` runs in a docker which is based on the `openjdk:8-slim-buster` image. If the `wget` fails to check the server certificate, there's sth wrong with the base image.

Because the wget command is also used in the distribution Dockerfile, if there's sth wrong configuration with the Dockerfile, we also have to update the distribution docker file.

I can't re-produce this problem by execute the `wget` from a minimal container as following commands:

1. Start a container: 
```
docker % docker run -it openjdk:8-slim-buster /bin/bash
```

2. Run the commands in the container, which are included in the `base-setup.sh`
```
apt-get update
apt-get install -y wget
```

3. Run the wget command:
```
wget https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.7.3/mariadb-java-client-2.7.3.jar
```

What's the running result from your environment? @AlbericByte

**Comment by AlbericByte** [comment]
@FrankChen021 following is error message:
`root@7604fa241304:/# wget https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.7.3/mariadb-java-client-2.7.3.jar
--2024-01-12 18:44:36--  https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.7.3/mariadb-java-client-2.7.3.jar
Resolving repo1.maven.org (repo1.maven.org)... 146.75.28.209, 2a04:4e42:78::209
Connecting to repo1.maven.org (repo1.maven.org)|146.75.28.209|:443... connected.
ERROR: The certificate of ‘repo1.maven.org’ is not trusted.
ERROR: The certificate of ‘repo1.maven.org’ doesn't have a known issuer.`

**Comment by FrankChen021** [comment]
@AlbericByte Could you try again by adding the command `apt-get install ca-certificates `?

```
apt-get update
apt-get install -y wget
apt-get install ca-certificates 
wget https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.7.3/mariadb-java-client-2.7.3.jar
```

**Comment by abhishekagarwal87** [comment]
@georgew5656 - didn't you fix something similar recently?

**Pull request closed without merging**
