### PR TITLE
[for master] general exactly count distinct support in Druid

### PR DESCRIPTION
**Pull request by pzhdfy**
The detailed design and discussion is in issue https://github.com/apache/incubator-druid/issues/6716
**Target**
support general exactly count distinct in Druid

**Attention**
the pr is for branch master,  pr for 0.12.x is here(https://github.com/apache/incubator-druid/pull/7582)

**Usage**
1. configure to use extension druid-uniq: druid.extensions.loadList=[...,"druid-uniq"]
2. define a unique metric in  metricsSpec at Ingestion time
 ` "metricsSpec": [
                {
                    "type": "count",
                    "name": "count"
                },
                {
                    "name": "author_id_distinct",
                    "type": "unique",
                    "fieldName": "author_id"
                }
            ],`
3. define a unique metric in  aggregations at query time
`{
  "queryType": "timeseries",
  "postAggregations": [],
  "granularity": "ALL",
  "dataSource": "druid_hadoop_task_example",
  "intervals": "2018-04-24T00:00:00+08:00/2018-04-26T00:00:00+08:00",
  "aggregations": [
    {
      "name": "count",
      "type": "count"
    },
    {
      "name": "author_id_distinct",
      "type": "unique",
      "fieldName": "author_id_distinct"
    }
  ]
}`

**Tips**
1.if the cardinality of the unique column is too large, you can increase the map / reduce memory in jobProperties

### CODE REVIEW

**Comment by JackyYangPassion** [comment]
when i use quickstart example wikiticker-2015-09-12-sampled.json with unique user:
record:
`{"time":"2015-09-12T00:47:44.963Z","channel":"#ru.wikipedia","cityName":null,"comment":"/* Донецкая Народная Республика */","countryIsoCode":null,"countryName":null,"isAnonymous":false,"isMinor":false,"isNew":false,"isRobot":false,"isUnpatrolled":false,"metroCode":null,"namespace":"Main","page":"Караман, Александр Акимович","regionIsoCode":null,"regionName":null,"user":"Камарад Че","delta":0,"added":0,"deleted":0}`

Error:
`java.lang.Exception: io.druid.java.util.common.RE: Failure on row[{"time":"2015-09-12T00:47:44.963Z","channel":"#ru.wikipedia","cityName":null,"comment":"/* Ð”Ð¾Ð½ÐµÑ†ÐºÐ°Ñ ÐÐ°Ñ€Ð¾Ð´Ð½Ð°Ñ Ð ÐµÑÐ¿ÑƒÐ±Ð»Ð¸ÐºÐ° */","countryIsoCode":null,"countryName":null,"isAnonymous":false,"isMinor":false,"isNew":false,"isRobot":false,"isUnpatrolled":false,"metroCode":null,"namespace":"Main","page":"ÐšÐ°Ñ€Ð°Ð¼Ð°Ð½, ÐÐ»ÐµÐºÑÐ°Ð½Ð´Ñ€ ÐÐºÐ¸Ð¼Ð¾Ð²Ð¸Ñ‡","regionIsoCode":null,"regionName":null,"user":"ÐšÐ°Ð¼Ð°Ñ€Ð°Ð´ Ð§Ðµ","delta":0,"added":0,"deleted":0}]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522) [hadoop-mapreduce-client-common-2.7.3.jar:?]
Caused by: io.druid.java.util.common.RE: Failure on row[{"time":"2015-09-12T00:47:44.963Z","channel":"#ru.wikipedia","cityName":null,"comment":"/* Ð”Ð¾Ð½ÐµÑ†ÐºÐ°Ñ ÐÐ°Ñ€Ð¾Ð´Ð½Ð°Ñ Ð ÐµÑÐ¿ÑƒÐ±Ð»Ð¸ÐºÐ° */","countryIsoCode":null,"countryName":null,"isAnonymous":false,"isMinor":false,"isNew":false,"isRobot":false,"isUnpatrolled":false,"metroCode":null,"namespace":"Main","page":"ÐšÐ°Ñ€Ð°Ð¼Ð°Ð½, ÐÐ»ÐµÐºÑÐ°Ð½Ð´Ñ€ ÐÐºÐ¸Ð¼Ð¾Ð²Ð¸Ñ‡","regionIsoCode":null,"regionName":null,"user":"ÐšÐ°Ð¼Ð°Ñ€Ð°Ð´ Ð§Ðµ","delta":0,"added":0,"deleted":0}]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:93) ~[druid-indexing-hadoop-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: Value : ÐšÐ°Ð¼Ð°Ñ€Ð°Ð´ Ð§Ðµ not exists
	at org.apache.kylin.common.util.Dictionary.getIdFromValue(Dictionary.java:107) ~[kylin-core-common-2.5.2.jar:2.5.2]
	at org.apache.kylin.common.util.Dictionary.getIdFromValue(Dictionary.java:85) ~[kylin-core-common-2.5.2.jar:2.5.2]
	at io.druid.segment.incremental.IncrementalIndex$1InputRowDictWrap.getDimension(IncrementalIndex.java:180) ~[druid-processing-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.query.aggregation.unique.RoaringBitmapComplexMetricSerde$1.extractValue(RoaringBitmapComplexMetricSerde.java:70) ~[druid-uniq-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.query.aggregation.unique.RoaringBitmapComplexMetricSerde$1.extractValue(RoaringBitmapComplexMetricSerde.java:52) ~[druid-uniq-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex$1IncrementalIndexInputRowColumnSelectorFactory$1.getObject(IncrementalIndex.java:264) ~[druid-processing-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.query.aggregation.unique.UniqueBuildAggregator.aggregate(UniqueBuildAggregator.java:53) ~[druid-uniq-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.indexer.InputRowSerde.toBytes(InputRowSerde.java:281) ~[druid-indexing-hadoop-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorMapper.innerMap(IndexGeneratorJob.java:371) ~[druid-indexing-hadoop-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:88) ~[druid-indexing-hadoop-0.12.4-SNAPSHOT.jar:0.12.4-SNAPSHOT]
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]
2019-07-16T12:19:08,346 INFO [task-runner-0-priority-0] org.apac`

**Comment by JackyYangPassion** [comment]
from the error message ,i think there is must be an error in built  dictionary stage ! so when in the ingestion stage there is a key can't find in the dictionary

**Comment by pzhdfy** [comment]
> From the error message ,i think there is must be an error in built dictionary stage ! so when in the ingestion stage there is a key can't find in the dictionary!
> 
> do you have the same error when use wikiticker-2015-09-12-sampled.json data? @pzhdfy

Yes, this is a know issue, non-ascii char may not be encoded correctly in BuildDictJob.
We fix it in our internal version, I will commit it later

**Comment by JackyYangPassion** [comment]
> > From the error message ,i think there is must be an error in built dictionary stage ! so when in the ingestion stage there is a key can't find in the dictionary!
> > do you have the same error when use wikiticker-2015-09-12-sampled.json data? @pzhdfy
> 
> Yes, this is a know issue, non-ascii char may not be encoded correctly in BuildDictJob.
> We fix it in our internal version, I will commit it later

Thank you for your attention

**Comment by JackyYangPassion** [comment]
SQL have plan will support uniq query?
Like theta use APPROX_COUNT_DISTINCT_DS_THETA with sql

**Comment by JackyYangPassion** [comment]
i make a test for this PR:

**source** data 300 million ;
**dictionary** build time 45 min ; dictionary size 7GB; 
dictionary info:Total 191707672 values and 48 slices,min:0,max:191707672

**there is one problem:
when build segment long time can't build finish;**
there is the Map log:
`2019-09-05T09:32:00,414 INFO [main] org.apache.parquet.hadoop.InternalParquetRecordReader - at row 0. reading next block
2019-09-05T09:32:00,975 INFO [main] org.apache.parquet.hadoop.InternalParquetRecordReader - block read in memory in 561 ms. row count = 732366
2019-09-05T09:39:10,079 INFO [main] org.apache.kylin.dict.AppendTrieDictionary - Evict slice with key APArDCycNA1LBbSBJN114twCcdStEcZQtVU= and value null caused by COLLECTED, size 30/48
2019-09-05T09:39:10,079 INFO [main] org.apache.kylin.dict.AppendTrieDictionary - Evict slice with key ALDreChzKg1LBUt0Rr_TW-HAbTiuSotei-I= and value null caused by COLLECTED, size 30/48
2019-09-05T09:39:10,080 INFO [main] org.apache.kylin.dict.AppendTrieDictionary - Evict slice with key ACDvscHggA1LBdZmGFsn8cWVhiIyEjszhu0= and value null caused by COLLECTED, size 30/48
2019-09-05T09:39:10,080 INFO [main] org.apache.kylin.dict.AppendTrieDictionary - Evict slice with key  and value null caused by COLLECTED, size 30/48
2019-09-05T09:39:10,080 INFO [main] org.apache.kylin.dict.AppendTrieDictionary - Evict slice with key AMBh5j9swQ9LBfOZxCJ6vLZh1ms8RIDZmW4= and value null caused by COLLECTED, size 30/48`

the build segment MR memory config:
`<property>
          <name>mapreduce.map.memory.mb</name>
          <value>10096</value>
  </property>
  <property>
             <name>mapreduce.reduce.memory.mb</name>
             <value>9096</value> 
</property>`

**Comment by JackyYangPassion** [comment]
Have solve this : 
the reason is Map memory is too small
<property> <name>mapreduce.map.memory.mb</name> <value>20096</value> </property> <property> <name>mapreduce.reduce.memory.mb</name> <value>9096</value> </property>

**Comment by pzhdfy** [comment]
implement relocate in UniqueBufferAggregato
,that fix unique in group by query may be broken

**Pull request closed without merging**
