### PR TITLE
fix website mvn build

### PR DESCRIPTION
**Pull request by clintropolis**
### Description
Update nodejs and npm version for `website` to match `web-console`. Prior to this change, website build via maven would fail with an error like 
```
$ mvn package -pl website -Pwebsite-docs
...

[INFO] --- exec-maven-plugin:1.6.0:exec (build-docs) @ druid-website ---
Building to docs for '27.0.0-SNAPSHOT' to ../../druid-website-src ...

> @ compile-scss /Users/clint/workspace/clintropolis/druid/website
> sass scss/custom.scss > static/css/custom.css

/Users/clint/workspace/clintropolis/druid/website/node_modules/sass/sass.dart.js:6
var self = dartNodeIsActuallyNode ? Object.create(globalThis) : globalThis;
                                                  ^

ReferenceError: globalThis is not defined
    at Object.exports.load (/Users/clint/workspace/clintropolis/druid/website/node_modules/sass/sass.dart.js:6:51)
```

After swapping to a newer nodejs version, it appears to build successfully.

I went ahead and removed the `i18n/en.json` changes since the file is autogenerated, and added it to `.gitignore`, but i can revert this if it bothers anyone...

### CODE REVIEW

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by vogievetsky** [comment]
are the changes to `website/i18n/en.json` intentional? Usually that file is changed and then we just remove it from the commit because it is an auto generated file. I suggest removing it from this PR

**Comment by clintropolis** [comment]
> are the changes to website/i18n/en.json intentional? Usually that file is changed and then we just remove it from the commit because it is an auto generated file. I suggest removing it from this PR

Since this file is autogenerated, I have removed it ... to the max! It is deleted and added to .gitignore so that hopefully it won't cause us any confusion in the future. Everything seems to still build ok afaict.

**Review by 317brian — APPROVED** [review]
Deleting `i18n` (internationalization) and adding it to the git ignore LGTM. It's used for translation, which isn't within the scope of the OSS Druid docs.

**Comment by clintropolis** [comment]
failures are unrelated to this PR

**Pull request merged**
