### PR TITLE
28.0.0 backports

### PR DESCRIPTION
**Pull request by cryptoe**
Backports for :
#15095 Rewrite EARLIEST/LATEST query operators to EARLIEST_BY/LATEST_BY 
#14994 Limit pages size to a configurable limit

### CODE REVIEW

**Comment by LakshSingla** [comment]
@cryptoe Can you please breakout out the commits in separate PRs if possible? This helps with the release management.

**Comment by abhishekagarwal87** [comment]
We could also try `rebase and merge` option. If that retains individual commits, then the commit history would be clean.

**Comment by LakshSingla** [comment]
Hmm, I think that should work. TY for the suggestion.

**Comment by LakshSingla** [comment]
Thanks for the backports @cryptoe

**Pull request merged**
