### PR TITLE
Functions that extract a value from a JSON-encoded string.

### PR DESCRIPTION
**Pull request by achimbab**
This PR implements functions that extract a value from a JSON-encoded string.

### New functions

| function | description |
| --- | --- |
| json_extract_string(expr,string...) | Extracts the String value from expr based on string arguments. |
| json_extract_long(expr,string...) | Extracts the Long value from expr based on string arguments. |
| json_extract_double(expr,string...) | Extracts the Double value from expr based on string arguments. |
| jsonpath_extract_string(expr,json-path) | Extracts the String value from expr based on json-path. |
| jsonpath_extract_long(expr,json-path) | Extracts the Long value from expr based on json-path. |
| jsonpath_extract_double(expr,json-path) | Extracts the Double value from expr based on json-path. |

### Examples

The `json_extract_*` family of functions extract a value from a JSON-encoded string.

```SQL
SELECT json_extract_string('{"key1":"val1"}', 'key1')
-- Extract a value from a nested object
SELECT json_extract_string('{"key1":{"key2":"val2"}}', 'key1', 'key2')
```

The `jsonpath_extract_*` family of functions support JSONPath expressions referring to a JSON structure in the same way as XPath expression.

```SQL
SELECT jsonpath_extract_string('{"key":[{"k":"v1"},{"k":"v2"}]}', '$.key[0].k')
```

### FastJsonReader
The `json_extract_*` family of functions use FastJsonReader.

In order to improve extraction performance, I implemented light and fast parser called FastJsonReader.

In my environment, it is faster than Jsonpath in the case of extracting a scalar value. However, Jsonpath offers lots of functionalities.

### Benchmark
I did benchmark test with the query below.

```SQL
select v, count(*) 
from (
    select json_extract_string(json_column, 'key') as v 
    from test
) 
group by v
order by count(*) desc
```

####  Benchmark 1 - Single Node, Small dataset
1 node / 6 core, 32G RAM, SSD

Sample rows: 445,283

image

#### Benchmark 2 - Cluster, Medium dataset
15 Historical nodes / 32 core, 256G RAM, NVME

Sample rows: 3247568

image

#### Benchmark 3 - Cluster, Large dataset
15 Historical nodes / 32 core, 256G RAM, NVME

Sample rows: 9614347

image

### CODE REVIEW

**Comment by achimbab** [comment]
@asdf2014 @suneet-s 
Can you please do a code review?

**Comment by suneet-s** [comment]
Thanks for the contribution @achimbab! The benchmark results look promising.

I have to spend some time to understand the changes better and hope to get a review out next week. 

In the mean time, could you resolve the merge conflicts that exist now please. Also I skimmed the changes and noticed new SQL functions - to test that they are wired up correctly, could you add a test to one of the `CalciteQueryTest` classes - these are what I use to write "integration tests" for SQL functions so we can ensure these functions continue to work with each new release of Druid.

**Comment by achimbab** [comment]
I force-pushed just to modify commit messages.

**Comment by achimbab** [comment]
@suneet-s
- I resolved the merge conflicts. 
- I added tests to CalciteQueryTest class.

Thank you.

**Comment by achimbab** [comment]
@suneet-s 
I fixed `json_extract_*` functions to unescape strings.

**Comment by suneet-s** [comment]
Thanks @achimbab I am reviewing this today!

**Comment by achimbab** [comment]
@suneet-s 
Hi, hope you are doing well. please let me know if there is something that I have to do in order to merge PR.
Wish you a happy christmas.

**Pull request closed without merging**
