### PR TITLE
Fixup typos in `integration-tests/README.md`

### PR DESCRIPTION
**Pull request by abhishekrb19**
### Description

This PR fixes some miscellaneous things in the `integration-tests` README file.

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Review by amaechler — APPROVED** [review]
🐻

**Review by paul-rogers — APPROVED** [review]
Thanks for fixing these typos.

**Comment by abhishekrb19** [comment]
Thanks for the reviews! Static check is failing unrelated to this change (I see similar failures on other open PRs):
```
Error:  processing/src/main/java/org/apache/druid/data/input/FirehoseFactory.java:90 -- Method is never used as a member of this interface, but only as a member of the implementation class(es). The project will stay compilable if the method is removed from the interface.
Error:  processing/src/main/java/org/apache/druid/data/input/InputFormat.java:62 -- Method is never used.
Error:  processing/src/main/java/org/apache/druid/data/input/FirehoseFactoryToInputSourceAdaptor.java:48 -- Method is never used.
Error:  processing/src/main/java/org/apache/druid/java/util/http/client/HttpClientProxyConfig.java:43 -- Constructor is never used.
Error:  processing/src/main/java/org/apache/druid/java/util/http/client/response/FullResponseHolder.java:52 -- Method is never used as a member of this abstract&nbsp;class, but only as a member of the implementation class(es). The project will stay compilable if the method is removed from the abstract&nbsp;class.
```

**Comment by paul-rogers** [comment]
Merging because I can't see how changing a `README.md` file could cause a UT to fail, so assuming the UT failure is flaky.

**Pull request merged**
