### PR TITLE
bug fix: merge results of group by limit push down

### PR DESCRIPTION
**Pull request by mchades**
#### Fixed the bug:
when merge limit push down results with long dimension not in limitSpec, merge result is incorrect.

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by mchades** [comment]
this PR may also resolve issue #11758

**Comment by mchades** [comment]
could u do a code review for this pr? @gianm

**Comment by mchades** [comment]
@clintropolis Could u plz do a code review for this pr?

**Comment by clintropolis** [comment]
>@clintropolis Could u plz do a code review for this pr?

sorry yes, will try to have a look soon

**Comment by mchades** [comment]
邮件收到，谢谢！

**Comment by abhishekagarwal87** [comment]
@mchades - can you merge the latest master branch in your PR source branch? This is because there is any recent change incompatible with your PR, we will be able to catch it. There have been a lot many changes to druid after the last Travis run for your PR.

**Comment by mchades** [comment]
@abhishekagarwal87 -yeah,It's done now, all checks have passed as well.

**Review by gianm — APPROVED** [review]

**Comment by gianm** [comment]
Thanks for the fix @mchades! It also looks to me like it should address #11758.

**Pull request merged**
