### PR TITLE
Re-order and document format detection in web console

### PR DESCRIPTION
**Pull request by josephglanville**
Motivation for this change is to not inadvertently identify binary
formats that contain uncompressed string data as TSV or CSV.

Moving detection of magic byte headers before heuristics should be more
robust in general.

This PR has:
- [x] been self-reviewed.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by vogievetsky** [comment]
Love it. Makes total sense. Out of curiosity was this change motivated by something you saw IRL that tripped up the current system?

**Comment by vogievetsky** [comment]
Oh I guess you saw a binary file that happened to have more than 3 tabs or commas...

**Comment by josephglanville** [comment]
@vogievetsky sorry for slow reply. Yes I opened an Avro binary file with the compression codec set to `none` that contained JSON data, it was detected as CSV because of the commas.

**Comment by maytasm** [comment]
@vogievetsky @josephglanville 
I also observed similar issues in the following cases when ingesting from local files:
- Ingesting from directory containing Orc files with file filter set to * auto-detect to csv
- Ingesting from directory containing Parquet files with file filter set to * auto-detect to csv
- Ingesting from directory containing Parquet files with file filter set to *.parquet auto-detect to csv
However, ingesting from directory containing Orc files with file filter set to *.orc correctly auto-detect to orc

I think your PR may fix all of the above issues. I will try checkout the PR and confirm.

**Comment by josephglanville** [comment]
Yes this will definitely fix those issues.

**Pull request merged**
