### PR TITLE
Harmonize behavior when virtual columns reference each other.

### PR DESCRIPTION
**Pull request by gianm**
This matches the behavior of QueryableIndex and IncrementalIndex based cursors.

### CODE REVIEW

**Comment by clintropolis** [comment]
This seems like it should work for `ExpressionVirtualColumns` without issue, but we might need to add some additional guards to some other virtual columns which expect to be built on top of a physical column to do things with dictionaries and indexes, such as `ListFilteredVirtualColumn`, looking into some code to see if this should be done now or can be done later.

I'm also wondering if there is work SQL side to be done here to allow this, e.g. with `VirtualColumnRegistry` and how some of the expressions are being constructed, to allow SQL to plan into things like this. I think we would want some smarts to it so that it only breaks up an expression virtual column into multiple parts if there is some sub-part shared by all callers, but could also potentially be nice in the cases that have "native" optimized virtual column implementations, such as allowing expressions to call `ListFilteredVirtualColumn`.

**Comment by gianm** [comment]
@clintropolis with regard to whether virtual column implementations would handle this properly, I want to stress that virtual columns referencing other virtual columns is _already possible_ for cursors backed by regular segments. They do their own virtual column handling and it already works this way. The VirtualizedColumnSelectorFactory is updated in this patch to match that behavior.

**Comment by clintropolis** [comment]
>@clintropolis with regard to whether virtual column implementations would handle this properly, I want to stress that virtual columns referencing other virtual columns is already possible for cursors backed by regular segments or by IncrementalIndexes. They do their own virtual column handling and they both already work this way. The VirtualizedColumnSelectorFactory is updated in this patch to match that behavior. It's used by RowBasedSegments and by PostJoinCursor.

Hmm, in that case there might be a couple of other things worth fixing so stuff works good.

these should probably use `this` instead of the inspector of the underlying index:
https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/QueryableIndexColumnSelectorFactory.java#L196
https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/vector/QueryableIndexVectorColumnSelectorFactory.java#L270
https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/virtual/VirtualizedColumnInspector.java#L55

I've had it in my head that this is broken for some reason, but admit the last time i really dug into it was a couple of years ago, so trying to remember things.

**Comment by gianm** [comment]
Ah, that's a good list. Yeah those should all use `this`, I think, to be consistent with the existing behavior of the selector-making methods. I'll change them and think a little about how we could improve the test coverage.

**Comment by gianm** [comment]
@clintropolis I think this should be enough to do it: https://github.com/apache/druid/pull/11955/commits/1b1eb1e6c195170d1c970c2a14e23472dcc05c22. With that change, the other call sites you mentioned look ok to me.

**Review by clintropolis — APPROVED** [review]

**Pull request merged**
