### PR TITLE
Hadoop based batch ingestion support range partition

### PR DESCRIPTION
**Pull request by hqx871**
### Description

This pr implements range partitioning for hadoop-based ingestion.  For detail about multi dimension range partition can be seen https://github.com/apache/druid/pull/11848.
This pr also add a sample parameter to fast DeterminePartitionsJob.

<hr>

##### Key changed/added classes in this PR
 * `DeterminePartitionsJob`
 * `HadoopTuningConfig`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
Hey @hqx871 forced-push on a PR is not recommended. See the contributing.md

> Avoid rebasing and force pushes after submitting a pull request, since these make it difficult for reviewers to see what you've changed in response to their reviews. The Druid committer that merges your change will rebase and squash it into a single commit before committing it to master.

**Comment by hqx871** [comment]
> Hey @hqx871 forced-push on a PR is not recommended. See the contributing.md
> 
> > Avoid rebasing and force pushes after submitting a pull request, since these make it difficult for reviewers to see what you've changed in response to their reviews. The Druid committer that merges your change will rebase and squash it into a single commit before committing it to master.

Get. I will read the contributing.md

**Comment by rshanmugam1** [comment]
This future will help us also. Any plans to merge?

**Comment by aharbunou-branch** [comment]
> This feature will help us also. Any plans to merge?

+1

@hqx871 @FrankChen021 do you happen to know whether it will be included into an upcoming release?

**Pull request closed without merging**
