### PR TITLE
Drop the deprecated NoneShardSpec

### PR DESCRIPTION
**Pull request by jihoonson**
A part of https://github.com/apache/druid/issues/9241. `NoneShardSpec` has been deprecated for a while.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by drcrallen** [comment]
This breaks compatibility with segments that were built with none shard spec. My understanding is that very old segments are still to be supported to load on historicals for query.

**Comment by jihoonson** [comment]
Yes, this is an incompatible change. The `NoneShardSpec` was deprecated in March last year (https://github.com/apache/druid/pull/6883). I don't think we should support everything forever. For example, we don't support the old segment format (lower than the version 9) anymore.
However, I'm open to keep it for a couple of more releases. Do you think the next release is not a good time to remove it?

**Comment by gianm** [comment]
I don't think we should ever remove support for loading any previously-existing segments, no matter how old they are. To my knowledge, we haven't done this since Druid was open-sourced (if I recall correctly, the pre-v8 segment versions were also pre-OSS). This is because it is a pretty big burden on users to ask them to reindex all their data.

Does the fact that NoneShardSpec exists block #9241 from working?

If so, an alternative would be to remove NoneShardSpec, but include code to automatically convert metadata into something equivalent, so users don't need to reindex.

**Comment by jihoonson** [comment]
Ok. This is not a blocker. I'm closing this PR.

**Pull request closed without merging**
