### PR TITLE
Historical clean damaged segment enhancement

### PR DESCRIPTION
**Pull request by mchades**
### Description

Historical only `checkSegmentFilesIntact` in `findStoragePathIfCached`

https://github.com/apache/druid/blob/6a4cbab4b8a55efa482aacc0399353ac5589e5e1/server/src/main/java/org/apache/druid/segment/loading/SegmentLocalCacheManager.java#L157-L189

when found segment files damaged, the method remove the segment files and break StorageLocation loop, then return null. If the segment load faild in other locations for some reason befor, and the other damaged segment will never be removed.

#### Release note

<hr>

##### Key changed/added classes in this PR
 *  In order to searching segment in all storage path, remove break statment

<hr>

This PR has:

- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
did you run into this problem in your cluster? can you tell us more about how you ran into this issue?

**Comment by mchades** [comment]
> did you run into this problem in your cluster? can you tell us more about how you ran into this issue?

@abhishekagarwal87  I have encountered the following situation:

The storage of the Historical configured locations has been filled up, but the storage utilization displayed on the Coordinator is only around twenty percent. This has caused the Coordinator to continuously allocate segments to this Historical, but the segments fail to load due to insufficient storage, resulting in a repetitive cycle.

I suspect that there are failed segments that were not completely cleaned up, leading to inaccurate storage statistics for the Historical. The premature exit from the loop in `findStoragePathIfCached` may be causing this outcome.

**Comment by abhishekagarwal87** [comment]
Oh. What version are you on? There was a bug in earlier versions because of which when historical restarts, they don't take into account their current usage. So every time a historical restarts, the usage will become zero even though they have lot of segments. It's fixed in this PR - https://github.com/apache/druid/pull/10884

**Comment by abhishekagarwal87** [comment]
I don't think there is a real risk and even if it breaks, the damaged file will be deleted in the next run.

**Pull request closed without merging**
