### PR TITLE
Fix bug in TaskStorageQueryAdapter

### PR DESCRIPTION
**Pull request by kfaraz**
#### 1. Bug in TaskStorageQueryAdapter
#15377 introduced a change to fetch task payloads from memory.

But it keeps a reference to the `TaskQueue` when `TaskStorageQueryAdapter` is being constructed.

The `TaskQueue` object is recreated upon every leader election.
So, effectively, if a node becomes a leader again, it would use the older instance of the `TaskQueue`
from when it had first become the leader.

But that old instance of `TaskQueue` would not have information of new tasks and would eventually fall back
to fetching stuff from metadata storage, rendering the caching layer useless.

Also, memory leaks.

#### 2. Broken master

#16309  removed the method `TaskAction.isAudited()`. Some task actions still have this method causing compilation failure.

### Changes

- Do not hold a reference to `TaskQueue` in `TaskStorageQueryAdapter`
- Use `TaskStorage` instead of `TaskStorageQueryAdapter` in `IndexerMetadataStorageAdapter`
- Rename `TaskStorageQueryAdapter` to `TaskQueryTool`
- Fix newly added task actions `RetrieveUpgradedFromSegmentIds` and `RetrieveUpgradedToSegmentIds`
by removing `isAudited` method.

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by kfaraz** [comment]
Marked as dev blocker since master branch is broken after merging #16309

**Review by AmatyaAvadhanula — APPROVED** [review]
LGTM! Thanks, @kfaraz

**Comment by AmatyaAvadhanula** [comment]
> Marked as dev blocker since master branch is broken after merging https://github.com/apache/druid/pull/16309
This seems misleading as the bug in TaskStorageQueryAdapter doesn't break master. Could you please edit the PR description accordingly?

**Comment by kfaraz** [comment]
Thanks for the quick review, @AmatyaAvadhanula !

**Pull request merged**
