### PR TITLE
add optional lookup schema authorization

### LINKED ISSUE #12728: ACL for  lookups
Hi, (please consider this as a Feature Request)
We applied Authorization model on datasources, as described here : [User authentication and authorization · Apache Druid](https://druid.apache.org/docs/latest/operations/security-user-auth.html)

Once done, a user connecting with the proper credentials can only acces the datasources he’s been granted.
Can we achieve the same on lookups ?

We discovered this while connecting Superset to our druid instance : all lookups seem accessible, ,while only the authorized datasources are accessible from Superset logged with the restricted login.

### PR DESCRIPTION
**Pull request by AlbericByte**
Fixes #12728

### Description
add optional authorization to LOOKUP in SQL as LOOKUP resources, if
the newly added druid.sql.planner.authorizeLookupDirectly is true. For backwards compatibility, this feature is off by default. This allows cluster operators to selectively enable access to LOOKUP, or even disallow completely while still allowing SQL access to LOOKUP resources.
Ex: if druid.sql.planner.authorizeLookupDirectly is false, disallow completedly authorization to LOOKUP resource. User can access any LOOKUP resource without permission.
if druid.sql.planner.authorizeLookupDirectly is true, druid will verify the permission of any LOOKUP resource.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `ResourceType`
 * `PlannerConfig`
 * `SqlResourceCollectorShuttle`
 * `NamedLookupSchema`

<hr>

This PR has:

- [x] been self-reviewed.
- [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
Interesting. I didn't understand the bit "disallow completely while still allowing access to lookup resource". can you elaborate through an example?

**Comment by AlbericByte** [comment]
@abhishekagarwal87 updated the description with example, and i will create some unit test cases for these.

**Comment by FrankChen021** [comment]
> or even disallow completely while still allowing SQL access to LOOKUP resources.

From the code, I think this description is ambiguous. 
What he want to say I think is, if the the flag is enabled, it's not allowed to access the LOOKUP.

**Comment by abhishekagarwal87** [comment]
While this PR takes care of lookup access in SQL, a user can submit JSON queries directly, too, and those JSON queries can refer to lookup. So you will also need to make necessary changes in QueryLifecycle#authorize for this feature to be complete.

**Comment by AlbericByte** [comment]
Add integration test case for current implement
Still working on QueryLifecycle#authorize

**Review by FrankChen021 — COMMENTED** [review]
BTW, I don't see any changes on documents. Should this newly added configuration stated in the user document?

**Comment by abhishekagarwal87** [comment]
I marked this a design review since the approach here needs a thorough review. I can't say confidently that the current approach is robust in extracting all the lookup information. So I will want more committers to look at this change.

**Pull request closed without merging**
