### PR TITLE
Add support for optional region, endpoint url, and endpoint signing region for s3 for ingestion

### PR DESCRIPTION
**Pull request by maytasm**
Add support for optional region, endpoint url, and endpoint signing region for s3 for ingestion 

### Description

Cloud InputSource (such as S3, etc.) should be able to support taking in configs optionally in order to be able to read from multiple buckets/location. This is in order to use different region and/or endpoint url than the default (i.e. the one provided in the common runtime property) and also to be able to use different region and/or endpoint url for each ingestion.

Motivation:
This address the proposal https://github.com/apache/druid/issues/9305 and due to popular demand from the community

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by a2l007** [comment]
Looks to be similar to #11798 
@maytasm Do you want me to rebase the latest onto that PR or should we proceed with this one?

**Comment by maytasm** [comment]
@a2l007 
I am planning to close this PR. 
I found out that the region parameter is not really needed. If the user wants to ingestion data from s3 with different region than the region configured on the cluster (in runtime property), the user can set druid.s3.forceGlobalBucketAccessEnabled=true 
Unless you think there is any benefit of setting optional region parameter in each ingestionSpec rather than druid.s3.forceGlobalBucketAccessEnabled=true, I will go ahead and close this PR.
The other component of this PR is endpoint url, and endpoint signing region which can be done in https://github.com/apache/druid/pull/11798
I think you can rebase https://github.com/apache/druid/pull/11798 and combine tests / docs as needed from this PR. I can review https://github.com/apache/druid/pull/11798 once it is ready.

**Comment by a2l007** [comment]
@maytasm I don't think we need the region parameter in the ingestion spec for multi region access. We've been able to read from buckets in other regions with custom endpointconfigs and clientconfigs.
I'll clean up #11798 and give you a heads up. Thanks!

**Comment by maytasm** [comment]
@a2l007 
Sounds good! Thanks

**Pull request closed without merging**
