### PR TITLE
Add CalciteSysQueryTest to enable some testing of bindable plans.

### PR DESCRIPTION
**Pull request by kgyrtkirk**
Fixes #XXXX.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [x] been self-reviewed.

### CODE REVIEW

**Review by somu-imply — APPROVED** [review]
Thanks for logging the logical plan. This will be helpful! LGTM

**Comment by xvrl** [comment]
@soumyava @kgyrtkirk @somu-imply it looks like this commit broke the build `notMsqCompatible` is not defined anywhere. Can we please revert this until this is fixed?

**Comment by xvrl** [comment]
looks like the function was renamed in https://github.com/apache/druid/pull/14900

**Comment by somu-imply** [comment]
Yes this is being fixed in https://github.com/apache/druid/pull/15099. Will merge as soon as CI passes

**Comment by soumyava** [comment]
The master should be back up as the PR is merged

**Pull request merged**
